### ISSUE TITLE
New configuration folder structure (a suggestion...)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1000]
Several suggestions:

- [ ] Instead of "example-config", the folder should be called "config-templates". This way the two folders would be closer together on a listing and easier to associate
- [ ] The "templates" folder should be placed closer to the crosswalks in the same folder to facilitate the configuration of a new schema
- [ ] The "schemas" folder should be closer to the crosswalks (same folder)
- [ ] The names of the crosswalk folders should be in line with the current documentation, i.e. : Validation, indexing, visualisation, editing

**Comment by hsilva-keep** [comment]
Closing without further actions.
