### ISSUE TITLE
roda-core.properties has some missing features for "core.notification" properties

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1002]
# core.notification.ingest_subject

We currently have 
core.notification.ingest_subject = RODA ingest process finished -

Shouldn't it be something like:
core.notification.ingest_subject = RODA ingest process finished - {VARIABLE}

# Subjects

We have core.notification.ingest_subject but don't have the definition of subjects for any other mail template

# I18n

Shouldn't the subjects be translated into all the languages? shouldn't this be on the translation files?
We don't have all the templates in all the languages, just some.

# Velocity vs handle bars

In the mail templates folder there seems to be two different template systems: Velocity and Handlebars
We should use only one, or if using 2, change the file extension to make it clear.

@luis100 and @hsilva-keep I would like your comments on this.

**Comment by nunovieira220** [comment]
Ingest subject property issue solved on 680d55e6cb188a8a2a5ddd1c87faad37189ecf04

**Comment by luis100** [comment]
variable and i18n issue now at #1024
Velocity vs handlebars issue now at #1023
