### ISSUE TITLE
Refactoring suggestions "org.roda.core.plugins.plugins" to "org.roda.core.plugins.internal"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1005]

**Comment by luis100** [comment]
Note that this refactor can make external plugins cease working because they have dependencies on this code. Suggest to move this to milestone 2.1.

**Comment by jmaferreira** [comment]
Its not a priority.

**Comment by hsilva-keep** [comment]
As RODA version 3 was already released, moving this to next major version.

**Comment by hmiguim** [comment]
Moving to next major version
