### ISSUE TITLE
How do we change the i18n files of the UI?

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1008]
These files are not on the config-examples folder as the server messages are.
I understand that it might be a limitation of GWT, but its a pretty nasty one! 

Isn't there  procedure that can be made to update these by normal people?

**Comment by luis100** [comment]
GWT compiles the messages so the interface is fast. Every i18n message that needs this easiness of configuration needs to be brought from the server with an async request, but doing this for all messages would make the interface insufferably slow. So, I recommend we only do this as needed.
