### ISSUE TITLE
Review the terminology of the ingest tasks according to EARK (there are probably some tasks missing as well)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#101]
Quality Control – Security Check

* Check for viruses and other malware. - The system must check the SIP for any infected computer files.

* Check bit integrity. - The system must check the checksums/hash values of computer files.

* Test for compression. - The system must test for compression (illegal if not explicitly granted, i.e. TIFF, MPEG-4), for encryption, password protection, or anything that could prohibit preservability.

Quality Control – Formal validation

* Check package for missing files.- 
The system must offer the option to check that all files listed in the manifest are contained in the SIP.

* Check package for surplus files. - The system must offer the option to check for surplus files (i.e. files not mentioned in the manifest).

* Check package integrity for duplicate files. - The system must offer the option to check for duplicate files.

* Check correctness of application of archival classification scheme. - The system must check if the data is classified according to the included classification scheme.

* Check the conformance of metadata. - The system must check if the metadata conforms to each of the agreed metadata schemas.NB There might be more than one schema. - 

* Validation of codepage/character sets. - Are the codepage/character sets used in accordance with the SIP specification and/or submission agreement?

* Checking document properties. - The system must check for empty content, unexpectedly large documents, and other things that can indicate errors in the SIP creation process.

For databases this includes:
-	data type check (date form)
-	Integrity check
-	Remove duplicate records
-	Apply validation rules (for dates)
Statistical analysis to evaluate the content (completeness for instance).

* Select and deselect automated validation tests. - The system must allow the ability to select and deselect parts of the automated validation tests to accommodate different needs.

Quality Control – Content Review and Approval

* Manual inspection and validation of data. - A validation tool must present the structure and content of SIPs visually in a way that allows manual navigation and validation.

* Report of the SIP approval. - It must be possible to create a report at the conclusion of the SIP ingestion, which could include:
-	Number of computer files in the SIP
-	Overall size of SIP in bytes
-	A list of included files (the manifest) 
-	Date SIP approved
-	Agent who created SIP

Quality Control – Remove “in transfer” flag. 

* Remove the status/flag from exported records and metadata. - The system must support removing the restriction status/flag “in transfer” from exported records and metadata to allow normal activities.

* Identify the search criteria. - The export system must support the specification of the search criteria for data selection. The criteria can be metadata elements and/or metadata values. The flag and IDs can be one of the search criteria. The goal of this requirement is to choose the right search criteria for the search (see the next requirement).

* Search one or many records by metadata elements. - The export system must support the selection of one record or a set of records using search criteria identified in original requirement 2.2 (e.g. date period, retention period). The search parameters can be input manually or selected from pre-defined menus.
The search criteria can be very simple – find all records with an extraction identification code XYZ.

**Comment by luis100** [comment]
@jmaferreira is this done?

**Comment by jmaferreira** [comment]
We are using PREMIS terminology.
