### ISSUE TITLE
Job report created when reindex job creation fails is misplaced

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1015]
When replicating a bunch of AIPs with success using rsync but failing to create a reindex job, a job report is created without source/outcome object id (and well because it applies to several objects).

Nevertheless, we should instead edit last report item of each AIP to state the failure and the reason (besides keeping the information already present about the rsync).

![captura de ecra de 2017-05-29 18 24 14](https://cloud.githubusercontent.com/assets/1315759/26557885/9110c5e2-449c-11e7-9d0f-dc03300271ec.png)

**Comment by nunovieira220** [comment]
Solved on 171598ad6c595dcf89d66e342c1f199f36ab04f7
