### ISSUE TITLE
Remove unnecessary fields from the json used in the "Obtain command" functionality

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1020]
When creating the json for using in the "Obtain command" functionality, all the fields from the Job object are serialized & most of them are irrelevant.

Add new method in JsonUtils
```java
public static String getJsonFromObject(Object object, Object objectClass, Object jacksonMixInClass)
```

Fields to ignore (create JobMixIn class):
- id
- startDate
- endDate
- state
- stateDetails
- jobStats
- inFinalState
- stopping

**Comment by nunovieira220** [comment]
Solved on c9fedfc933aa72d3a7ea803ea843f3735c734de7
