### ISSUE TITLE
When the metadata doesn't have a version we can't re-edit the metadata using the form editor

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1021]
Everything else seems to work, namely:
- Validation
- Indexing
- Edit on New AIP

but it fails on "Edit metadata", showing the XML and not the form.

Example: Look at the behaviour of "key-value" metadata (which doesn't have a version).

**Comment by nunovieira220** [comment]
Solved on 4ae543afc523b1abc094432748be4df9cbdd3f34
