### ISSUE TITLE
The EAD visualisation XSLT has problems in groups, mappings and translations

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1027]
- "Bibliography" is mapped twice.
- There are fields appearing in the wrong ISAD sections.
- The XSLT is based on cycles instead of templates (influenced readability and performance)

**Comment by luis100** [comment]
@chalkos please check if this is solved on the last review of the EAD XSLT

**Comment by chalkos** [comment]
I think this has been fixed by the latest changes, can you check @jmaferreira ?

**Comment by jmaferreira** [comment]
Not really.
There are labels and translations missing in the small example I've seen, so probably there are more stuff missing.

<img width="506" alt="screen shot 2017-08-29 at 17 47 56" src="https://user-images.githubusercontent.com/3181302/29833161-62d81232-8ce2-11e7-9410-5db3a409bed3.png">

**Comment by chalkos** [comment]
F and S are being correctly expanded into Fonds and Series, but it seems there are some cases missing like "P" and "SD".

ODD needs some improvements.

@jmaferreira  Which translations are missing?

**Comment by jmaferreira** [comment]
P = Producer / Produtor
SD = I have no idea

**Comment by hsilva-keep** [comment]
@chalkos as we spoke, one of the problems is you also have to take a look at the descriptive metadata template for ead_2002 because it contains controlled vocabularies that are also not being translated. Using the above example, "minimal" & "final" are not being translated:
![captura de ecra de 2017-09-01 12 00 32](https://user-images.githubusercontent.com/1315759/29967160-2d3ac340-8f0d-11e7-98cd-ddd479b4482e.png)

**Comment by jmaferreira** [comment]
@chalkos Bruno, this problem is still standing... It's been 4 months now..

**Comment by jmaferreira** [comment]
Name of creators is not being shown on the viewer, but it's displayed on the editor.

<img width="1382" alt="screen shot 2017-10-23 at 18 04 53" src="https://user-images.githubusercontent.com/3181302/31902448-ce79ca34-b81c-11e7-837d-ab76fe4c26a1.png">

**Comment by chalkos** [comment]
@jmaferreira Well, in my defense, I was only assigned 2 months ago :]
I agree that this template needs a major revision. We'll talk tomorrow in order to prioritise this.

**Comment by jmaferreira** [comment]
Fair enough! :)

**Comment by chalkos** [comment]
This has been fixed. See issues #1067, #1068, #1070 and #1071 for more details
