### ISSUE TITLE
Disable showing all results when entering search

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1029]
On very big indexes, this is an expensive query that is done every time with no added value for the user.

**Comment by nunovieira220** [comment]
Done on 469302ba0d094aefc2e94798a33a6a5c4b389228. Please review it @luis100

**Comment by luis100** [comment]
Missing the facets

**Comment by luis100** [comment]
Missing the check-boxes, can do actions.

**Comment by nunovieira220** [comment]
Review it again @luis100 please.

**Comment by luis100** [comment]
The ENTER on the search bar ceased to work
@chalkos please check why-

**Comment by hsilva-keep** [comment]
Confirmed that enter works. Closing the issue.
