### ISSUE TITLE
Add checkboxes to all the browsing tables on the catalogue to enable subsequent actions such as Start Job, Delete, etc.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#103]

**Comment by vitorfernandes87** [comment]
The checkboxes appearing can be set on the list constructor.
Added checkboxes to the following tables:

- Intelectual entities search results
- Representations search results
- Files search results

The AIP list on browse page needs to have checkboxes?

**Comment by jmaferreira** [comment]
At this point I’m not sure. We’ll see.

**Comment by vitorfernandes87** [comment]
Ok...
The "select all pages of this search" prompt should appear in every lists with checkboxes or only in some of them?
Right now the prompt appears in every list with checkboxes.
