### ISSUE TITLE
Limit result size of CSV export on WUI

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1030]
When clicking the Export on a search result it may be exporting millions of documents, which may affect performance. Limit it by default to 1000 results and allow this limit to be configured in roda-wui.properties.

**Comment by luis100** [comment]
On the REST API allow to define the limit via parameter.

**Comment by nunovieira220** [comment]
Done on 5b4a1493e410b4dffd4e374cc73edd7c67439ef7. Please review it @luis100.

**Comment by luis100** [comment]
Needs warning that explain that only LIMIT will be exported

**Comment by nunovieira220** [comment]
Done on dbb1eb5bd1dd9cc67babad8c6327170af9c2b4eb.
