### ISSUE TITLE
"Move orphan(s) to a parent node (1.0)" plugin reporting is wrong

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1040]
In the end it keeps objects in "waiting", it should count all orphans and non orphans as a success.
Also it should only report on the detected orphans.
![roda - 8ebb17ba-987a-491d-a236-677097086ecc](https://user-images.githubusercontent.com/631728/28666647-2c5aee8c-72c0-11e7-8228-16da6f0117f1.jpg)

**Comment by nunovieira220** [comment]
Can you review it @luis100 ?
