### ISSUE TITLE
Review preservation events based on the new PREMIS vocabulary

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1046]
We need to check if all the events we are producing are in line with the official vocabulary:
http://www.loc.gov/standards/premis/v3/preservation-events.pdf

**Comment by jmaferreira** [comment]
Revised & improved PREMIS eventType vocabulary now live:

http://id.loc.gov/vocabulary/preservation/eventType.html?t=1&cn=ZmxleGlibGVfcmVjc18y&refsrc=email&iid=4addd72342424e2886418511e5884299&uid=1171786716&nid=244+272699400

The final contenders:

- accession
- appraisal
- capture
- compression
- creation
- deaccession
- decompression
- decryption
- deletion
- digital signature generation
- digital signature validation
- dissemination
- encryption
- filename change
- fixity check
- forensic feature analysis
- format identification
- imaging
- information package creation
- information package merging
- information package splitting
- ingestion
- ingestion end
- ingestion start
- message digest calculation
- metadata extraction
- metadata modification
- migration
- modification
- normalization
- packing
- policy assignment
- quarantine
- recovery
- redaction
- refreshment
- replication
- transfer
- unpacking
- unquarantine
- validation
- virus check

**Comment by jmaferreira** [comment]
Add to https://github.com/keeps/roda/blob/master/roda-common/roda-common-data/src/main/java/org/roda/core/data/common/RodaConstants.java#L1159

**Comment by nunovieira220** [comment]
Preservation event types added
