### ISSUE TITLE
Incomplete tooltip

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1051]
The tooltip for the process info of an AIP is incomplete.

<img width="271" alt="screenshot of google chrome" src="https://user-images.githubusercontent.com/98429/30274108-e76070ec-96f3-11e7-951a-f7be09973429.png">

In the image, when the mouse is over `Process: 85523f82-8b76-48f5-9f50-6a96d5f5eb4b` the tooltip simply shows `Process: `

**Comment by nunovieira220** [comment]
Done on 65be961ff4979cb017b3a070a17d6ccc5812a62e
