### ISSUE TITLE
Break lines on the visualisation XSLT are not being preserved

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1055]
I mean... if the original text has break lines we should display them on the HTML.

I'm not sure how easy this is to do with a XSLT.

**Comment by luis100** [comment]
Break lines are being preserved but lost on the HTML. This can be done via CSS with `white-space: pre;`

**Comment by jmaferreira** [comment]
That’s not a great strategy!
Long lines will break the UI. We need to use <br> instead.

**Comment by jmaferreira** [comment]
@luis100 This issue is under screening, please put it in a milestone if you feel its relevant.

**Comment by jmaferreira** [comment]
Only apply to EAD_2002 and DCSimple_xpto

**Comment by chalkos** [comment]
I also applied it to DC, the change was the same as DCSimple_xpto (it only applied to the "description" multiline field).

**Comment by chalkos** [comment]
The ead was already done.
