### ISSUE TITLE
When using the UI to create representations and upload files the clip icon is not displayed

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1057]
The same happens when we remove the representation. The clip is not removed.

<img width="1311" alt="screen shot 2017-10-23 at 18 26 37" src="https://user-images.githubusercontent.com/3181302/31903357-cc7ddbdc-b81f-11e7-9721-4561aab28ee3.png">

**Comment by hsilva-keep** [comment]
This happens because when a representation is created, only Representation index is manipulated. What we need to do is check AIP for the state of the boolean hasRepresentations, and update it accordingly. This needs to be done in both representationCreated & representationDeleted.

**Comment by nunovieira220** [comment]
Done on a982d1b5fee7a8d439044cdee8f7a263eef35ddc
