### ISSUE TITLE
Update translation Change States > Change Status

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1058]
There are some situations where status may be considered countable. In those cases, the plural form can be used as statuses. MacMillan dictionary gives 3 definitions for status, and 2 of them are referred to as countable & uncountable. Personally, I would use status as the plural form instead of statuses.

More on the subject - https://en.wikipedia.org/wiki/Talk%3AStatus#Plural_of_status

**Comment by nunovieira220** [comment]
Done on ce503acbf69c5c3ba6ece28f82f5c4a69bd75dcc
