### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by GolikSwe** [keeps/roda#1062]
We are trying to use our own customised XML-schemas for the AIP and representation levels. Now we need to be able to search after values in one of the fields of the customised metadata called <destructiondate>. 
For instance we want to find all packages in a series that has a destructiondate that has passed, that is “todays date” > “destruction date”. Se XML-example below.

 <?xml version="1.0" encoding="UTF-8"?> <gip>
 	<origdesc>abcdefgh</origdesc>
	 <infoversion>1</infoversion>
	<packagetype>siard2</packagetype>
	 <producer>abcdefgh</producer>
	<destructiondate>2020-01-01</destructiondate>
	<destructionstatus>none/appraised/in bin/destroyed</destructionstatus>	<infoclass>1</infoclass>
	<agreementid>tv-eh-12</agreementid>                                         
	<racode>3.1.1</racode> 
</gip>

We have no problem creating SIPs as well as loading them into RODA and validating them against our customised schema. However when we try to use the “advanced search” searching after (e.g. destructiondate) in the metadata when we cannot find the AIPs.

Probably we need to make some more changes in some SOLR config file or other config file? (Changes made to configuration files, roda-wui.properties, ServerMessages.properties) 

It would be great if we could get some tips on where to change, and in which files. How should we configure to make our customised metadata searchable for a particular field on the package and representation levels?

**Comment by luis100** [comment]
Several steps to do it:
1. Generate SIPs with your new desc. metadata type and version
2. Configure RODA to index your new desc. metadata format
3. Configure RODA to show fields in the advanced search menu

Optional:
* Configure RODA to display your metadata
* Configure RODA to allow to edit your metadata with a form


## 1. Generate SIPs with your new desc. metadata type and version
On the SIP you must define the descriptive metadata type and version. As you are using your own, you should define metadata type OTHER, other metadata type e.g. "GolikSwe" and metadata type version e.g. "1". This can be done directly in the METS or using the [RODA-in application](http://rodain.roda-community.org/) or the [commons-ip library](https://github.com/keeps/commons-ip).

## 2. Configure RODA to index your new desc. metadata format
On RODA, you must configure how it can index this file. To do so, you must define the XSLT under `$RODA_HOME/config/crosswalks/ingest/` with a name that is calculated by your metadata type and version. 

On the example with metadata type=OTHER, other metadata type="GolikSwe" and metadata version 1, you must create the file  `$RODA_HOME/config/crosswalks/ingest/golikswe_1.xslt`.

You can look at examples in the `$RODA_HOME/example-config/crosswalks/dissemination/ingest/` or the [online version](https://github.com/keeps/roda/tree/master/roda-core/roda-core/src/main/resources/config/crosswalks/ingest).

The resulting XML must be something like:
```xml
<doc>
  <field name="title">abcdefgh</field>
  <field name="origdesc_txt">abcdefgh</field>
  <field name="destructiondate_txt">2020-01-01</field>
  <field name="destructiondate_dd">2020-01-01T00:00:00Z</field>
</doc>
```
Rules:
- There are some reserved field names, specially `title`, `dateInitial` and `dateFinal`, that define what appear on the lists
- You can add new specific fields, but must always add a suffix for the data type. The most used suffixes are "_txt" (any string tokenized), "_ss" (non-tokenized strings for identifiers), "_dd" for ISO1601 dates.
- A complete list of reserved fields names and suffixes is available on the [AIP SOLR schema](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/resources/config/index/AIP/conf/schema.xml).

To apply the changes on the stylesheet you must ingest new content or re-index existing content.

## 3. Configure RODA to show fields in the advanced search menu

Change your `roda-wui.properties` to [add an new advanced search field item](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/roda-wui.properties#L165):

```javaproperties
ui.search.fields.items = destructiondate # add new field to the list of fields for items (i.e. AIPs), other options are representations or files
ui.search.fields.items.destructiondate.fields = destructiondate_txt # the id of the field in the index, equal to the one on the stylesheet you create
ui.search.fields.items.destructiondate.i18n = ui.search.fields.items.destructiondate # key for the translation in ServerMessages.properties
ui.search.fields.items.destructiondate.type = text # the type of the field which influences the search form input
ui.search.fields.items.destructiondate.fixed = true # if it appears on advanced search by default or if it needs to be added via the "ADD SEARCH FIELD" button.
```
You should also add the necessary translations to your `$RODA_HOME/config/i18n/ServerMessages.properties`, and in all languages you which to support.

Add [a translation for your new metadata type and version](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/i18n/ServerMessages.properties#L121):

```javaproperties
ui.browse.metadata.descriptive.type.golikswe_1=Golik SWE (version 1)
```

Add [translations for your fields](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/i18n/ServerMessages.properties#L2):
```javaproperties
ui.search.fields.items.destructiondate= Destruction Date
```

A similar system is implemented to support [configure RODA to display your metadata](https://github.com/keeps/roda/tree/master/roda-ui/roda-wui/src/main/resources/config/crosswalks/dissemination/html),  and [configure RODA to allow to edit your metadata with a form](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/templates/). But this comment is already too big. Developing documentation is still in our roadmap.
