### ISSUE TITLE
There are templates and XSLTs called "EAD". Is this obsolete?

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1065]
There is a EAD_2002 that I believe replaces the EAD file. No?
If so, remove them from base.

<img width="341" alt="screen shot 2017-11-10 at 14 35 46" src="https://user-images.githubusercontent.com/3181302/32663067-9442cb5c-c624-11e7-96d9-f3913554358c.png">
<img width="316" alt="screen shot 2017-11-10 at 14 35 22" src="https://user-images.githubusercontent.com/3181302/32663068-945c38e4-c624-11e7-9c80-d638b6c639fe.png">

**Comment by luis100** [comment]
It is not obsolete, it is the used default in case the EAD version is not declared.

**Comment by jmaferreira** [comment]
Ok. Do we need to update these XSLT as well?

**Comment by luis100** [comment]
Having a separated stylesheet for fallback is too much maintenance work. It should be a symbolic link to the EAD 2002 XSLT.

**Comment by chalkos** [comment]
the symlinks are:

```
roda-core/roda-core/src/main/resources/config/crosswalks/ingest/ead.xslt -> ead_2002.xslt
roda-ui/roda-wui/src/main/resources/config/crosswalks/dissemination/html/ead.xslt -> ead_2002.xslt
roda-ui/roda-wui/src/main/resources/config/templates/ead.xml.hbs -> ead_2002.xml.hbs
```
