### ISSUE TITLE
advanced search in representation

### ISSUE THREAD

**Issue by GolikSwe** [keeps/roda#1075]
Has a question about search in the metadata representation field. Can we use our own XML schema and create advanced search in the drop down list against our own representation metadata. Is this possible at the representation level?

**Comment by luis100** [comment]
Yes you can.

You can define crosswalks for viewing ([config/crosswalks/dissemination/html](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/crosswalks/dissemination/html/dc_SimpleDC20021212.xslt)) for indexing ([config/crosswalks/ingest](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/resources/config/crosswalks/ingest/dc_SimpleDC20021212.xslt)), define schema for validation ([config/schemas](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/resources/config/schemas/dc.xsd)), and [forms for editing](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/templates/dc_SimpleDC20021212.xml.hbs).

Then you can define the [representation advanced search configuration in the roda-wui.properties](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/roda-wui.properties#L250).

**Comment by luis100** [comment]
Note that you can use your own XML schemas on both AIP and representation level without any diference on the base configuration, as they are set by the descriptive metadata type and version. The only difference is then on the configuration of the advanced search between AIP and Representation levels.

**Comment by GolikSwe** [comment]
I have made the necessary changes so we can do advanced search on item against over own schema and it works well. Now we want to try to do advanced search at the representation level. The schema we use is Dublin Core (DC) and we want to do advanced search on the “subject” field in DC. Has done the same changes as on item configuration, changes in roda-wui
ui.search.fields.representations = subject
ui.search.fields.representations.subject.fields = subject_txt
ui.search.fields.representations.subject.i18n = ui.search.fields.representations.subject
ui.search.fields.representations.subject.type = text
ui.search.fields.representations.subject.fixed = true

changes in ServerMessages
ui.search.fields.representations.subject=Subject
As well as created an xsl file in, $RODA_HOME/config/crosswalks/ingest/
this does not work, what is wrong?

**Comment by luis100** [comment]
@GolikSwe does the advanced search option appear? Did you re-index? Are there log errors?

**Comment by GolikSwe** [comment]
This is output from dc.xslt file, shows the indexing field for Dublin Core
doc>
   <field name="title">Title sip</field>
   <field name="title_txt">Tirle Asip</field>
   <field name="identifier_txt">uuid-3273bd8c-c6cf-439d-a2fa-198a00cd0c97</field>
   <field name="language_txt">sv</field>
   <field name="relation_txt">none</field>
   <field name="subject_txt">test, more test, dog, cat</field>
   <field name="level">item</field>
</doc> 
For subject, the index is subject_txt

Yes the advanced option for subject appear and i have re-index RODA. I have also re-started the tomcat.
Have also checked RODA's logs and could not find any errors, have also run “tail -f 50” on RODA:s logs but nothing wrong has appeared. I can do advanced search on the subject in representations but I will not get any response back (empty field back ) even if I know there are values for searching in subject field.

**Comment by luis100** [comment]
@GolikSwe it seems that we might have a bug here, that as been potentially solved on pull request https://github.com/keeps/roda/pull/1103

We will review this pull request this week, but in the meanwhile you might want to test it with your data. If so, you might want to clone @beepsoft fork that has the pull request,  compile it to generate the docker image and test:
```bash
git clone https://github.com/beepsoft/roda.git
cd roda
 mvn package -Dmaven.test.skip -Denforcer.skip -Proda-wui-docker
docker run ...
```

**Comment by luis100** [comment]
@GolikSwe please test the following version that should have fixed the problem:
```
docker pull keeps/roda:development
```

**Comment by luis100** [comment]
relevant commit is 4dfd27b725cd828f113750285b50e72e9f8c628c
