### ISSUE TITLE
Obtain last report using transferred resource filename

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1076]
ATM, when obtaining last report via REST API (/v1/reports/last), the only options are:
* SIP - by SIP ID or SIP original IDs
* Transferred Resource Path - relative path to transferredResources folder
* Transferred Resource UUID - UUID of the transferred resource

The new one will use **sourceObjectOriginalName** field.

**Comment by nunovieira220** [comment]
Done on 78017b0602731395f81c9e34c38b8889cf0bbe1f
