### ISSUE TITLE
Define relation types for Representation Information and Intellectual entities

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1078]
There should be two distinct vocabularies for RI relations with other RI and with AIPs

![screen shot 2017-11-22 at 17 36 07](https://user-images.githubusercontent.com/3181302/33141648-b3107f4e-cfab-11e7-9891-6bd415299f7d.png)

**Relations with other Representation information records (these are all DCMI relations):**

- Conforms to
- Has created
- Was created by
- Has format 
- Is format of
- Has part
- Is part of 
- Has version 
- Is version of 
- References
- Is referenced by
- Replaces
- Is replaced by
- Requires
- Is required by
- Has source
- is source of

**Relations with AIPs:**

- Rendered by
- Executed by
- Specified by
- Represents

 **Relations with text resources (these are all DCMI relations):**

- Conforms to
- Has created
- Was created by
- Has format 
- Is format of
- References
- Is referenced by
- Has source
- is source of

 **Relations with Web resources (these are all DCMI relations):**

- References
- Is referenced by
- Has source
- is source of
- Specified by

**Comment by chalkos** [comment]
There are also relations with "Web" and "Text", which relation types should be available for those?

**Comment by jmaferreira** [comment]
Updated vocabulares on main description. Have fun.

**Comment by nunovieira220** [comment]
Done
