### ISSUE TITLE
Representation information families

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1079]
Create the following families as default:

- File format
- Software
- Organisation
- Data

------
OAIS v2 (https://public.ccsds.org/pubs/650x0m2.pdf) suggests the following taxonomy:

- Structure
- Semantics
- Software
- Algorithm
- Encryption
- Written instructions
- Representation rendering software
- Access software

[...] The taxonomy of Representation Information presented here is far from complete. For example software, algorithms, encryption, written instructions and many other things may be needed to understand the Content Data Object, all of which therefore would be, by definition, Representation Information, yet would not obviously be either Structure or Semantics. Information defining how the Structure and the Semantic Information relate to each other, or software needed to process a database file would be regarded as Other Representation Information.

Two special types of Representation Information are **Representation Rendering Software** and **Access Software**.

**Representation Rendering Software** is able to display the Representation Information in understandable forms. For example, the file and directory structure of many CD-ROMs conforms to ISO 9660. This standard is Representation Information describing how most CD-ROM file structures are to be implemented, and it may be obtained as a paper document. However, it may also be obtained as a digital object that needs to be understood as a PDF object. Rather than actually obtaining the documentation of PDF and writing software to understand the ISO 9660 object, an OAIS may use available PDF display software to render the ISO 9660 documentation humanly visible and readable. In this role the PDF display software is referred to as Representation Rendering Software because it is used to render the Representation Information. It also terminates the Representation Network. If the OAIS does not also obtain the associated description of PDF, it needs to record and track this fact because when PDF objects are no longer cost-effective for access and display, the ISO 9660 documentation expressed as a PDF object will need to be migrated to a new form.

**Access Software** presents some or all of the information content of an Information Object in forms understandable to humans or systems. It may also provide some types of access services, such as displaying, manipulating, processing, or sub-setting, to an Information Object. For some types of Digital Objects, such software may be widely available. It is not necessary for the OAIS to maintain or provide such software. The OAIS may want to maintain and provide this software for more specialized types of Digital Objects.

More info at http://wiki.dpconline.org/index.php?title=4.2.1.3.1_Representation_Information_Types 

-----

Custom fields should be created for each type. For example, this page should serve as inspiration to determine the custom attributes for the file format family - https://fileinfo.com/extension/pdf 

This page should be used as inspiration for the software attributes - https://fileinfo.com/software/adobe/reader

**Comment by luis100** [comment]
This has been done on #1092, #1093,#1094,#1095
