### ISSUE TITLE
Add help text to Representation Network list page

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1088]
Representation information is any information required to understand and render both the digital material and the associated metadata. Digital objects are stored as bitstreams, which are not understandable to a human being without further data to interpret them. Representation information is the extra structural or semantic information, which converts raw data into something more meaningful.

Representation information should contain as much structure and semantic information as is required for a defined community (or [Designated Community](https://en.wikipedia.org/wiki/Designated_community) in OAIS terminology) to access the information stored within a digital object.

Representation information is not the same thing as metadata which describes data in administrative, descriptive, technical, structural and preservation terms. The term can be applied to all levels of abstraction and refers to both the structural and semantic composition. It can therefore be recursive and is dependent on the knowledge base of the designated community. 

This page allows the preservation expert to define [Representation Information](LINK TO DOCUMENTATION ARTICLE ABOUT REPRESENTATION INFORMATION) and to link it to Intellectual Entities in the repository.

**Comment by chalkos** [comment]
Do you want me to translate this to pt-PT and es-CL?

**Comment by jmaferreira** [comment]
Translate to PT, please.
Leave it in English for the Spanish version.

**Comment by chalkos** [comment]
> A informação de representação é qualquer informação necessária para entender e renderizar o material digital e os metadados associados. Os objetos digitais são armazenados como sequências de bits, que não são compreensíveis para um ser humano a não ser que se façam acompanhar de informação que auxilie a interpretação dos bits. A informação de representação é a informação extra estrutural ou semântica, que converte dados em bruto em algo mais significativo.
> 
> Esta página permite que o especialista em preservação defina <a href="#theme/Representation_Information.md">Informações de representação</a> e vinculá-las às Entidades Intelectuais no repositório.

@jmaferreira close this if the translation is ok

**Comment by jmaferreira** [comment]
Its ok. Carry on, carry on...

**Comment by chalkos** [comment]
:laughing: :tada:
