### ISSUE TITLE
Change menu item "Representation information registry" to "Representation network"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1090]
FROM OAIS v2 (https://public.ccsds.org/pubs/650x0m2.pdf):

_Representation Information is an Information Object that may have its own Data Object and its own Representation Information associated with understanding each Data Object, as shown in a compact form by the ‘interpreted using’ association. The resulting set of objects can be referred to as a Representation Network._

**Comment by chalkos** [comment]
Done
