### ISSUE TITLE
Replace the design of the top "X" with the design of the "X" on the bottom example

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1091]
Its too heavy.

<img width="301" alt="screen shot 2017-11-23 at 15 51 41" src="https://user-images.githubusercontent.com/3181302/33180920-49193a52-d066-11e7-8a18-f4a2002f6fad.png">

**Comment by chalkos** [comment]
Looks good? 
![image](https://user-images.githubusercontent.com/98429/33340736-dabd5800-d474-11e7-9a08-209b66d101be.png)

**Comment by jmaferreira** [comment]
Try removing the grey background on the X, i.e. the X should sit outside the textbox.

**Comment by chalkos** [comment]
like this?

horizontal:

![image](https://user-images.githubusercontent.com/98429/34561212-d2cbda02-f140-11e7-955b-093ce3be7c75.png)

vertical:

![image](https://user-images.githubusercontent.com/98429/34561297-3f0f0932-f141-11e7-903d-c949892816be.png)

**Comment by jmaferreira** [comment]
Must experiment to be able to opinate.

**Comment by chalkos** [comment]
suggested changes done in 0e34c19
