### ISSUE TITLE
Link to developers guide on RODA demo footer is broken

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1100]
<img width="201" alt="screen shot 2017-11-28 at 10 37 58" src="https://user-images.githubusercontent.com/3181302/33315393-7c5cba0e-d428-11e7-80f3-b33619f92607.png">

Should point to:
https://github.com/keeps/roda/blob/master/documentation/Developers_Guide.md

**Comment by chalkos** [comment]
Actually, I think it should point to the documentation available locally at `#theme/Developers_Guide.md`

**Comment by jmaferreira** [comment]
Yes.

**Comment by jmaferreira** [comment]
Check all the links again... please. This is an old issue.

**Comment by chalkos** [comment]
It is an old issue indeed. I knew I fixed the footer before https://github.com/keeps/roda/commit/1c706adefb768b05b986e062e6b23ee7fb3a74ca :sunglasses:

RODa demo must be outdated.

**Comment by chalkos** [comment]
@luis100 @hsilva-keep can you check the demo?

**Comment by hsilva-keep** [comment]
It "was" outdated because RODA docker latest tag was also outdated. Solved.
