### ISSUE TITLE
Removing a Representation also removes its Intellectual Entity

### ISSUE THREAD

**Issue by beepsoft** [keeps/roda#1105]
I trired this with 2.0. and the  latest 2.2.0-beta1 as well:

1. I cretate an IP calle Foo
2. Inside Foo I create a Representation
3. I check that Foo is actually in he catalogue
4. I go back inside Foo, select the Representation and click Remove
4. The Representation is removed and also Foo cannot be found in the Catalogue anymore.

If there are multiple Representations, deleting any of them results in deletion of the parent IP as well.

**Comment by luis100** [comment]
To remove a representation when looking the IE you must select the checkbox
on the list of Representations, click Actions on the bottom and select
remove. The buttons on the sidebar always affect the scope being viewed, in
this case will remove the whole IE.

This sidebar and list actions behaviour is common to IEs, representations,
files and DIPs, but not to others (like transferred resources) but will in
the future.

Em 01/12/2017 15:06, "beep" <notifications@github.com> escreveu:

**Comment by luis100** [comment]
See #885 for more information

**Comment by beepsoft** [comment]
Oh, yes, you are right, my mistake!

What got me confused is the confirmation text: "Are you sure you want to remove the selected items, including all their nested items?" And in my mind the selected items were the representations.

Maybe the confirmation dialog's title could reflect the type of the object to be removed to make it clear for the users. The title is currently a generic "Confirm remove items".

**Comment by luis100** [comment]
That is true, created #1106

**Comment by beepsoft** [comment]
Just a note: In case of "Ingest transfer" list there are no list actions, so checking an item in the list and clicking the sidebar Remove button removes the selected element. This is a bit of inconsistency compared to other list views.

**Comment by luis100** [comment]
Yes, that is true and we are aware of that. This change on behavior is not propagated on every entity of the model. This is what is being managed at #885

**Comment by beepsoft** [comment]
Great, thanks for the clarification!
