### ISSUE TITLE
Intellectual Entity remove dialog text is not clear enough

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1106]
@beepsoft says:
> Maybe the confirmation dialog's title could reflect the type of the object to be removed to make it clear for the users. The title is currently a generic "Confirm remove items".

**Comment by beepsoft** [comment]
I would suggest to make the title reflect the type for all kind of objects, not just Intellectual Entities.

**Comment by jmaferreira** [comment]
Validated. Works well.
Thanks for the suggestion @beepsoft.
