### ISSUE TITLE
Get the information in an item

### ISSUE THREAD

**Issue by GolikSwe** [keeps/roda#1107]
Yet another question about search, what we want to do is to search and get the information in an item.
Example element destructiondate> 2020-01-01</ destructiondate. As it is now in avanced search (2020 *), we will get all AIPs after this year. 

What we want to test is if it is possible to get a list of all destruction dates, like
Destructiondate: 2020-01-01, 2020-05-14... 2020-09-01

Is this possible to do without reindexing to search the information in an item and create a list and if so how?

**Comment by luis100** [comment]
You should index the destructiondata field as a date. To do so, looking at the [AIP index configuration](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/resources/config/index/AIP/conf/schema.xml), you should use a dynamic field that is related with dates:

```xml
  <dynamicField name="*_dt"  type="date"    indexed="true"  stored="true"/>
   <dynamicField name="*_dts" type="date"    indexed="true"  stored="true" multiValued="true"/>
```

So you can use `destructiondata_dt` is there is only one destruction date per record or `destructiondata_dts`if there are multiple.

Note that then you need to index dates a restricted variant of the ISO8601 format, specifically `1995-12-31T23:59:59Z`, [check the rules here](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/resources/config/index/AIP/conf/schema.xml#L274).

The you can set in roda-wui.properties an advanced search field of type date and it will automatically give you advanced search form inputs for search in a range and date pickers.

But you must reindex data to do these operations. Does this fit your requirements?
