### ISSUE TITLE
Change edit associations dialog

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1109]
![image](https://user-images.githubusercontent.com/98429/33730362-a99dfbee-db77-11e7-803d-5087cb79707e.png)

- [x] remove the rectangle to the right of the dropdown (use a white background)
- [x] change the title to "Edit associations"
- [x] change the input fields background to white

**Comment by jmaferreira** [comment]
There is a problem with the way the new fields appear.
Try the following... instead placing new boxes bellow the input field that has the ADD button, try placing them on top -- this way the add button is always the one on the bottom.

**Comment by chalkos** [comment]
@jmaferreira I implemented your suggestion in the referenced commit above, but the whole thing feels sluggish...

But lets discuss this on #1125. This issue is done, but the other one seems to have been closed by mistake.
