### ISSUE TITLE
Integrated notification system

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#111]
R23, R24

**Comment by jmaferreira** [comment]
The requirements are:

* A method or notification component that handles sending emails to users
* The API of this component should be able to take the following parameters:
  * Recipient users or emails
  * From users or emails
  * Subject of the message
  * Body of the message (HTML or just TXT, not sure which one at this point)
  * The body should support some variables to be replaced by the notification component (e.g. recipient name, acknowledge URL)

* Each message sent should be stored on the storage (JSON?) and indexed for future consultation on the UI
* For each message it should store the timestamp of message (auto generated) and a auto generated token for each recipient.
* There should be a REST service (GET method with token authentication) that one could include inside the body of the email to enable recipients to acknowledge the reception of the notification. The acknowledgement should update the JSON file on the storage to store the date of acknowledgement and the name of user that has acknowledged the notification. 
* Various users can receive the notification, and each one of this can do the acknowledge of reception of the notification.

Any questions you may have, talk to @luis100

**Comment by nunovieira220** [comment]
Integrated notification system is done. Each message has a single recipient user and a from "user" that indicates what RODA component is responsible of sending it.
