### ISSUE TITLE
Change IncrementalList

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1110]
Change the buttons from this
![image](https://user-images.githubusercontent.com/98429/33730600-5dbf637e-db78-11e7-9323-0218de7ad0cc.png)

to this
![image](https://user-images.githubusercontent.com/98429/33730987-9ea4cab8-db79-11e7-9e56-f8893cef0f80.png)

Alternatively the `[+]` could be on all text boxes.

Also change the horizontal version of this widget.

**Comment by chalkos** [comment]
Horizontal:

![image](https://user-images.githubusercontent.com/98429/34535530-13d994bc-f0ba-11e7-8c6c-896c5775ebee.png)

![image](https://user-images.githubusercontent.com/98429/34535516-077517be-f0ba-11e7-94c9-a3ca836c016f.png)

Vertical:

![image](https://user-images.githubusercontent.com/98429/34535569-3464280a-f0ba-11e7-9ed6-8b7566a06670.png)

![image](https://user-images.githubusercontent.com/98429/34535609-5bd347e0-f0ba-11e7-8c1a-cd898b5a80a6.png)

**Comment by jmaferreira** [comment]
ok. See comments on #1125 and #1109
