### ISSUE TITLE
Preview results when associating RI

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1112]
When associating RI with AIP, Representations or Files, when the user writes something in a field, a list below should show AIP, Representations or Files filtered by that field.

Eg: writing `pdf` in the extension field (for Files) should show all files with that extension in a list below the form and above the cancel/confirm buttons.

**Comment by chalkos** [comment]
This should wait until we know if the association form needs to be changed (see #1083 for info on that)

**Comment by nunovieira220** [comment]
Done
