### ISSUE TITLE
Change RI Association page subtitle

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1113]
The subtitle should appear inside the cardbox.
It should be blue with the `(i)` icon when showing a list.

**Comment by chalkos** [comment]
when there is associated representation information:

![image](https://user-images.githubusercontent.com/98429/34559995-02e84cfc-f13c-11e7-825b-416fbb90886b.png)

when there isnt:

![image](https://user-images.githubusercontent.com/98429/34558949-e910fe4a-f137-11e7-8437-2994f377a8fd.png)

**Comment by jmaferreira** [comment]
Its ok.
