### ISSUE TITLE
Can roda-wui run with mvn gwt:run?

### ISSUE THREAD

**Issue by beepsoft** [keeps/roda#1115]
I would like to start roda-wui from the command line via maven.

It seems that the gwt:run goal is available in the project, but I am not able to start the roda-wui via

`mvn gwt:run
`

My question is: Is gwt:run supported? If it is, what is the correct way to use it?

Thanks!

**Comment by luis100** [comment]
The correct command to run would be the following on the base of the project:
```
mvn gwt:run -pl roda-ui/roda-wui -am
```

But this is not currently working for me, there is some configuration problem. We normally run inside eclipse.
