### ISSUE TITLE
Card filters

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1116]
The following mockups illustrate the idea pretty well. The one that shows only the filters on the bottom as an action button work by displaying a popup with the facet options in it.

![filters left](https://user-images.githubusercontent.com/3181302/34002061-9124e31c-e0e9-11e7-88fa-5e7c277aef8d.png)
![filters right](https://user-images.githubusercontent.com/3181302/34002062-914d2f66-e0e9-11e7-9aec-e8dfb28947d4.png)
![filter action](https://user-images.githubusercontent.com/3181302/34002063-916e881e-e0e9-11e7-88f0-83da5eaf0ba3.png)
![filters at right bg color](https://user-images.githubusercontent.com/3181302/34002064-918a3398-e0e9-11e7-9d91-5223c81eed7d.png)

**Comment by luis100** [comment]
The mockups should be discussed further, but adding this to current milestone as it is a priority.

**Comment by chalkos** [comment]
Done and reviewed.
