### ISSUE TITLE
Adding new categories and then editing them makes the component show the first field empty

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1125]
![screen shot 2018-01-09 at 15 37 00](https://user-images.githubusercontent.com/3181302/34728870-fe354ece-f552-11e7-9fc2-2e1d4b2ab2f9.png)

**Comment by chalkos** [comment]
Reopening this as I misunderstood the issue, fixed a different problem and then closed this issue. Meanwhile this issue was partially discussed in #1109

**Comment by jmaferreira** [comment]
Let me take a look...

**Comment by luis100** [comment]
Basis is good, small issue identified at #1133
