### ISSUE TITLE
When integrated with CAS there is no sign-in log

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1130]

**Comment by luis100** [comment]
- [ ] Method [getOrCreateUser(String)](https://github.com/keeps/roda/blob/b008cc81df32f9d27253254818325d7bf4d270e8/roda-ui/roda-wui/src/main/java/org/roda/wui/filter/CasWebAuthFilter.java#L152) uses a catch GenericException to infer that user does not exist but [LdapUtility.getUser(String)](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/java/org/roda/core/common/LdapUtility.java#L405) states null is returned if user does not exist, check which one applies and fix accordingly (nevertheless, if exception is used NotFoundException is the most appropriate one)
- [ ] Log duration is incorrect due to controller assistant constructor and register method being together, also may want to change the method or use a different one to cope with log register
- [ ] Provide translation of log component

![roda - activity log 1](https://user-images.githubusercontent.com/631728/34993684-108e541e-fac9-11e7-8ec2-34e0a97b220e.jpg)

**Comment by chalkos** [comment]
> Method getOrCreateUser(String) uses a catch GenericException to infer that user does not exist but LdapUtility.getUser(String) states null is returned if user does not exist, check which one applies and fix accordingly (nevertheless, if exception is used NotFoundException is the most appropriate one)

checking if the user exists by checking if it is null

I'm not sure about what to do with all the exceptions that are thrown when getting/creating a user. Maybe I'm not calling the right methods...

> Log duration is incorrect due to controller assistant constructor and register method being together, also may want to change the method or use a different one to cope with log register

Can't use a different one as they (at least the ones that seemed to do what I want) are protected/private. The duration time now corresponds to the time it took to get (or create and get) the user.

> Provide translation of log component

done

**Comment by luis100** [comment]
Checked.
