### ISSUE TITLE
Rep. Information - Associate to existing

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1143]
- [x] Also enable scroll
- [x] Add to existing button should use pencil icon
- [x] "Add to new" should become "Create new"
- [x]  Less items on list

**Comment by chalkos** [comment]
I didn't do the scroll as no other dialog has it and since we are showing less items on the list I dont think scrolling is necessary. Let me know your opinion on this.

@nunovieira220 changed the title in another commit

**Comment by jmaferreira** [comment]
I guess because the other lists are not in popups. What happens if we raise the number of visible items? We’ll end-up with a popup window that is larger than the screen?

**Comment by chalkos** [comment]
I found an existing example of a scrolling list in a dialog (Move AIP) and replicated it for RI associations.
