### ISSUE TITLE
IncrementalList enhancements

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1147]
- [x] On creating a new textbox set focus so one can start writing without having to select the textbox
- [x] When writing on the bottom textbox and pressing ENTER on keyboard add a new textbox (same as clicking the [+])

**Comment by chalkos** [comment]
I also set the focus on the last textbox when one of them is removed.

**Comment by chalkos** [comment]
when pressing enter on a textbox other than the last one, focuses (and selects all text) the next one, just like pressing TAB.

Additionally, pressing CTRL,ALT,MOD or SHIFT together with ENTER has no effect.

**Comment by luis100** [comment]
Use http://www.gwtproject.org/javadoc/latest/com/google/gwt/event/dom/client/KeyCodes.html instead

**Comment by chalkos** [comment]
done: f06541e

**Comment by luis100** [comment]
checked.
