### ISSUE TITLE
Dialogs should not always have max width to 60vw

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1153]
The following example should be able to use more that 60% of the viewport.
![roda - planning 1](https://user-images.githubusercontent.com/631728/35393917-40919db2-01de-11e8-808b-a00941a76421.jpg)

Furthermore, the `!important` css modifier should be avoided.

Also, it should not restrain the width below the size of the components.

Finally, the dialog should use the available space in a better way, but this is an enhancement possibly difficult to add.

**Comment by luis100** [comment]
the dialog-scroll show not define the width (is should be limited by the dialog max-width, e.g. 90vw in the case of the dialog above), and should define min-height (e.g. 100px) and max-height relative to the viewport.

**Comment by chalkos** [comment]
I didn't follow all the suggestions, but the changes I made make the RI dialogs use the available space in a more natural way
