### ISSUE TITLE
Error while saving representation information

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1156]
I pasted a large HTML into a HTML field.

![screen shot 2018-02-22 at 16 59 00](https://user-images.githubusercontent.com/3181302/36552487-e9774052-17f1-11e8-9569-5450351240c4.png)

**Comment by nunovieira220** [comment]
Problem is solved since HTML is not used anymore.

**Comment by jmaferreira** [comment]
Have you updated the migration scripts to handle the URLs properly?
