### ISSUE TITLE
Date range search filters on the interface don't cope with different time zones

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1159]
For example, on the Ingest Process list, you can filter by dates (start day and end day), and the search should include all results for that time span, using time 0 for the start date and time 0 + 1 day - 1 millisecond for the end date.

But this page gives different results for users in browsers in different time zones.

**Comment by nunovieira220** [comment]
Done on 8c1551a54b21c4e76837c285b22c961e77797c26
