### ISSUE TITLE
Support for digital signatures on DIPs

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#116]
R45

**Comment by nunovieira220** [comment]
Support added as a RODA Plugin for PDF, OOXML and ODF format files.

**Comment by luis100** [comment]
@jmaferreira Should be done, please test and close.

**Comment by luis100** [comment]
@jmaferreira please test and close

**Comment by jmaferreira** [comment]
The plugin has left the building and is nowhere to be found... Please add it to the list of plugins.

**Comment by nunovieira220** [comment]
The plugin was already added back to the core plugins.

**Comment by jmaferreira** [comment]
This plugin is not shown on the list of plugins... how should I test it?

**Comment by nunovieira220** [comment]
It is only shown when selecting "All representations" option because, at the moment, the plugin only runs on representations.

**Comment by luis100** [comment]
@jmaferreira is this issue done? should it be closed?

**Comment by jmaferreira** [comment]
Not tested yet. I need a demo to understand how it works.

**Comment by luis100** [comment]
This will have to be redone using the DIP mechanism, which is not yet implemented.
Blocked by #454

**Comment by nunovieira220** [comment]
The plugin now supports DIP creation instead of a new representation on the AIP. Please review it.

**Comment by luis100** [comment]
It needs to be available on the interface first.

**Comment by luis100** [comment]
blocked by #671

**Comment by luis100** [comment]
unblocked and tested.

**Comment by luis100** [comment]
Issue about lack of reporting when keystore not created is at #725
