### ISSUE TITLE
When we click the links on the theme, and the supporting text is in markdown the page is loaded but not positioned on top

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1167]
This is extremely annoying... 

<img width="1792" alt="screen shot 2018-03-10 at 09 55 26" src="https://user-images.githubusercontent.com/3181302/37240908-65350e78-2449-11e8-891e-41d96d94d63e.png">

Check this as an example of poor UI:

https://roda.arquivos.pt/?locale=pt_PT#welcome

**Comment by chalkos** [comment]
Working for me. Try:

1. go to https://demo.roda-community.org
2. scroll down and click "what is roda" link

the markdown is rendered and the browser scrolls to the top

I'm using chrome on ubuntu

**Comment by jmaferreira** [comment]
No.. not working on Safari or Chrome on Mac.

**Comment by chalkos** [comment]
Ok, I'll look into it
