### ISSUE TITLE
Add pre-wrap to representation information long text values when viewing and increase height when editing.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1168]
On view:

```
.value {
    font-size: 1.6rem;
    color: rgb(88, 89, 91);
    white-space: pre-wrap;
}

```

On edit:

```
.metadata-form-text-area {
    min-height: 250px;
}

```

**Comment by jmaferreira** [comment]
Bruno, see if you can integrate this on the demo for tomorrow!

**Comment by jmaferreira** [comment]
Guys.. this one is pretty simple and important!

**Comment by chalkos** [comment]
I can take care of this tomorrow morning, no worries.

**Comment by chalkos** [comment]
there are more elements using `.value` so I dont want to just paste your CSS in there hoping it will work.

**Comment by jmaferreira** [comment]
Yes.. you might have to put a class or two prepending the .value...

**Comment by chalkos** [comment]
Fixed in https://github.com/keeps/roda/commit/8d8ce9a28f0f568ecc910ba81e682c6d53e757d8
