### ISSUE TITLE
Add "Software history" to the "Sustainability factors" of the Software RI type editor

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1170]
Put it right on top, bellow the "Sustainability factors" label:

<img width="833" alt="screen shot 2018-03-13 at 12 25 32" src="https://user-images.githubusercontent.com/3181302/37341537-a2a3255c-26b9-11e8-8331-3891a1d44624.png">

**Comment by nunovieira220** [comment]
Done on 75388843cbaab3693e3b6d4aa6694659a1ae6a53
