### ISSUE TITLE
Add "Is replaced by" to list of relationships in RI

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1171]
I have a feeling that many of these relationships actually mean the same thing, e.g. Replaces, Has earlier version, Has version, Modification of...
Its hard to pick one.

Also, What is the order of the relations? Can we change the order in the config so that the relation and its inverse are placed together on the list?

<img width="256" alt="screen shot 2018-03-13 at 12 38 32" src="https://user-images.githubusercontent.com/3181302/37342111-80ff88e4-26bb-11e8-910d-491dd8c8acd3.png">

**Comment by nunovieira220** [comment]
@jmaferreira at the moment, when creating, you can only relate in a specific order. For example, you can create a "Replaces" relation but not a "Is related by". When showing the RI then you can see both relations.

**Comment by jmaferreira** [comment]
In that case we really need to clean up the vocabulary

**Comment by nunovieira220** [comment]
@jmaferreira I tried now to create a "Replaces" relation between RIs and the inverse relation was automatically created too.

**Comment by jmaferreira** [comment]
Let me give it a try.

**Comment by jmaferreira** [comment]
Try using the RI relation "Has earlier version". Issues:

- Not all RI records show up
- The inverse relation is not displayed.

Do you confirm?

**Comment by nunovieira220** [comment]
"Has earlier version" does not have an inverse relation defined. The other point is an issue, yes.

**Comment by jmaferreira** [comment]
The inverse of "Has earlier version" is actually on the list!!!
Please take a good look at the list of relation and revise it in an attentive way. Ask @luis100 for help if necessary. Beware of repetitions.

**Comment by nunovieira220** [comment]
Both issue are solved.
