### ISSUE TITLE
RI: wrong title on association popup and list of records now showing everything I have.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1172]
I'm not moving anything...

<img width="1381" alt="screen shot 2018-03-13 at 12 44 14" src="https://user-images.githubusercontent.com/3181302/37342413-6c40d2c2-26bc-11e8-8fed-0a3d05c77133.png">

Furthermore, why doesn't the list include all the RI records and only shows up one? I have hundreds of records.

**Comment by nunovieira220** [comment]
Done
