### ISSUE TITLE
Metadata field DC type should be mapped into RODA Level during indexing

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1174]
@luis100 do you agree?

<img width="669" alt="screen shot 2018-03-13 at 12 55 25" src="https://user-images.githubusercontent.com/3181302/37342903-ea014722-26bd-11e8-93e0-eb1b7a219b6b.png">

**Comment by hsilva-keep** [comment]
Solved since 72816766cc2112c51ab84281cdefbcf900ba3604. If type exists, use it as level, otherwise set level as item.
