### ISSUE TITLE
Add a way of downloading a RI record (XML)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1177]
Only it is a low cost development.

On this page, on the right:

<img width="1729" alt="screen shot 2018-03-13 at 16 51 36" src="https://user-images.githubusercontent.com/3181302/37356960-174e2d82-26df-11e8-90b2-efebf22da960.png">

**Comment by nunovieira220** [comment]
Done on 7485b417287d595dc426830dbe3ffccfa887dace
