### ISSUE TITLE
Should we remove tags from RI list?

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1178]
Makes the UI a little broken:

<img width="1320" alt="screen shot 2018-03-13 at 18 31 09" src="https://user-images.githubusercontent.com/3181302/37362388-f2214a36-26ec-11e8-91d2-de46d027fc4c.png">

@luis100 Do you care to opinate?

**Comment by luis100** [comment]
Tag should follow the same design as when showing a RI record, i.e. a badge (same as the Beta tag on the  screenshot above, but blue).

Some tags are very long (e.g. "Database management system"), so the tags should have a max-width, should define whitespace: nowrap; and text-overflow: ellipsis; and also have a title attribute, so we can see the full text in a tooltip.

To optimize space we could use the same strategy as the GitHub issue list and put the tags on the name column, instead having a column of their own.

**Comment by jmaferreira** [comment]
Lets try that.

**Comment by nunovieira220** [comment]
@luis100 does this look ok?
![screenshot from 2018-03-15 11 08 10](https://user-images.githubusercontent.com/8982932/37459814-2bfc6e98-2841-11e8-95c8-057c48b965eb.png)

**Comment by luis100** [comment]
Looks good
