### ISSUE TITLE
On SIP update add new SIP ids to the AIP

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1183]

**Comment by hsilva-keep** [comment]
E-ARK SIP to AIP plugin: https://github.com/keeps/roda/blob/development/roda-core/roda-core/src/main/java/org/roda/core/plugins/plugins/ingest/EARKSIPToAIPPluginUtils.java#L49 & https://github.com/keeps/roda/blob/development/roda-core/roda-core/src/main/java/org/roda/core/plugins/plugins/ingest/EARKSIPToAIPPluginUtils.java#L91

**Comment by hsilva-keep** [comment]
Done since adbe7ab8164c4fa24a1ec46b1ffdb1fcd4305eb0
