### ISSUE TITLE
When seeing one representation information & clicking in one tag, the search does nothing

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1186]
I.e., if I click in a tag called "encoding", I should be presented with the list of representation information that has the tag "encoding". And, ATM, I'm presented with the list with all items.

**Comment by nunovieira220** [comment]
Done

**Comment by hsilva-keep** [comment]
The solution presented is not very good as it reuses the functionality of representation information association & that has interface differences that make no sense in this context (i.e. show me all representation information that has tag equal to VALUE). Besides, using that strategy show us a page without side bar & therefore the lack of actions/facets.

![img](https://user-images.githubusercontent.com/1315759/38025271-a52a8c76-327f-11e8-8cdf-feee0ace4d8a.png)

**Comment by nunovieira220** [comment]
Done
