### ISSUE TITLE
Links at the bottom of Representation Information pages don't scroll the page to the top, leaving the user with the impression that the link did not work

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1191]
The fix should be similar to #1167 

You may test it with with the following record available on the staging server:

#planning/representation_information_register/representation_information/fdd000125

**Comment by nunovieira220** [comment]
@jmaferreira I can not reproduce the problem. Can you explain me what links make that happen (I tested with multiple cases)?

**Comment by nunovieira220** [comment]
We found some examples that do not scroll totally to the top after clicking them due to description being too large. A scrollToTop is needed on this particular events.

**Comment by jmaferreira** [comment]
Sure.
Make your window width narrow and then click in any of the RI links on the bottom.

![screen shot 2018-03-28 at 19 12 36](https://user-images.githubusercontent.com/3181302/38048022-218428a4-32bc-11e8-84ab-f99e911511c6.png)

**Comment by nunovieira220** [comment]
Done
