### ISSUE TITLE
Date (with or without time) should be presented always in the same format

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1198]
I think the right format should be yyyy-mm-dd hh:mm:ss. 
Also, when it makes sense, use the same labels for column name: "Date and time" vs. "Date" (and in this last case also time is presented).

![captura de ecra de 2018-04-03 12 03 37](https://user-images.githubusercontent.com/1315759/38245708-25e162e8-3737-11e8-9558-2fc80686b8a7.png)
![captura de ecra de 2018-04-03 12 00 28](https://user-images.githubusercontent.com/1315759/38245709-25ff407e-3737-11e8-8e2b-5b60868fdd9b.png)
![captura de ecra de 2018-04-03 11 58 50](https://user-images.githubusercontent.com/1315759/38245710-261e705c-3737-11e8-86e5-ee9bc409abe5.png)

**Comment by nunovieira220** [comment]
Done
