### ISSUE TITLE
When using CAS, with register active=false, a successful auth shows page with error 500

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1199]
How to reproduce:

- RODA with CAS
- Configure to create users inactive
- Authenticate with user that does not exist in RODA

**Comment by chalkos** [comment]
What would be the intended behaviour? (when a new valid user logs in via CAS but RODA refuses to create it internally)

**Comment by chalkos** [comment]
@hsilva-keep 

> Show some error page informing that the user is inactive and to try contacting the administrator to activate the account

**Comment by chalkos** [comment]
the page mimics the 404 and 500 error pages and looks like this: (but the design can be overridden in theme.css)

![image](https://user-images.githubusercontent.com/98429/38630661-7f37a2ac-3daf-11e8-803a-4f514d1feac4.png)

![image](https://user-images.githubusercontent.com/98429/38630685-8b6e4a26-3daf-11e8-8394-299360845414.png)

**Comment by jmaferreira** [comment]
That design is a bit off the default isn’t it?
Can you make it more similar to what already exists?

**Comment by chalkos** [comment]
I based the design on existing error pages, namely error 404 and error 500.
