### ISSUE TITLE
Support ingest by FTP with LDAP authentication

### ISSUE THREAD

**Issue by luis100** [keeps/roda#12]
Ingest by FTP instructions are no longer valid because of changes in PAM. This support now needs to be reviewed and good instructions need to be created.

From Nicholas del Pozo:
> Install instructions for LDAP + libpam-ldap both require a lot of options to be set-up. I understand that somebody with more knowledge in these areas wouldn't find it a problem, but it would good to have some 'default' values to enter recorded in the install documentation.

**Comment by hsilva-keep** [comment]
In new RODA version (2.x.x) a generic ingest area has been created and organized by user/producer. At the moment, we envision that there will be 3 ways the user will be able to manipulate data in his folder (e.g. add a new SIP) to be ingested: 1) via web user interface; 2) via REST API; 3) using any other way to expose the access to the filesystem folder. 
For this last one, we will (most probably) no longer provide concrete instructions on how to access that folder as the possibilities are endless and may be installation specific (related to OS, infrastructure restrictions in what concerns security, software/protocol to be used, etc.).
