### ISSUE TITLE
Welcome page review (Portuguese version)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1200]
The welcome page could use an improvement of its text.
Check the translations provided by Vitor Santos.

**Comment by jmaferreira** [comment]
@hsilva-keep  Do me a favour... send the welcome page (EN) to Vitor Santos to be translated into Portuguese. Thanks.

**Comment by hsilva-keep** [comment]
@jmaferreira you send him the links as follow (I don't have any of his contacts):

- https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/theme/Welcome.html
- https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/theme/Welcome_pt_PT.html

**Comment by jmaferreira** [comment]
He has an institutional email... ! :)

**Comment by luis100** [comment]
Done.
