### ISSUE TITLE
Support for full AIP export for a given producer/fonds

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#124]
R64, R65

**Comment by sleroux-keep** [comment]
Added Browser method to export AIP based on a Filter
public static StreamResponse exportAIP(RodaUser user, Filter filter, String acceptFormat)

I've also update the REST method /aips/[aipID] GET endpoint to download the AIP Zip representation (better than new ApiResponseMessage(ApiResponseMessage.OK, "magic!") ... )

**Comment by luis100** [comment]
This needs (also) to be implemented as a plugin/job. The plugin/job should receive as argument the folder on the filesystem where the AIPs will be exported to.

**Comment by luis100** [comment]
Also, please test the export in large-scale, exporting thousands of AIPs in a single go. Use Job creation using filters to accomplish the selection of AIPs.

**Comment by jmaferreira** [comment]
Whats the status of this issue?

**Comment by sleroux-keep** [comment]
https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/java/org/roda/core/plugins/plugins/base/ExportAIPPlugin.java

**Comment by luis100** [comment]
- [ ] Remove or change default value for PLUGIN_PARAM_EXPORT_FOLDER_PARAMETER parameter
- [ ] change all java.io to nio based code

**Comment by luis100** [comment]
@sleroux-keep please check the above tasks for the solution to be accepted.

**Comment by luis100** [comment]
checked.
