### ISSUE TITLE
Setting permissions for public access

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1249]
Roda should support fine-grain control over what a guest (non-authenticated user) can do. Currently removing a role allows public access, but using an all-or-nothing policy. This issue is about giving RODA administrators better control of what guests can do in RODA.

A way to do this is to implement that users accessing RODA without logging in should have the same permissions as the special user 'guest'.

**Comment by chalkos** [comment]
A possible fix is https://github.com/keeps/roda/commit/551e8607ade3acd7b62e30c738ab4835dd0d91e7, but it still needs some reviewing.

**Comment by luis100** [comment]
Fixed on 0d239231023903bdee3543476aadc5869f8c5ebb
Merged into 2.2.x on 1d50a07fe91f2b08150165943567c4e06b82d857

**Comment by chalkos** [comment]
The guest user roles' were not being retrieved from the server for unauthenticated users. Fixed by including the roles when creating the 'guest' RODA user that is used by unauthenticated users.
