### ISSUE TITLE
Configurable web interface date format

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1251]
The date format on the interface is fixed to the YYYY-MM-DD format.

Other GWT options include regional or local configuration for dates.

But this should be configurable by implementation. Have a configuration in RODA-WUI properties that would allow to configure the date format.

Note that this date format is shown on the AIP lists (date initial and final) and on the AIP browse.

**Comment by chalkos** [comment]
The date format is now configurable using a new enhancement that allows server properties to be shared with client browsers, and new (shared) properties that have been added to roda-wui:

```
ui.date.format.title = predef\:DATE_LONG
ui.date.format.simple = yyyy-MM-dd
ui.dateTime.format.simple = yyyy-MM-dd HH:mm:ss
ui.dateTimeMs.format.simple = yyyy-MM-dd HH:mm:ss.SSS
ui.dateTimeTimezone.format.simple = yyyy-MM-dd HH:mm:ss z
```

For these properties to be shared with the browser they also need to be whitelisted as shared properties:

```
ui.sharedProperties.whitelist.configuration.prefix = ui.date
ui.sharedProperties.whitelist.configuration.prefix = ui.dateTime
ui.sharedProperties.whitelist.configuration.prefix = ui.dateTimeMs
ui.sharedProperties.whitelist.configuration.prefix = ui.dateTimeTimezone
```

**Comment by chalkos** [comment]
Done and reviewed
