### ISSUE TITLE
Implement actions layout as a contextual menu instead of sidebar

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1259]
Actions in sidebar induce a usability error where one is not sure if the button acts on the object open or in a object selected in a list within the open object. Example is in AIP where one may remove a whole collection AIP instead of a single collection record.

Use a contextual menu, based on the same of the BrowseFile, to show the Actions that apply to an object (i.e. AIP). This menu open button is aligned with the object title it applies to and does not follow interface. This way it is obvious to that it applies to.

**Comment by chalkos** [comment]
Done
