### ISSUE TITLE
Add description to Preservation Events page

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1263]
Add a description below the title, like other pages have.

**Comment by chalkos** [comment]
Please handle the creation of this text. I can add it to RODA after if that suits you.

**Comment by luis100** [comment]
> A preservation event aggregates metadata about actions, specifically documenting which objects it affects and which human or software agents intervened. Documentation of actions that modify an object is critical to maintaining digital provenance, a key element of authenticity. Actions that create new relationships or alter existing relationships are important in explaining those relationships. Even actions that alter nothing, such as validity and integrity checks on objects, can be important to record for management purposes. 

This should be an theme-able external HTML file, like other descriptions.

**Comment by chalkos** [comment]
fixed
