### ISSUE TITLE
Revise exceptions thrown by Storage, Model and Index services

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#127]
At the moment, for example, if ModelService makes use of a method in StorageService and an exception is thrown, then that will be a StorageService exception that afterwards will be rewrapped as a ModelService exception. And there is also a code, kind of hidden inside the exception, that explains what happened (e.g. NOT_FOUND, ALREADY_EXISTS, etc.).
That does not make any sense, it is hard to maintain and therefore core exceptions must be used instead (i.e. the ones from roda-common-data).

**Comment by luis100** [comment]
Changed most of exception on commit c92491eae8acd18b2822b9407fd855c333247908, now letting @hsilva-keep to review

**Comment by hsilva-keep** [comment]
The majority of the work was done by @luis100 and I in 82f4d08a16e43d3faf8a4e7bf50866867b45d43e have finished the review.
