### ISSUE TITLE
I don't love the way KEEPS logo appears on the footer

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1271]
Try putting it in its own column to the right with a heading saying "Powered by".

**Comment by chalkos** [comment]
Like this?

1:
![image](https://user-images.githubusercontent.com/98429/43008268-81589772-8c32-11e8-94b1-f3bcc137f6ac.png)

2:
![image](https://user-images.githubusercontent.com/98429/43008315-a0cf5442-8c32-11e8-8148-9a74aa2a10b1.png)

**Comment by chalkos** [comment]
@jmaferreira please review the images above

**Comment by jmaferreira** [comment]
Number 2 (I guess)... @luis100 what do you think?

**Comment by luis100** [comment]
The second, so it doesn't look we would be adding more.

**Comment by chalkos** [comment]
Implemented number 2, per your decision.
