### ISSUE TITLE
Plugins without icon

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1279]
<img width="357" alt="screen shot 2018-07-18 at 11 28 07" src="https://user-images.githubusercontent.com/3181302/42876152-b0eb73ee-8a7d-11e8-9e7a-37a26e843e25.png">

<img width="412" alt="screen shot 2018-07-18 at 11 29 26" src="https://user-images.githubusercontent.com/3181302/42876193-de317c04-8a7d-11e8-8252-a9e17ffe2d62.png">

**Comment by nunovieira220** [comment]
It is already solved
