### ISSUE TITLE
Add support for the database previewer 

### ISSUE THREAD

**Issue by luis100** [keeps/roda#13]
The PhpMyAdmin previewer support was removed in version 1.1.0, the support now needs to be re-evaluated.

**Comment by luis100** [comment]
Add new previewer to be implemented at https://github.com/keeps/db-viewer

**Comment by luis100** [comment]
Blocked by #454

**Comment by luis100** [comment]
Now is blocked more specifically by #670

**Comment by luis100** [comment]
No longer blocked as it now can show disseminations in files.

**Comment by chalkos** [comment]
@luis100 
Is this only missing authorization support in the viewer?

Or is it considered to be blocked until the viewer (when used by RODA) supports external LOBs?

**Comment by hsilva-keep** [comment]
Aside from some details (CAS, etc.), a database viewer is available (see https://github.com/keeps/db-visualization-toolkit) & a plugin for automating DIP generation (which implies uploading information from RODA DIP to the viewer) is also available (see https://github.com/keeps/roda-dbptk-plugin).
