### ISSUE TITLE
List files under a representation using the REST API

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1312]
ATM, it's not possible. And it should for a specific AIP id/Representation id.

Requested by @jmaferreira

**Comment by jmaferreira** [comment]
This is necessary to support the mapping between RODA objects and CMIS objects to implement the CMIS protocol.

Other requirements might arise from this work.

**Comment by hsilva-keep** [comment]
Done.

**Comment by jmaferreira** [comment]
This is already in dockerhub in the tag development. You can download the new container.
The demo site hasn't been updated yet.
