### ISSUE TITLE
BrowseAIP permissions and roles visibility

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1335]
- [ ] Desc. metadata should not be shown if user does not have role
- [ ] RI should not be shown if user does not have role
- [ ] Representation list should not be shown if user does not have role
- [ ] DIP list should not be shown if user does not have role

Bundle verify permissions:
- [ ] Should not add risk incidences count, preservation events count and log entries count if user does not have permission (maybe with Optional)
- [ ] Should not show this information if there is no access to it.

**Comment by nunovieira220** [comment]
Done
