### ISSUE TITLE
Identifying formats action in representation shows remove job message

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1344]
- [x] Message should be different. If the same for all jobs then it should be more generic. Also, it could be a bit more verbose.
- [ ] Select to follow job jumps to AIP (double jump?)

![image](https://user-images.githubusercontent.com/631728/45893423-14cc3600-bdc3-11e8-809d-561491c37ec5.png)

**Comment by chalkos** [comment]
@luis100 can not reproduce the 'Select to follow job jumps to AIP (double jump?)' part

**Comment by chalkos** [comment]
confirmed with @luis100 that this does not happen anymore. It must have been fixed along with some other issue.
