### ISSUE TITLE
The selected items information is not coherent

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1348]
![captura de ecra de 2018-09-24 16 57 31](https://user-images.githubusercontent.com/1315759/45963368-f1032d00-c01a-11e8-910c-e9b13df107f9.png)

How to reproduce:
* Search something using wildcard (e.g. 'mimi*') & hit enter key
* Select all pages
* Remove search text & hit enter key to search

The counter is not coherent.

**Comment by chalkos** [comment]
Fixed.
