### ISSUE TITLE
Clean leftover data after failing to ingest a SIP

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1351]
When ingesting an EARK SIP, the plugin should make sure to remove any leftover data after failing the creation of an AIP.

The fix should target the method `EARKSIPToAIPPluginUtils#earkSIPToAIP`, in which the following can happen:

1. start ingest
2. create the AIP in the filesystem
3. try to index it and fail
4. throw exception up, but leave AIP in the filesystem

**Comment by luis100** [comment]
Superseeded by #342
