### ISSUE TITLE
Replace ImageViewer by UniversalViewer

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1362]
ImageViewer.js is a lab Javascript library that is not updated since 2016.
http://ignitersworld.com/lab/imageViewer.html

This is the only JS library in RODA not replaced by a webjar.

Replace this library by the newer UniversalViewer
http://universalviewer.io

**Comment by jmaferreira** [comment]
Beware of browser compatibility

**Comment by luis100** [comment]
Universal Viewer to be integrated as a separated component, together with a IIIF image server (Cantaloupe).
