### ISSUE TITLE
Ingest: Do not release lock until whole ingest workflow ends

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1378]
Currently, locking is being released after ingest SIP to AIP step. This allows other SIP updates to run their SIP to AIP step before the first workflow ends. And this will make the remaining steps from the first workflow to be run on a AIP state already changed by subsequent updates. 

For example, if a SIP update changes desc. metadata  and the following SIP update does the same, the desc. metadata validation step of the  workflow for the first SIP update will run with the desc. metadata changed by the second SIP update.

**Comment by hsilva-keep** [comment]
Solved since c593b803f424ff6d258044d576252dcd7d018338
