### ISSUE TITLE
Accessibility of GUI (WCAG 2.0 AA)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#138]
R63

**Comment by jmaferreira** [comment]
This will have to be done by @luis100 or @vitorfernandes87  with the support of @sleroux-keep

**Comment by hsilva-keep** [comment]
Done since b030d4cb0739edb95d298a0bc46920e1a9c98b1d by @nunovieira220. I'll review it.

**Comment by hsilva-keep** [comment]
@nunovieira220 There are still some non-compliances:
- Statistics page: ```Foram encontrados 23 elementos <iframe> sem título``` [(ChartJS issue)](https://github.com/chartjs/Chart.js/issues/3796)
- AIP page: ```Foi identificado 1 controlo de formulário sem etiquetas associadas e sem o atributo title```

**Comment by nunovieira220** [comment]
Those two issue are now solved on 354863d4d518fa3a8e74ea2e7cc4c06dcd0bccae

**Comment by hsilva-keep** [comment]
Indeed solved.
