### ISSUE TITLE
Inconsistent state in browse aip

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1385]
To reproduce:

1. create AIP. the "add representation" button should be visible, but not the list (because it is empty)
2. create representation in the AIP
3. go back to AIP. the representations list should be visible with 1 item
4. select the representation and remove it

Expected: the page should display the same as it did after step 1 above.

Actual result: an empty representation list is shown instead of the "add representation" button

**Comment by chalkos** [comment]
@luis100 can you choose a milestone for this?

**Comment by luis100** [comment]
done

**Comment by chalkos** [comment]
done
