### ISSUE TITLE
Revise the usage of storage metadata

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#139]
At the moment, and using an AIP in our storage as an example, there is important information that is being stored in a .properties.yaml file which might be considered obscure and non standard. List of some of the properties being saved in *AIP_ID/.properties/.properties.yaml*:
* active
* parentId
* date.created
* date.modified

Also, this is applicable to other entities of our model (Representation, Representation files, etc.) because this is possible in each folder/file inside an AIP.

**Comment by luis100** [comment]
Removed the support for storage metadata, all information should be kept in the AIP metadata `aip.json`.
