### ISSUE TITLE
In search, sometimes the dropdown items break into 2 lines

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1392]
1. Select a shorter item
2. Open the dropdown
3. the longest item in the dropdown is now breaking into multiple lines (happens with Portuguese language)

![image](https://user-images.githubusercontent.com/98429/48346875-63d07200-e674-11e8-8742-ea26a75d6bb3.png)

**Comment by luis100** [comment]
Also the arrow is displaced in IE
