### ISSUE TITLE
Hiding too much information on preservation actions list

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#1398]
This is how it looks on a wide screen:

![image](https://user-images.githubusercontent.com/98429/48349190-713d2a80-e67b-11e8-8efc-4245309954c0.png)

and this is how it looks on a small screen:

![image](https://user-images.githubusercontent.com/98429/48349230-8f0a8f80-e67b-11e8-95ee-139211e21a32.png)

Columns Name and Creator are important (specially the name) and they are hidden when the table is rendered on smaller screens.

**Comment by luis100** [comment]
Define min-width for the column

**Comment by chalkos** [comment]
This fix works for now as the essencial info is now shown, but deeper changes (sidebar, facets) need to be made for all pages/tables to look good on screen widths under 1000px.
