### ISSUE TITLE
Missing/wrong i18n pt_PT translations

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1402]
- [x] When viewing an AIP, the hover for viewing details is not translated
- [x] When viewing an AIP and viewing the details, type is not translated
- [x] Advanced search input fields title is not translated
- [x] When viewing a specific Representation Information & adding new relation, when we choose the type other the title is not translated (Relation com outro tipo de recurso)
- [x] When editing a specific Representation Information, the title of the tags input is not translated
- [x] AIP page: "0 incidências de riscos, 1 eventos de preservação and 42 entradas de log"
- [x] When viewing an event, it says "Objetos de partida" and "Objetos de chegada" which sounds horrible; instead, change it to "Objetos fonte" and "Objetos resultado"

I'll update this issue description if more translations are missing...

**Comment by chalkos** [comment]
done. Reopen if you find more i18n problems

**Comment by chalkos** [comment]
done. Reopen if you find more i18n problems
