### ISSUE TITLE
Eliminate some right side bars

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1407]
- [x] Ingest / Process (start new process must be put in 3 dots menu)
- [x] Ingest / Assessment (just remove the side bar as the 3 dots menu already exists with respective actions)
- [x] Administration / Preservation actions (start new process must be put in 3 dots menu)
- [x] Planning / Risk register (just remove the side bar as the 3 dots menu already exists with respective actions)

**Comment by chalkos** [comment]
done.
