### ISSUE TITLE
Links between representation information and files is not working

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1420]
<img width="1601" alt="screenshot 2018-12-03 at 08 24 14" src="https://user-images.githubusercontent.com/3181302/49361866-f9d84500-f6d4-11e8-868c-954af781e972.png">

This leads to the following page:

<img width="1239" alt="screenshot 2018-12-03 at 08 25 54" src="https://user-images.githubusercontent.com/3181302/49361937-25f3c600-f6d5-11e8-95e9-dd009edf7999.png">

Check this record  on the demo:
https://demo.roda-community.org/#planning/representation_information_register/representation_information/c5269b2c-8d8d-4638-a8a1-d3ed8d697366

**Comment by chalkos** [comment]
done
