### ISSUE TITLE
Broken links on the contents of Representation information (PNG 1.4)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1421]
- [ ] Check the cause of this problem. Is this on the source data or is it a conversion problem?
- [ ] We might have to check the validity of all links in the corpora.

<img width="1441" alt="screenshot 2018-12-03 at 08 27 45" src="https://user-images.githubusercontent.com/3181302/49362024-7539f680-f6d5-11e8-8d85-476e6087bafe.png">

**Comment by hsilva-keep** [comment]
@jmaferreira I've checked the links in the source XMLs, i.e. XMLs used to create Representation Information in RODA own XML format, and the problem already is there (partial URL to KEEPS internal repo: roda-dev/representation-information/blob/master/fddXML/fdd000122.xml):
```xml
<fdd:urls>
         <fdd:url>
            <fdd:urlReference>
               <link>http://www.adobe.com/devnet/pdf/pdf_reference_archive.html</link>
               <tag>PDF Reference Archives</tag>
               <comment>Documentation for versions of PDF prior to the current version.  Includes access to errata and supplements.</comment>
            </fdd:urlReference>
         </fdd:url>
         <fdd:url>
            <fdd:urlReference>
               <link>http://wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf</link>
               <tag>PDF Reference, Fourth Edition, Version 1.4.</tag>
               <comment>Adobe Systems Incorporated.</comment>
            </fdd:urlReference>
         </fdd:url>
         <fdd:url>
            <fdd:urlReference>
               <link>http://wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference13.pdf</link>
               <tag>PDF Reference, Fourth Edition, Version 1.3.</tag>
               <comment>Adobe Systems Incorporated.</comment>
            </fdd:urlReference>
         </fdd:url>
      </fdd:urls>
```

**Comment by jmaferreira** [comment]
This you fix this case manually in our corpora?
Did you check to see if there are more cases of this?

**Comment by hsilva-keep** [comment]
@jmaferreira I've just created an issue to review the representation information (see #1423). But, in the end of the day, broken links may not be the only problem.
