### ISSUE TITLE
Bug while searching for filename

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1432]
<img width="1680" alt="screenshot 2019-01-15 at 00 15 10" src="https://user-images.githubusercontent.com/3181302/51149609-bd167680-185a-11e9-8d14-692950ecbbd3.png">

**Comment by luis100** [comment]
Bug confirmed on client, setting for next patch release.

**Comment by nunovieira220** [comment]
Done on 5b5cd2534f53060b4ea24815b72d9d0280155c32
