### ISSUE TITLE
Configuring facets for AIPs is not working

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#1442]
When trying to configure more facets, for AIPs and due to custom metadata fields, facets don't show up. Moreover, AIPs advanced search stops showing the search fields that were showing until facets configuration was introduced.
This configuration is done in external roda-wui.properties. 
If the same configurations is added directly to roda-wui.properties, inside webapp, it works as expected.

Even more, if no translation is set, the facet values are added to another facet.

**Comment by luis100** [comment]
When overriding a list of properties, or a list of trees of properties, the whole list must be re-defined in the external document. This is necessary to support removal and re-ordering on the overridden file.

Was this the case on your test? An example is necessary to confirm to the problem.

The second part, of no translation, seems an unrelated bug and should be another issue.

**Comment by hsilva-keep** [comment]
An example is simple to provide. Try to add a new facet (about AIP type attribute) to Search AIPs list using external roda-wui.properties like:
```
ui.lists.Search_AIPs.facets.parameters = type
ui.lists.Search_AIPs.facets.parameters.type.type = SimpleFacetParameter
```

**Comment by luis100** [comment]
You need to override all properties that start with ui.lists (around 448 lines).

This could be improved: #1445
