### ISSUE TITLE
Configuring a ui.list should not need to override all lists

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1445]
The property ui.lists is a list of complex properties:
https://github.com/keeps/roda/blob/3e1cf2d1196a72ed960086a0e96f651bf38f88ef/roda-ui/roda-wui/src/main/resources/config/roda-wui.properties#L709-L720

This seems to be mainly used to ascertain if a list has facets:
https://github.com/keeps/roda/blob/3e1cf2d1196a72ed960086a0e96f651bf38f88ef/roda-ui/roda-wui/src/main/java/org/roda/wui/common/client/tools/ConfigurationManager.java#L209-L212

But the collateral effect is that to redefine any property of a list, including a facet, one need to override the complete list of properties for all ui.lists. (448 lines!!!)

But, to ascertain if a list does not have facets, one just needs to check if the list of facet parameters exists and is not empty.

I recommend removing the list of ui.lists so it becomes easier to override a list property.

**Comment by chalkos** [comment]
Done. I'll close this once the code passes validation.

**Comment by chalkos** [comment]
@luis100 confirmed working.
