### ISSUE TITLE
Tests with admission of A / V content to the RODA repository and system subsidies for archival description of access derivative (DIP)

### ISSUE THREAD

**Issue by JG260914** [keeps/roda#1453]
Dear,

Would anyone be aware of the institutions that are testing or are already working extensively with the admission of audiovisual content in the RODA?
Does the RODA repository currently allow the archival description capability for the access derivative (DIP)?
Thanks for the information!

**Comment by luis100** [comment]
Hello. Our current customers do not work with large amounts of audiovisual content, but there might be users that install RODA on their own and have this profile.

RODA supports audiovisual content, there are plugins for format conversion of audiovisual content (see [Format normalization policy](https://github.com/keeps/roda/blob/master/documentation/Format_Normalization_Policy.md)) and embedded viewers for audio and video (in HTML5 supported formats, so format conversion might be needed).

The result of the format conversion can go to a new representation or to a DIP file, connected to the original file.

If you need more information about our services please contact us at sales@keep.pt
