### ISSUE TITLE
Update Fedora Commons to 4.4

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#148]

**Comment by hsilva-keep** [comment]
This task is kind of done since 983d80e555c0e70a87027d6f8ca42f58e148d30d but, with the changes performed, RODA was left with 1 Fedora related unit test failing. The problem was reported in Fedora Commons bug tracking system and can be found in https://jira.duraspace.org/browse/FCREPO-1873

**Comment by luis100** [comment]
Ignoring test for now, added issue #153 to review when Fedora bug is fixed.
