### ISSUE TITLE
RODA is indicated to digital library?

### ISSUE THREAD

**Issue by Wellblack76** [keeps/roda#1485]
Hi
I'm finishing my master in digital information system in Salamanca University - Spain. In my final work I'll evaluate Archivematica, DSpace and RODA to identify what is the more adequated for Digital Library (open access) and administrative documents (public access, on demand)

RODA is indicated to built digital library? 

Thank you in advanced

Wellington

**Comment by jmaferreira** [comment]
Dear Wellington,

Sorry for the late response.
RODA is perfectly capable of implementing a digital library, however, please bear in mind that RODA is a OAIS preservation system and not really a publication platform. This means that, the most common use case for RODA is to have an archive/library only accessible to specific users within an organisation.

Nonetheless, if you make digital objects public, they will be accessible on the UI without authentication. 

Hope this helps.

**Comment by Wellblack76** [comment]
Thank you so much for you answer. It was really helpfull. 

Best regards,
