### ISSUE TITLE
The different practice of naming the representation?

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1486]
Hi,
during the creation of the new dissemination, which will result in the new representation, its folder is given the uuid like a name. Is not such a practice kind of confusing? I am aware of the fact, that EARK specification does not specify the name of such folders but RODA-IN itself is working on the rep1-repN basis, so I am curious why RODA itself does not work in a similar way. Or even is not willing to say to their users, that "this" representation is derived from ingested one by, for example, naming it "rep1.2", how is EARK specification suggesting.

**Comment by hsilva-keep** [comment]
Dear @elbre 

First of all let me clarify some things about RODA and RODA-in:
* Archival Information Package (AIP) and Dissemination Informatin Package (DIP) are separated entitites in RODA
* All entities in RODA have unique identifiers, that are automatically assigned upon creation. This behavior is applied by RODA business logic to avoid entities' colisions, but some specific exceptions do exist, being one of them the representation id
* E-ARK specifications about information packages specify the format of the packages, both logical and physical, but say nothing about how the ingest process takes place. This way RODA, when ingesting SIPs created by RODA-in of the type E-ARK, makes decisions about how to transform the information contained in the package into RODA AIP (which is vary simillar to E-ARK AIP)
* As you mentioned E-ARK specifications say nothing about how representations should be named. In RODA-in, as it is mainly a demonstrational tool for creating SIPs, a decision was made to name representations 'repN'
* If ingesting E-ARK SIPs created by RODA-in in RODA, each representation will be named after representation name in the SIP (I've just confirmed using RODA version 3.x and RODA-in version 2.x)
* When creating representations, the logic creating them is responsible for setting their id. From RODA perspective, they are simple strings with no special meaning.

Having said this, and to start answering your questions, creating a new Dissemination doesn't mean necessarily creating a new Representation. 
On the other hand, while creating one Representation from another for dissemination purposes, you might/should programmatically create a PREMIS event that relates this new representation to the original one (e.g. a migration event). And they are this way "connected" via the PREMIS event and their URNs.

As I said before, RODA does not interpret representation id's neither has a clue about the reason why a new representation was created, that is why naming representations and creating PREMIS events must be done explicitly.

Hope this helps clarifying your doubts.
