### ISSUE TITLE
Problem with ingesting 'preservation' and 'other' metadata type

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1490]
Good day!
During testing Ingest I come across problem with ingesting other than descriptive metadata. By a layout of the METS, it seems that system should be prepared for such data and in cases, when I fake some other problem (like for example write the wrong checksum), I can read in the "Information package processing report" that "Preservation metadata file was found and file checksum matches METS checksum". So by this report, it seems that metadata should be acceptable. BUT if I repair the faked problem and try ingesting the package, RODA is just reporting unsuccessful ingest without providing any processing report. 

Would be somebody so nice and let me know if this is, by any chances, problem of our package or regular RODA bug?

**Comment by luis100** [comment]
An unexpected error might have happened, but we would need more information to be able to diagnose. Can you send the roda-core.log and screenshot of the ingest report?

**Comment by elbre** [comment]
![Snímek obrazovky (46)](https://user-images.githubusercontent.com/48675042/64697184-856ed580-d4a0-11e9-923b-cd16414d196d.png)

I am sorry, I have at this moment issue gets log. Sending at least screenshot of the report. As I said, this report will pop up if I write incorrect checksum. If I will correct this error, ingest will fail but will not give me any report.

**Comment by hsilva-keep** [comment]
From the provided screenshot, the error happens in the file metadata/preservation/premis_ipc.xml because in the METS.xml file there is one sha-256 checksum but the file has another different value.

@elbre can um please check your package so we can close this issue as no bug seems to exist?

**Comment by hsilva-keep** [comment]
@elbre also, this report is only presented in the first step of the ingest workflow if an error processing the SIP occurs. So if you are saying that, if the checksum is correct, the job fails then you need to provide us roda-core.log and/or screenshot of the different steps of the ingest so we can try to diagnose in which step the error is happening. 
Otherwise we will close the issue due to missing information/evidences of the possible problem.

**Comment by elbre** [comment]
Ok, I understand. 
I just thought that the answer will be that RODA doesn't expect the preservation metadata at the phase of SIP ingest so, therefore, is not able to process them. 
I will close the issue and eventually reopen it if I will be successful with retreating the data.
I apologize for the inconvenience!
