### ISSUE TITLE
question: E-ARK ingest update

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1499]
Hi,
I am apologizing to bother you again.
Can I just ask if there is some time frame in which you are planning to make the update of the E-ARK ingest?

I know that the new version is still in polishing process but I am just genuinely curious when you are planning to project current changes into your program (if you are actually planning to do so in the first place).
It seems to be unavoidable since the usage of structMap is quite different. 

Thanks for the answer!
EKB

**Comment by hsilva-keep** [comment]
@elbre the simple answer is soon. But, in what concerns RODA, we will support both versions of E-ARK SIP. But, in essence, only internal changes exist (things like you've mention, i.e., structMap usage and others).
