### ISSUE TITLE
Create i18n compliant error pages

### ISSUE THREAD

**Issue by luis100** [keeps/roda#15]
Right now, error pages are static pages on the webapp folder and used directly by the web descriptor (web.xml). 
Change the web descriptor to point out to RODA webapp menu options that open i18n error page as in Home.html

Example: Point web.xml 404 error page to /#error_404, add menu option "ERROR_404", load error page when menu option selected.

**Comment by jmaferreira** [comment]
Make something beautiful

**Comment by nunovieira220** [comment]
The 404 error page is now created. Its design shall be improved.

**Comment by jmaferreira** [comment]
I can give a hand… send me a screenshot of the current design.

**Comment by nunovieira220** [comment]
![screenshot from 2016-09-23 12 34 11](https://cloud.githubusercontent.com/assets/8982932/18784488/4ed620e4-818a-11e6-9cea-3f5cfa386d3c.png)

**Comment by jmaferreira** [comment]
Its perfect. Keep it as it is!
