### ISSUE TITLE
Support "None selected" for any "controlled" advanced search field

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1501]
https://github.com/keeps/roda/blob/201216c298db8081411cb0a89e5999764886d1c7/roda-ui/roda-wui/src/main/java/org/roda/wui/client/common/search/SearchPanel.java#L416

Currently only supporting for level field, should support for any field of the "controlled" type.

**Comment by hmiguim** [comment]
Close at https://github.com/keeps/roda/issues/1995
