### ISSUE TITLE
New digital signature plugins

### ISSUE THREAD

**Issue by fdelapena** [keeps/roda#1505]
Hello,

Here's a question concerning digital signature support. Since 2.2.0 some plug-ins were removed likely due to licensing issues, I'm interested on contributing an eSignature DSS based plug-in (LGPL) for both ingest validation and DIP signing as before. After reading some answered questions, it seems you are planning to bring back some of them and mentioned some kind of plug-in market.

My plan is to contribute to your project with the PR, sign the CLA, and get this plug-in available in your deployments hopefully around the second quarter 2020, so it would be nice to know in case you're working already on it to prevent effort duplication. Additionally, would you prefer to get this developed in a separated repository or keep it in the same?

Thanks!

**Comment by luis100** [comment]
Hi, plugins are now to be managed on separated repositories, following the template available at https://github.com/keeps/roda-plugin-template

You can create your own plugin using your own repository, and release a plugin asset (zip) as created by the assembly already available on the template.

Something like a plugin market is on our plans, but not for the immediate future. Anyway, installing plugins in simple, just unzip the plugin in the $RODA_HOME/config/plugins folder.
Also, the Dockerfile in the template will allow you to have a RODA with your plugin installed to test and possibly as a deploy example.

We currently have two digital signature plugins for our enterprise users:
-   Digital signature verification and extraction plugin: to verify and/or extract digital signatures embedded on PDF or Microsoft Word files
- Multicert LTV plugin: LTV dates extraction and integration with [Multicert mLTV](https://www.multicert.com/en/case-studies-folder/long-term-validation-copy/) web service to use Long Term Validation protocol to extend the validation of digitally signed files (PDFs and Words). 

Your plugin seems to be a different thing, so I guess you wont be duplicating effort.
