### ISSUE TITLE
I have a question about RODAin

### ISSUE THREAD

**Issue by paulpott** [keeps/roda#1510]
Are there any open source java solutions that works with RODAin? Like Open JDK?

**Comment by luis100** [comment]
Yes, openjdk works if you also install openjfx

```bash
sudo apt-get install openjfx
```

If you cannot install it, e.g. in RHEL, than you can use [Java Zulu JRE FX](https://www.azul.com/downloads/zulu-community/?&version=java-8-lts&architecture=x86-64-bit&package=jre-fx&show-old-builds=true)
