### ISSUE TITLE
API create/update descriptive metadata is failing

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1516]
In attempt to try create (POST) or update (PUT) descriptive metadata is process failing and receiving this response instead.

{
  "type": "error",
  "message": "AuthorizationDeniedException: Unable to determine which roles the user needs because the config. key 'core.roles.org.roda.wui.api.controllers.Browser.createAIPDescriptiveMetadataFile' is not defined"
}

{
  "type": "error",
  "message": "AuthorizationDeniedException: Unable to determine which roles the user needs because the config. key 'core.roles.org.roda.wui.api.controllers.Browser.updateAIPDescriptiveMetadataFile' is not defined"
}

This error is showing even on https://demo.roda-community.org/api-docs/.

**Comment by luis100** [comment]
Missing 'core.roles.org.roda.wui.api.controllers.Browser.updateAIPDescriptiveMetadataFile' in file 
https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/resources/config/roda-roles.properties

Workaround, copy the above file from source to the RODA config and add the missing property.
```javaproperties
core.roles.org.roda.wui.api.controllers.Browser.updateAIPDescriptiveMetadataFile = aip.update
```

**Comment by hmiguim** [comment]
Close at afc4fed
