### ISSUE TITLE
Roda and reverse proxy

### ISSUE THREAD

**Issue by lodnert** [keeps/roda#1527]
Has someone configured roda-wui behind a nginx or apache httpd and can provide some configuration examples?

**Comment by luis100** [comment]
This is a common implementation, just do a usual reverse proxy configuration to roda-wui on port 8080.

**Comment by lodnert** [comment]
I have done that, but the api-docs is not working. my proxy points at domain.com/roda-wui.3.2.0 -> localhost:8080/roda-wui-3.2.0 and all that works fine. But the api-docs is pointing at the root directory domain.com/api instead of domain.com/roda-wui.3.2.0/api .

**Comment by luis100** [comment]
Please deploy roda-wui as ROOT so the context path is /

**Comment by lodnert** [comment]
OK will try to do that. As a follow up question, Is this requirement documented somewhere?

**Comment by luis100** [comment]
It's not an actual requirement, is a limitation in some parts, specifically in api-docs. Documentation is lacking, as this is a bug.

**Comment by lodnert** [comment]
Ok, fair enough.

Works fine when deployed as ROOT
