### ISSUE TITLE
Enable test when Fedora 4.4 bug is solved

### ISSUE THREAD

**Issue by luis100** [keeps/roda#153]
Re-enable Fedora Storage move binary test when the following Fedora bug is solved: https://jira.duraspace.org/browse/FCREPO-1873

**Comment by hsilva-keep** [comment]
Actually this task also depends on updating Fedora client as well (as the bug is fixed in version 4.5).

**Comment by luis100** [comment]
This became less of a priority, will be dealt with after beta. In the meanwhile a new version of fcrepo can be released and we might change our objective to sync with the last stable version.

**Comment by jmaferreira** [comment]
The issue has been resolved on Fedora 4.5.1 on 6/Feb/16 5:41 PM.

**Comment by hsilva-keep** [comment]
Fedora 4 support has been removed, due to lack of reliability, in RODA version 3. Closing this issue as no further actions are required.
