### ISSUE TITLE
Roda API Rest

### ISSUE THREAD

**Issue by fernandesjm** [keeps/roda#1533]
Boa tarde,
Eu estou com dificuldades em entender o workflow do serviço rest do roda. Eu preciso de criar AIPs, mandar para lá  um ficheiro e posteriormente criar DIPs. Tentei entender como o fazer através da UI, mas está complicado replicar em rest. Há alguma coisa ou alguém que me consiga fazer entender melhor?
Obrigado desde já

**Comment by luis100** [comment]
A descrição do procedimento que quer seguir é insuficiente para sugerir o workflow mais adequado. No geral, há dois workflows possiveis: 1) criar um SIP, adiciona-lo às transferências, iniciar um job de ingestão e posteriormente criar um DIP, ou 2) criar um AIP, dentro desse criar uma Representação, e dentro dessa adicionar um ficheiro, e posteriormente criar um DIP.

**Comment by fernandesjm** [comment]
Eu estou a tentar fazer o que descreveu no ponto 2. Fazendo um POST para /api/v1/aips consigo criar um AIP, ficando com o aip_id. Em seguida, fazendo um POST para /api/v1/representation_information consigo criar uma representação, ficando com o representation_id. 
O passo seguinte seria fazer um POST para /api/v1/representations/{aip_id}/{representation_id}/preservation_metadata com os ids anteriores, certo? Para criar uma representação do ficheiro a preservar. É que eu não estou a conseguir fazer este ultimo passo. Nao sei se estou a fazer algo errado ou a saltar algum passo

**Comment by fernandesjm** [comment]
Olá Luis,
Eu estou a tentar fazer o que descreveu no ponto 2. Fazendo um POST para /api/v1/aips consigo criar um AIP, ficando com o aip_id. Em seguida, fazendo um POST para /api/v1/representation_information consigo criar uma representação, ficando com o representation_id.
O passo seguinte seria fazer um POST para /api/v1/representations/{aip_id}/{representation_id}/preservation_metadata com os ids anteriores, certo? Para criar uma representação do ficheiro a preservar. É que eu não estou a conseguir fazer este ultimo passo. Nao sei se estou a fazer algo errado ou a saltar algum passo.
Obrigado

**Comment by luis100** [comment]
Não são esses os endpoints corretos

1.  POST /v1/aips Create AIP 
2. POST /v1/representations Create representation
3. POST /v1/files Create file

**Comment by fernandesjm** [comment]
Esse ponto 2, não me é permitido... como é que eu tenho acesso ao representation_id se estou a cria-lo?

**Comment by luis100** [comment]
Não deve estar a cumprir os requisitos mínimos do método. Por favor experimente via api-docs/

**Comment by fernandesjm** [comment]
<img width="1435" alt="Captura de ecrã 2020-05-27, às 17 10 16" src="https://user-images.githubusercontent.com/43337277/83045442-7aaf9d00-a03d-11ea-8def-5d029ac987a2.png">
<img width="1440" alt="Captura de ecrã 2020-05-27, às 17 10 26" src="https://user-images.githubusercontent.com/43337277/83045451-7daa8d80-a03d-11ea-8d6b-d130bf953899.png">


Olá Luis,
não sei o que estarei a fazer de errado, quer na api-docs quer no Postman dá me o erro 405. Alguma sugestão?

**Comment by luis100** [comment]
Não definiste o acceptFormat, podes tentar com application/json?
