### ISSUE TITLE
RODA REST API

### ISSUE THREAD

**Issue by fernandesjm** [keeps/roda#1534]
Boa tarde,
eu consigo criar um AIP através dos seguintes passos: 
1) POST para /v1/transfers para transferir o file,
2) POST para /v1/jobs para fazer um job de ingestão .

Neste ponto 2 só tenho acesso ao jobId.
A minha questão é se há alguma maneira de obter o aipId e o representationId do AIP que é gerado no passo 2. Para posteriormente serem usados para criar um DIP.

Obrigado

**Comment by luis100** [comment]
The GET /v1/reports/last will get you the last job report for a specific ingested transfer.
On the report you will get the AIP id as the outcomeObjectId.

![Captura de ecrã 2020-06-05, às 09 35 19](https://user-images.githubusercontent.com/631728/83855383-e2d24300-a70f-11ea-9a81-f6aaff1ea457.png)

**Comment by fernandesjm** [comment]
Obrigado Luis, deu certo. 
Já consigo fazer o meu primeiro objetivo, mandar para o Roda ficheiros criando AIPs. Posto isto, para os recuperar preciso de criar um DIP, certo? Estou a ter problemas em cria-lo e na formação  do seu body... estou a ter este erro.
Eu estou a usar a imagem no docker, tenho que definir esse createDIP?
 "type": "error",
  "message": "AuthorizationDeniedException: Unable to determine which roles the user needs because the config. key 'core.roles.org.roda.wui.api.controllers.Dips.createDIP' is not defined", alguma sugestão?

Obrigado

**Comment by luis100** [comment]
Para recuperar os ficheiros originais não é necessário um DIP, pode descarregar os ficheiros que quer, ou a representação, ou o AIP como um ZIP. O DIP é usado quando um formato diferente é necessário para acesso, por exemplo quando se arquiva uma imagem TIFF e se quer que os utilizadores acedam à imagem em JPEG.


Para descarregar um ficheiro, usar `GET /v1/files/{file_uuid}` com acceptFormat `bin`

**Comment by fernandesjm** [comment]
Obrigado pela explicação Luis. Outra questão, esse file_uuid trata-se de que id?

Já tentei com varios id relacionados com o ficheiro mas diz me sempre que n\ao encontra o ficheiro. é deste id que se trata? (nome)

<img width="1372" alt="Captura de ecrã 2020-06-05, às 15 38 17" src="https://user-images.githubusercontent.com/43337277/83889386-fe0a7600-a742-11ea-99d4-4d09e92fb90d.png">

**Comment by fernandesjm** [comment]
Obrigado Luis
