### ISSUE TITLE
Ingest Reports are stored with wrong final state

### ISSUE THREAD

**Issue by TiagoFraga** [keeps/roda#1544]
During the implementation of validation scripts to validate RODA ingest script, it wad detected that the final state doesn't achieve 'COMPLETE' state.
Also, the ingest report doesn't have the final date attribute.

When the ingest report is evaluated, it gives the information that the job has started but not reached a final state.

**Comment by hmiguim** [comment]
Fixed at b2a37ab277ece3d672fe9925ca0aaa7a78a918e2

**Comment by hmiguim** [comment]
Close
