### ISSUE TITLE
Is there a way how to transfer the AIP packages with preserving metadata into another version/second RODA system?

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1545]
Good to you all!
I would like to ask if there is some way how to transfer the current content (APIs) of the RODA into another one in case of planning to upgrade the system or duplicate the system for testing purposes. I registered "Rebuild AIP index" process in RODA but it is described as the solution for the error more than normal practice. Is there any way to achieve this? Because if I would reingest it I would lose the UUIDs under which are APIs hold in the original system. Or is this whole idea just safety risk?

**Comment by jmaferreira** [comment]
If you copy the AIPs folder from one RODA instance to another RODA instance, all you have to do is run the Reindex AIP process.
Of course, for this to work property the general RODA configurations, but especially the metadata configurations should be the same on both instances.

Hope this helps.
