### ISSUE TITLE
Representation viewer file list does not correctly break file name text

### ISSUE THREAD

**Issue by luis100** [keeps/roda#156]
When looking into a representation with a long file name that cannot be easily break-lined, file name gets oddly shopped off the screen. See screenshot:

![captura de ecra de 2016-01-11 11-05-24](https://cloud.githubusercontent.com/assets/631728/12231978/520c7b06-b853-11e5-8db6-e24e847fce11.png)

**Comment by vitorfernandes87** [comment]
http://www.w3schools.com/cssref/css3_pr_word-break.asp

**Comment by vitorfernandes87** [comment]
Closed on commit 782fffaceee4181f3496e05601944ec998a0a60a
