### ISSUE TITLE
Enhance the solr analysers to support stemming (snowball?), stop words and field boosts

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#164]
Ask sebastien for the best options to use.

**Comment by jmaferreira** [comment]
_txt
_t
_all

**Comment by hsilva-keep** [comment]
AIP solr index: uncomment in text_general the usage of stopwords in query analyzer.

**Comment by hsilva-keep** [comment]
Done in 28325a74b95b8153eb4bf3f7ac16a292a34a8ed6. Configured, for AIP, stemming using SnowballPorterFilter and stopwords, both for Portuguese language. Other indexes, that might need these as well, just copy/paste.

**Comment by luis100** [comment]
Default language (in source code) should be English.

**Comment by hsilva-keep** [comment]
Done in 42675b132adb062fb57b778b5ecd5e1cde997b8c. Portuguese configurations were commented out.
