### ISSUE TITLE
Recommendation of the heritage portal on top of RODA? 

### ISSUE THREAD

**Issue by tkarlovic** [keeps/roda#1649]
Hello,

I am working on a project on which we intend to implement RODA as an OAIS repository. We would like to integrate the heritage internet portal on top of the RODA repository. Does anyone have any recommendations which open source portal to choose? For instance, does anyone have experience integrating the OMEKA portal with the RODA repository? OMEKA has Fedora connector so maybe it could be connected with RODA as well?

Kind regards
Tomislav

**Comment by luis100** [comment]
We have no off-the-shelf solution for that, and most probably this would need to be done as a new OMEKA module. The module could use RODA REST API to feed information to OMEKA.
So, this could be a custom development that we could undertake, for prices please contact sales@keep.pt.

**Comment by luis100** [comment]
Note that after version 2, RODA no longer supports Fedora as a backend storage system. RODA uses the filesystem directly and keeps data using the E-ARK AIP format standard (https://earkaip.dilcis.eu/). This data is then indexed into a Apache Solr for fast searches.
