### ISSUE TITLE
The design of the advanced search should be revised

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#165]
Information must be configured in roda-wui.properties

- Support more field types (only text for the moment)
-- Date
-- Date interval
-- Numeric
-- Numeric interval
-- Storage size interval (with units)
-- Enumeration (done using facets)

- Enhance the UI
-- Add combobox to select which type of search will be done: AIP/Item or Files (the results table will have different information based on the option selected)

- Show most common fields fixed on the UI
-- Add new attribute 'fixed' (i.e. if it appears right way when you open the search panel)

**Comment by jmaferreira** [comment]
Ask Faria where the cross walks are.

**Comment by hsilva-keep** [comment]
Related to #192.

**Comment by vitorfernandes87** [comment]
Almost finished.
Improvements needed:

- Return correct filters for every type
- Custom facets for the different searches
- Enumeration support
