### ISSUE TITLE
Change the interface "File preview not support" to a different icon and message

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#166]
The message should be:

"File preview not supported
Download the file"

**Comment by vitorfernandes87** [comment]
Closed on f6472ca52fc2b6b3d910f4f7e8f1248c921c2063

**Comment by jmaferreira** [comment]
The icon is missing. Please add the icon that was there before.

**Comment by vitorfernandes87** [comment]
Like this?

![notsupported](https://cloud.githubusercontent.com/assets/9133305/12617223/9b0c1270-c506-11e5-815b-4bf2fc506c0b.png)

**Comment by jmaferreira** [comment]
Perfect.

Cumprimentos,
Miguel Ferreira

- -
Diretor executivo
KEEP SOLUTIONS, LDA.
Rua Rosalvo de Almeida, nº 5
4710-429 Braga, Portugal
W www.keep.pt E info@keep.pt 
T +351 253066735 F +351 253067248
