### ISSUE TITLE
Development of integrations

### ISSUE THREAD

**Issue by SeismoReimaliMalm** [keeps/roda#1673]
It seems that I need to develop an integration with RODA. The system will consist of a simple web-application that collects metadata and image files and then transfers them to RODA. The data may be transferred later to long time storage.

So the guestion is is there any code samples how to use the REST API and how to create the sips? Can I use code from RODA in to generate sips without UI? How to do that would be rather nice to know.

Seismo Malm

**Comment by luis100** [comment]
To create EARK SIPs please use the [commons-ip](https://github.com/keeps/commons-ip) library, the project README contains code samples.

**Comment by SeismoReimaliMalm** [comment]
Many thankses,
