### ISSUE TITLE
When executing the common-ip sample I get 'Error marshalling METS' exeption

### ISSUE THREAD

**Issue by SeismoReimaliMalm** [keeps/roda#1688]
Zip-file is created but it won't open. The exception occurs in sip.build(TempFolder); The source code is here, I copied the data files from common-ip:
package com.digitalia.memoriaali;

import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
//import java.xml.bind;

import org.roda_project.commons_ip.utils.IPException;
import org.roda_project.commons_ip.utils.METSEnums.CreatorType;
import org.roda_project.commons_ip2.model.IPAgent;
import org.roda_project.commons_ip2.model.IPAgentNoteTypeEnum;
import org.roda_project.commons_ip2.model.IPContentInformationType;
import org.roda_project.commons_ip2.model.IPContentType;
import org.roda_project.commons_ip2.model.IPDescriptiveMetadata;
import org.roda_project.commons_ip2.model.IPFile;
import org.roda_project.commons_ip2.model.IPMetadata;
import org.roda_project.commons_ip2.model.IPRepresentation;
import org.roda_project.commons_ip2.model.MetadataType;
import org.roda_project.commons_ip2.model.RepresentationStatus;
import org.roda_project.commons_ip2.model.SIP;
import org.roda_project.commons_ip2.model.MetadataType.MetadataTypeEnum;
import org.roda_project.commons_ip2.model.RepresentationStatus.RepresentationStatusEnum;
import org.roda_project.commons_ip2.model.impl.eark.EARKSIP;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        //Path TempFolder = "c:\\temp\\sip";
        Path TempFolder = FileSystems.getDefault().getPath("c:\\temp\\sip");
        SIP sip = new EARKSIP("SIP_1", IPContentType.getMIXED(), IPContentInformationType.getMIXED());
        sip.addCreatorSoftwareAgent("RODA Commons IP", "2.0.0");
        
        // 1.1) set optional human-readable description
        sip.setDescription("A full E-ARK SIP");
        
        // 1.2) add descriptive metadata (SIP level)
        IPDescriptiveMetadata metadataDescriptiveDC = new IPDescriptiveMetadata(
        new IPFile(Paths.get("src/test/resources/eark/metadata_descriptive_dc.xml")),
        new MetadataType(MetadataTypeEnum.DC), null);

        try{
            sip.addDescriptiveMetadata(metadataDescriptiveDC);
        } catch(IPException ipx){
            System.out.print(ipx.toString());
        }
        // 1.3) add preservation metadata (SIP level)
        IPMetadata metadataPreservation = new IPMetadata(
        new IPFile(Paths.get("src/test/resources/eark/metadata_preservation_premis.xml")));
        try{
            sip.addPreservationMetadata(metadataPreservation);
        } catch(IPException ipx){
            System.out.print(ipx.toString());
        }
       
        // 1.4) add other metadata (SIP level)
        IPFile metadataOtherFile = new IPFile(Paths.get("src/test/resources/eark/metadata_other.txt"));
        // 1.4.1) optionally one may rename file final name
        metadataOtherFile.setRenameTo("metadata_other_renamed.txt");
        IPMetadata metadataOther = new IPMetadata(metadataOtherFile);
        try{
            sip.addOtherMetadata(metadataOther);
        } catch(IPException ipx){
            System.out.print(ipx.toString());
        }
    
        // 1.5) add xml schema (SIP level)
        sip.addSchema(new IPFile(Paths.get("src/test/resources/eark/schema.xsd")));
        
        // 1.6) add documentation (SIP level)
        sip.addDocumentation(new IPFile(Paths.get("src/test/resources/eark/documentation.pdf")));
        
        // 1.7) set optional RODA related information about ancestors
        sip.setAncestors(Arrays.asList("b6f24059-8973-4582-932d-eb0b2cb48f28"));
        
        // 1.8) add an agent (SIP level)
        IPAgent agent = new IPAgent("Agent Name", "OTHER", "OTHER ROLE", CreatorType.INDIVIDUAL, "OTHER TYPE", "",
           IPAgentNoteTypeEnum.SOFTWARE_VERSION);
        sip.addAgent(agent);
        
        // 1.9) add a representation (status will be set to the default value, i.e.,
        // ORIGINAL)
        IPRepresentation representation1 = new IPRepresentation("representation 1");
        try{
            sip.addRepresentation(representation1);
        } catch (IPException ipx){
            System.out.print(ipx.toString());
        }
        // 1.9.1) add a file to the representation
        IPFile representationFile = new IPFile(Paths.get("src/test/resources/eark/documentation.pdf"));
        representationFile.setRenameTo("data.pdf");
        representation1.addFile(representationFile);
        
        // 1.9.2) add a file to the representation and put it inside a folder
        // called 'def' which is inside a folder called 'abc'
                
        IPFile representationFile2 = new IPFile(Paths.get("src/test/resources/eark/documentation.pdf"));
        representationFile2.setRelativeFolders(Arrays.asList("abc", "def"));
        representation1.addFile(representationFile2);
        
        // 1.10) add a representation & define its status
                               
        IPRepresentation representation2 = new IPRepresentation("representation 2");
        //representation2.setStatus(new RepresentationStatus(REPRESENTATION_STATUS_NORMALIZED));
        representation2.setStatus(new RepresentationStatus(RepresentationStatusEnum.ORIGINAL));
        try{
            sip.addRepresentation(representation2);
        }   catch(IPException ipx){
            System.out.print(ipx.toString());
        }

        // 1.10.1) add a file to the representation
        IPFile representationFile3 = new IPFile(Paths.get("src/test/resources/eark/documentation.pdf"));
        representationFile3.setRenameTo("data3.pdf");
        representation2.addFile(representationFile3);
        
        // 2) build SIP, providing an output directory
        try{
            Path zipSIP = sip.build(TempFolder);
            System.out.print(zipSIP.toString());
        } catch(IPException ipx){
            System.out.print(ipx.toString());
        } catch (InterruptedException ie) {
            System.out.print(ie.toString());
        }

    }
}

**Comment by luis100** [comment]
What is the exception?
I notice that you are mixing Windows with Unix-like paths, maybe that is the reason it is not working? Please refer the [Paths.get()](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html#get(java.lang.String,%20java.lang.String...)) on how better use Paths idependently of the file system file path separator.

**Comment by SeismoReimaliMalm** [comment]
The path is now Path TempFolder = Paths.get("C:\\temp"); and it should be ok according. The exception was:
org.roda_project.commons_ip.utils.IPException: Error marshalling METS

I try to use linux too to see if it changes anything.

**Comment by SeismoReimaliMalm** [comment]
Same happens in Ubuntu.

**Comment by luis100** [comment]
Could you paste here the complete exception stack trace?

**Comment by SeismoReimaliMalm** [comment]
That was a very good idea as it complains that it cant find bind:
org.roda_project.commons_ip.utils.IPException: Error marshalling METS
        at org.roda_project.commons_ip2.utils.METSZipEntryInfo.prepareEntryforZipping(METSZipEntryInfo.java:87)
        at org.roda_project.commons_ip2.utils.ZIPUtils.zip(ZIPUtils.java:131)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.createZipFile(EARKSIP.java:175)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.build(EARKSIP.java:143)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.build(EARKSIP.java:97)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.build(EARKSIP.java:71)
        at com.digitalia.memoriaali.App.main(App.java:124)
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
        at org.roda_project.commons_ip2.utils.METSUtils.marshallMETS(METSUtils.java:67)
        at org.roda_project.commons_ip2.utils.METSZipEntryInfo.prepareEntryforZipping(METSZipEntryInfo.java:68)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
        at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
        ... 11 more

**Comment by luis100** [comment]
Which version of Java are you using? Can you try with Java 8?

**Comment by luis100** [comment]
It seems this is a Java 11+ issue, as some classes were removed.
https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio

Anyway, this issue pertains to commons-ip, so will move the issue to that project.

**Comment by SeismoReimaliMalm** [comment]
I owe you a couple of beers. The solution was to add three dependencies to the pom.xml
The solution is to use java 8 or add following:
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.0-b170201.1204</version>
    </dependency>
    <dependency>
      <groupId>javax.activation</groupId>
      <artifactId>activation</artifactId>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.0-b170127.1453</version>
    </dependency>

**Comment by SeismoReimaliMalm** [comment]
`    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.0-b170201.1204</version>
    </dependency>
    <dependency>
      <groupId>javax.activation</groupId>
      <artifactId>activation</artifactId>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.0-b170127.1453</version>
    </dependency>
`

**Comment by luis100** [comment]
glad it works for you, I've updated the commons-ip issue and closed.
Happy coding!

**Comment by SeismoReimaliMalm** [comment]
I am very grateful for your help. This kind of problems are very nasty 
to solve it would be a good idea to document it.

I will offer you a couple of beers if we meet in Malaga sometimes.

Seismo Malm

Luis Faria kirjoitti 17.11.2020 13:47:
