### ISSUE TITLE
Retention and disposal features

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1708]
Support disposal features as defined in [MOREQ2010](https://www.moreq.info/files/moreq2010_vol1_v1_1_en.pdf) section 8 (disposal scheduling service) and section 9 (disposal holding service), with the following limitations:
- Only support disposal actions of DESTROY, RETAIN PERMANENTLY and REVIEW. The action not supportted: TRANSFER
- On REVIEW, only support changing the schedule for a new one. That is, not supporting the whole REVIEW workflow.
- Not supporting retention period offset.
- Not supporting confirmation period, no confirmation period limitation are set nor notifications sent due to overdue confirmations
- Limited set of supported retention triggers

Features:
- [x] New disposal menu
- [x] Disposal policy page to define new disposal schedules and disposal holds
- [x] Disposal policy page allows to define disposal policy rules that define how disposal schedules are associated with records.
- [x] Record/intellectual entity page shows calculated retention period and associated holds and allows to edit the associated disposal schedule and disposal holds
- [x] Disposal confirmation page allows to check all overdue disposal records and create a disposal confirmation report which can be viewed and printed.
- [x] Pending disposal confirmation reports can be executed and the records destroyed
- [x] Destruction rules are available in the configuration including how record data is deleted and how metadata is pruned
- [x] Disposal bin feature allows to recover destroyed records or to permantetly deleted them. Permanent deletion job can be scheduled.

**Comment by hmiguim** [comment]
Close at 9b5a2ee8c5c915a9d5cf05659b27831ddef7bdf4
