### ISSUE TITLE
Adding Croatian language

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1711]
If resources are 100% ready on release date.
https://www.transifex.com/roda-1/roda2/language/hr/

**Comment by luis100** [comment]
@tkarlovic please ensure translation is ready up to end of the year (2020)

**Comment by tkarlovic** [comment]
@luis100 we are finished except for some GitHub .md files which contain mostly developer instructions. Our opinion is that it doesn't make sense to translate in the Croatian language since Croatian-speaking developers are more familiar with English and in most cases, we don't have proper Croatian translations. What is your suggestion?

**Comment by luis100** [comment]
Not all files make sense to be translated, and you can refer to the Portuguese language resources in Transifex to get a sense of what we have chosen not to translate. But the files you do choose to translate please do so completely (i.e. translate the whole file).

We are currently in code freeze for version 4.0 and have merged into development all resources relative to the disposal feature, but not all of them are in Transifex yet. We will be adding them next week and send a notification via Transifex to all translators. This wont be much extra work, just around 10-20 paragraphs to be translated in different files.

We will be merging the code after code freeze and doing the required setup to add the Croatian language, then we'll give you a couple of weeks to check if everything looks fine before making the 4.0.0 release early next year.

**Comment by luis100** [comment]
@tkarlovic all files relative to RODA 4.0 added to transifex for translation. Most have already been translated to Croatian, but please note that there are 5 string missing translation at [ClientMessages.properties](https://www.transifex.com/roda-1/roda2/viewstrings/#hr/roda-ui-roda-wui-src-main-resources-config-i18n-client-clientmessages-properties--development/308763704?q=translated%3Ano) resource.

**Comment by luis100** [comment]
@tkarlovic please be aware that we are about to release RODA 4.0 and there are some strings that are missing a Croatian translation. Please ensure these strings are translated in the next couple of days so we can include the translation into Croatian in this release.

**Comment by hmiguim** [comment]
Close at ab243a70a3da73c2bfb0445a79ce881c7cbf9ec0
