### ISSUE TITLE
Rethink the way facets that can contain many lines of information are displayed on the UI

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#174]
Examples: 
- The facet included in the transference area to choose producers

**Comment by luis100** [comment]
In the transfer area, removed the producer form facets. Producer list is now shown on the first listing of the table.

Still this problem can occur in other panes, just as the Log.

**Comment by hsilva-keep** [comment]
Facets are shown, up to the predefined value of 100, in the interface. If that behavior needs to be changed, new issue must be created & set to proper milestone.
