### ISSUE TITLE
Javascript snippet to include RODA viewers in the producer catalogues

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#176]
Think of alternatives.

**Comment by jmaferreira** [comment]
We have defined 3 levels of integration. This is level no 1.

**Comment by luis100** [comment]
@jmaferreira can this issue be closed?

**Comment by jmaferreira** [comment]
No. Put it in unplanned.

**Comment by jmaferreira** [comment]
Done already as part of the integration with third party apps.
