### ISSUE TITLE
Create VM with RODA pre-installed

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#177]

**Comment by hsilva-keep** [comment]
We could also make available vagrant & docker "stuff", by releasing them into their own registries: [public Vagrant box catalog](https://atlas.hashicorp.com/boxes/search) & [Docker Hub](https://www.docker.com/products/docker-hub).

**Comment by hsilva-keep** [comment]
This won't be done as now, as part of the maven build process, a docker image can be created and uploaded to the public hub under the following url: https://hub.docker.com/r/keeps/roda/.
Also, instructions on how to install docker and run RODA container were added to the [README.md](https://github.com/keeps/roda/tree/lf_dev#install-and-run)
