### ISSUE TITLE
Make Google Analytics configurable (roda-wui)

### ISSUE THREAD

**Issue by luis100** [keeps/roda#18]
Google analytics code is currently hardcoded in .html pages.

**Comment by luis100** [comment]
Needs to be tested again in new implementation.

**Comment by jmaferreira** [comment]
I think it isn't working. The analytics script is not showing up on the rendered page.

**Comment by jmaferreira** [comment]
I suggest placing on the configuration the entire javascript instead of just the Tracking ID. Sometimes this javascript changes and it would make it easier to update.

**Comment by jmaferreira** [comment]
The analytics is being injected as such (hardcoded):


	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push([ '_setAccount', 'UA-XXXXX-X' ]);

		(function() {
			var ga = document.createElement('script');
			ga.type = 'text/javascript';
			ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl'
					: 'http://www')
					+ '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(ga, s);
		})();
	</script>



It should be injecting: <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-7248825-14', 'auto');  ga('send', 'pageview'); </script>

**Comment by jmaferreira** [comment]
Works fine. thanks
