### ISSUE TITLE
Persist job information in storage

### ISSUE THREAD

**Issue by luis100** [keeps/roda#180]
Possibly in XML.

**Comment by hsilva-keep** [comment]
Done (using json, but xml could be also used, one just need to change the method that persists the information from the Job object) since 489f392b027224ee25856736c8cc00444a5f7980.

**Comment by jmaferreira** [comment]
I would recommend XML as most persistent data is stored this way.


Cumprimentos,
Miguel Ferreira

- -
Diretor executivo
KEEP SOLUTIONS, LDA.
Rua Rosalvo de Almeida, nº 5
4710-429 Braga, Portugal
W www.keep.pt E info@keep.pt 
T +351 253066735 F +351 253067248
