### ISSUE TITLE
Revise the ingest process so that failed tasks are recorded as such and the SIP is rejected 

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#184]
The tasks that automatically reject SIPs are the validation ones.

**Comment by luis100** [comment]
This is done but is missing a final cleanup removing any inactive AIP that might have been created in the process.

**Comment by hsilva-keep** [comment]
- [ ] During RODA start up, when job clean up is conducted, find all AIPs that were created by a job that has failed and if they are in the state INGEST_PROCESSING or CREATED, then remove them.
- [ ] After executing a job, do the same as before.

**Comment by hsilva-keep** [comment]
Instead of effectively deleting the AIPs, the Filesystem storage service method delete should be changed to move things to a folder inside RODA home (see configuration file to know which folder should be used (relative to the data folder))

**Comment by hsilva-keep** [comment]
Done (since 22c3d68f503aa90d85aa7f6f4b9ff755326a8a8c).
