### ISSUE TITLE
Remove the flags from the header and place them on the menu under an icon at the right end (next to the login)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#188]
1. Use one of the following icons on the menu:

http://fontawesome.io/icon/language/
http://fontawesome.io/icon/globe/

2. Place each language name in its original terminology in menu items.

**Comment by jmaferreira** [comment]
See example.

![screen shot 2016-01-28 at 12 18 39](https://cloud.githubusercontent.com/assets/3181302/12644232/5822f786-c5b9-11e5-99b4-cabe23aa24ff.png)

**Comment by vitorfernandes87** [comment]
Closed on 68cd9f8e42838091490243799ba49acb3d691597
Improvement: the supported languages should be dynamic.
