### ISSUE TITLE
Revise pre-ingest page

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#189]
* Add a button to the pre-ingest page that allows one to download the classification plan(s) that are associated to a producer
* Add a button to upload a plan exported by RODA-in
* Add link to the releases page of RODA-in or to the github page - http://keeps.github.io/roda-in/
* Add text to explain the whole process.

**Comment by luis100** [comment]
This button should open the REST API method GET `/api/v1/classification_plans?type=bagit`

**Comment by jmaferreira** [comment]
Pre-ingest 

The pre-ingest process depicts the ability of a Producer to create Submission Information Packages (SIP) containing both data and metadata, in a well-defined structure, that meets the policies established by or negotiated with the repository.

The pre-ingest procedure usually comprises some or all of the following activities:

1.	Negotiation

This activity consists of the definition of the terms, conditions and requirements for data, and all accompanying information, to be sent to the repository by the Producer.

Part of this activity consists of the creation of a base classification scheme (or collections) on the repository to which the Producer should comply.

You may download your classification scheme in this page.

[DOWNLOAD CLASSIFICATION SCHEME]

2. Submission agreement

This activity consists of signing a written agreement between the Producer and the Repository that specifies the type of content and all the legal and technical requirements that both parties should meet.

One may download a Submission Agreement template here.

3. Submission Information Packages

This activity consists of the preparation of Submission Information Packages (SIP) by the Producer according to the technical and non-technical requirements as defined by the Submission Agreement.

To facilitate the creation of SIPs you may take advantage of the RODA-in tool. Documentation and software are available at http://rodain.roda-community.org

[DOWNLOAD SIP CREATION TOOL]




4. Transfer of materials

This activity consists of the electronic transfer of Submission Information Packages (SIP) from the Producer to the Repository. SIPs will be temporarily stored in a quarantine area waiting for ingest. 

If you made changes to the classification scheme in RODA-in, you should first upload the new version of the classification scheme in order to update the Archive information.

[UPLOAD CLASSIFICATION SCHEME]

SIPs may be delivered via electronic transfer (e.g., FTP) or loaded from media submitted to the Archive.

FTP transfer

1.	Connect to [ftp://address] and use the credentials provided by the Archive in order to log in. 
2.	Create a folder to hold the SIPs you which to be part of a single ingest batch (Optional). 
3.	Copy all the created SIPs to the new folder.
4.	Inform the Archive that content is ready to be ingested.

External media transfer

1.	Save SIPs to an external media (e.g. CD, USB disk, etc.)
2.	Deliver it at the following address: [Archive address]
Ingest process

After transfer, SIPs will be selected for ingest by the Archive. The Ingest process provides services and functions to accept Submission Information Packages (SIPs) from Producers and prepare the contents for storage and management within the Archive. 

Ingest functions include receiving SIPs, performing quality assurance on SIPs, generating an Archival Information Package (AIP) which complies with the Archive’s data formatting and documentation standards, extracting Descriptive Information from the AIPs for inclusion in the Archive catalogue, and coordinating updates to Archival Storage and Data Management. 
[preingest.docx](https://github.com/keeps/roda/files/141529/preingest.docx)

**Comment by vitorfernandes87** [comment]
Page revised.
Button for upload classification scheme isn't working because the interface doesn't exist.
Button for download the submission agreement isn't working because the file wasn't sent.
Another issue for those buttons needs to be created.
