### ISSUE TITLE
Add cache mechanism

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#191]
There are a couple of "things" that are generated in runtime and can be resource intensive/expensive (CPU, memory, duration time, etc) and therefore could be cached. 
Things like generating html views from descriptive metadata (which uses xslt for transforming xml in html). 

Suggestions/alternatives:
- Ehcache
- memCache
- JBoss Cache
- OSCache
- Java Caching System
- ...

Some articles talking about this subject:
- https://www.linkedin.com/pulse/java-caching-frameworks-enterprise-applications-anshuman-biswal
- http://www.vizteams.com/blog/java-caching-frameworks-for-enterprise-applications/

**Comment by luis100** [comment]
First approach could use the Guava Cache approach which is quite simple, straightforward, and already in dependencies.

Already used here:
https://github.com/keeps/roda/blob/3d72ca0893b747e3d4523820631a294e19f3039e/roda-core/roda-core/src/main/java/org/roda/core/common/RodaURIFileResolver.java

**Comment by hsilva-keep** [comment]
Caching objects that don't change that much & are used several times, is already done. If more specific cases occur, please create new issue.
