### ISSUE TITLE
When generating PREMIS metadata make sure that we record all the relevant information

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#193]
Namely:

- The person that executed the action (Agent)
- The software that executed the action (Agent)
- When was the action performed (Event)
- What was the outcome of the action (Event)
- What objects were touched by the action (Event)

**Comment by sleroux-keep** [comment]
1 - I need the "Plugin name / Agent name", "Plugin description / Agent note", "Event detail", "eventOutcomeDetailNote (Success)", "eventOutcomeDetailNote (Partial)", "eventOutcomeDetailNote (Failure)", "Linking Sources", "Linking outcomes" for the VerifyProducerAuthorizationPlugin
2 - The order in the "RODA 2.O ingest workflow" document is different from the DefaultIngest Plugin... Which one is the correct?

**Comment by jmaferreira** [comment]
RODA 2.O ingest workflow

**Comment by sleroux-keep** [comment]
I need the RODA 2.O ingest workflow (Google Drive) updated with the updated premis event types
([http://id.loc.gov/ml38281/vocabulary/preservation/eventType.html](http://id.loc.gov/ml38281/vocabulary/preservation/eventType.html) )

**Comment by jmaferreira** [comment]
There will be no alterations to the existing table, unless there has been small changes to the wording. Please check the wording on the list and make amendments if necessary. 

Extra events we have on our list will not be removed or changed.

**Comment by luis100** [comment]
Just check if the PREMIS events types that are already used are correct (don't have small orthographic changes) and close this issue.
