### ISSUE TITLE
How to validate a SIP file (CLI, tool, website?)

### ISSUE THREAD

**Issue by philippefaes** [keeps/roda#1939]
Can I use Roda to validate my SIP file? I would like to check if the SIP file is valid.
Is there a command line tool or a web tool to do this?

**Comment by luis100** [comment]
Validation of E-ARK SIP v2.0.4 against specification is being developed on the commons-ip library, which is used by RODA.
You can check the development issue at https://github.com/keeps/commons-ip/issues/44 (on the roadmap to be release in October 2021).

In the meanwhile, you can use  RODA to ingest the SIP, which will use commons-ip library to parse the SIP and transform it into an AIP, which will up to some level validate the SIP.

If this is a one-off validation with non-sensitive content, I would suggest using the [RODA demo site](https://demo.roda-community.org/).

**Comment by luis100** [comment]
Hey @philippefaes you now have a command-line tool to validate your SIP file!
Checkout: https://github.com/keeps/commons-ip#use-as-a-command-line-tool
