### ISSUE TITLE
limit for AIPs

### ISSUE THREAD

**Issue by wbz-hot** [keeps/roda#1941]
If use roda on windows ，the upper limit of AIPs  ? Whether to use another file system?

**Comment by luis100** [comment]
On a off-the-shelf implementation of RODA, the limit of AIPs will be tied to the maximum number of files in a single folder.
For NTFS, this is around 4000 million, so you will probably have Solr index size issues before you get to that point. For FAT32 this seems to be  65534, so I would highly recommed not using this file system.

Source: https://askleo.com/is-there-a-limit-to-what-a-single-folder-or-directory-can-hold/

[KEEP](https://www.keep.pt) offers some commercial extensions that allow to overcome this issue by using a folder scattering technique which avoids creating too many AIP folders under a single folder.
