### ISSUE TITLE
Does anyone knows what collection, class and records group are?

### ISSUE THREAD

**Issue by KiarashE** [keeps/roda#1944]
Hi there,
I just start learning about Roda Software. When I create intellectual entity, I can choose Fonds, Series, Sub-series, File and Items. I am familiar with these, but I don't get what Collection, Record group and Class are for. 
Is there any documentation describing these? Or can anybody with few words describe Collections, Record groups and Classes, and purpose and usage of them. 
Thank you for any hints

**Comment by luis100** [comment]
RODA is a multipurposed tool that serves different communities, which use different terminology.

The description level, a field that comes from [ISAD(G)](https://www.ica.org/en/isadg-general-international-standard-archival-description-second-edition), can have the usual ISAD(G) values of fonds, series, sub-series, file and items, which are normally used by archives.

Record managements systems, on the other hand, might follow standards like [MoReq2010](https://www.moreq.info/files/moreq2010_vol1_v1_1_en.pdf), which use classes, aggregations and records. Most commonly, these are ortogonal categorizations and classes are the one used for organizing the records in contextual or semantic categorizations.

Collection is a term mostly used in Libraries, which can be used to catalogue books. This could be further extended to include terminology like works, expressions, manifestations and items from the [FRBR](https://www.loc.gov/cds/downloads/FRBR.PDF) terminology.

The terminology you choose and have available in the system can be [configured](https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/resources/config/roda-wui.properties#L1998-L2030) in RODA, which by default presents a superset of levels that can apply to different types of institutions.
