### ISSUE TITLE
Object PREMIS does not register contentLocation in storage element

### ISSUE THREAD

**Issue by JelleKleevensVAI** [keeps/roda#1947]
To reproduce:
1. Upload and ingest SIP in RODA (default workflow 2, E-ARK 2)
2. Check preservation metadata under representations > rep1 > metadata > preservation > any file level PREMIS.xml

ContentLocation element is always empty in my experience.

![image](https://user-images.githubusercontent.com/87436774/132325750-8020599b-6432-4c1a-963d-319dd2f4181f.png)

**Comment by luis100** [comment]
Could you provide more details on this issue and how to reproduce it?

**Comment by JelleKleevensVAI** [comment]
Edited my first comment. Not sure what the contentLocation element stands for exactly, just that it is never filled.

**Comment by luis100** [comment]
![image](https://user-images.githubusercontent.com/631728/132329052-5b742b11-0ee4-4f29-8c41-6f347398ce54.png)
from http://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf

The element is optional, but it should not be empty. "This could be a fully qualified path and filename, or the information
used by a resolution system (e.g., a handle), or the native information used by a storage management system"
