### ISSUE TITLE
State over 100%  when apply the instance id on AIP pres events

### ISSUE THREAD

**Issue by TiagoFraga** [keeps/roda#1955]
During some tests when apply the instance Id to AIP pres events the state goes over 100%

**Comment by JoaoGomes2110** [comment]
The issue still occurs 
![image](https://user-images.githubusercontent.com/17931713/165566450-aa2aa287-3887-4f55-8b3a-0e33807c94ca.png)

**Comment by hmiguim** [comment]
SimpleJobPluginInfo is still outdated, probably the refactor override the changes. I'll manually fix and commit.
