### ISSUE TITLE
405 Method Not Allowed with "/v1/representations/{aip_id}/{representation_id}"

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1957]
Good day everyone!

Based on the API documentation there should be a possibility to create new representation outside of the RODA UI.
But using template ".../api/v1/representations/aip_id/representation_id?type=mixed&details=reason&acceptFormat=json" is responding by 405 Method Not Allowed.

Am I missing some sort of prerequisites before posting such command or is it simply not currently enabled?

**Comment by elbre** [comment]
Good day again.
Sorry to bother with this after such delay.

I tried to replicate your example on the demo version. And it fail with 

**Failed to fetch.
Possible Reasons:
CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.**

So I am quessing that for these requests I need to be "local".

Either way, I tried this method in postman for our server and it claims that only allowed methods are **GET or DELETE**.
Can be there some similar issue as in the #1516 ? And therefore could you navigate me which properties I should check if they are on the right place?

Thank you very much

**Comment by hmiguim** [comment]
Use the URL https://roda-community.org/api-docs/ instead of https://demo.roda-community.org/api-docs/ and retry the operation.

**Comment by elbre** [comment]
![questfail_rep](https://user-images.githubusercontent.com/48675042/215059861-cae82f99-ac4e-4bda-9c6c-5c16c3df1476.png)

**Comment by hmiguim** [comment]
The AIP ID you set as argument does not exists

**Comment by elbre** [comment]
Good point indeed. I was trying to be precise againt the provided example.
I used the API to list the IDs to be sure and even with for example "79fc6077-2921-44a3-8a39-a796294d56f7" the response is identical.

I apologise for the trouble.

**Comment by hmiguim** [comment]
![image](https://user-images.githubusercontent.com/1252710/215079847-58d5070d-bea3-4c5e-88d4-b3411de96b27.png)

You should have a button that says "Authorize", click the button and fill up the username and password fields. After doing the authorization it should work as intended.

Username and password are provided visiting the demonstration website: https://roda-community.org and wait for a few seconds.

![image](https://user-images.githubusercontent.com/1252710/215080215-a0b5cebd-9e16-4833-a77e-7f19157d1c91.png)

**Comment by elbre** [comment]
Thank you for the concern about the basics in this case.
Yes I indeed have button "Authorize" and I used it during my testing.
I even let my collegue to try it as well.
You can even see in my previous screenshot that CURL is containing the Authorization line.

Still no success.

**Comment by hmiguim** [comment]
The Swagger-UI is not working properly to POST requests, we'll investigate what is causing this issue. As an alternative you can try use the cURL but without the **-d ''** options or the request URL.
