### ISSUE TITLE
Risk register UI

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#199]

**Comment by jmaferreira** [comment]
I didn't do a mockup, but written down the requirements in detail. See bellow:
--



Develop a panel called "Risk Register" similar to the catalogue, but with the following differences/requirements:

- Columns (sortable):
  - IdentifiedOn
  - Risk name
  - Category
  - Severity (use post-mitigation or pre-mitigation severity if no action has been made yet), possibly as names, instead of numbers (e.g. low, high)
  - Owner
  
- Rows:
  - Rows should be coloured from green to red depending of the severity (see Excel for the scale)

- Sidebar Actions:

  - Risks
    - Edit
    - New
    - Remove
    
  - Actions
    - Start new process

- Sidebar facets:
  - Risk name
  - Category
  - Severity
  - From / to
  
The risk files (based on the available schema) can exist at multiple repository abstraction levels:

- Repository level
- AIP level
- Representation level
- File level

These XML files should be stored on the corresponding places (system, AIPs/metadata/risks, representations/metadata/risks

**Comment by jmaferreira** [comment]
Faria,

We need services to support the operations described in this ticket. Please assign this issue to the right person and then assign it to @vitorfernandes87 for UI development.

**Comment by vitorfernandes87** [comment]
Started risk register interface on 9a976c2cb1b1b8c229a2d8e9bc0ffab3a70a3076
We should have a class named like 'IndexedRisk' and methods to create/edit/remove.
Then we need to create a new list to search/retrieve all risk register.

**Comment by luis100** [comment]
Implementation of backend is done #198

**Comment by luis100** [comment]
Done
