### ISSUE TITLE
How to import RODA into Eclipse?

### ISSUE THREAD

**Issue by mohimoradi** [keeps/roda#2000]
I wrote an Eclipse plugin and am now collecting a database of large Java Maven projects. I tried to import RODA into Eclipse, but I couldn't compile it and run the tests.

I tried changing the java version (8 to 17) or maven version(3.1.1 to 3.8.1), adding that plugin to maven dependencies, and following all of the StackOverflow suggestions, such as removing the.m2 folder, but none of them worked.

Is it possible to run the test classes inside Eclipse? If so, what procedure should I follow?
![image](https://user-images.githubusercontent.com/81889496/161006196-35f37321-f04c-4051-adc5-310c993db468.png)

The similar error occurred in WSL as well.
![2022-03-31 03_34_47-mohsen@DESKTOP-M216192_ _mnt_c_ScalaProject_actortest_FINAL_PRJ_roda](https://user-images.githubusercontent.com/81889496/161005493-a2216a73-f4be-4cff-82ed-d074473b21e8.png)

**Comment by luis100** [comment]
Hello,
Now we are using github packages which makes you have to put your github account in your ~/.m2/settings.xml to be able to use them.

Check this on how to do it:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-with-a-personal-access-token

**Comment by eriksali** [comment]
Hi, I got the error message when compiling roda: Failed to execute goal on project roda-core: Could not resolve dependencies for project org.roda-project:roda-core:jar:4.3.0-SNAPSHOT: Failed to collect dependencies at org.roda-project:commons-ip2:jar:2.0.0: Failed to read artifact descriptor for org.roda-project:commons-ip2:jar:2.0.0: Could not transfer artifact org.roda-project:commons-ip2:pom:2.0.0 from/to github (https://maven.pkg.github.com/keeps/*): transfer failed for https://maven.pkg.github.com/keeps/*/org/roda-project/commons-ip2/2.0.0/commons-ip2-2.0.0.pom, status: 400 Bad Request -> [Help 1]

Any suggestion would be appreciated!

**Comment by hmiguim** [comment]
Hi @eriksali 

You just need to follow this link: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-with-a-personal-access-token.

**Comment by eriksali** [comment]
Hi Miguel, I will follow this link and try it. Thank you and have a great day!

**Comment by luis100** [comment]
Please note that it cannot on your maven settings you cannot put your GitHub password, but a GitHub "Personal access token".
https://github.com/settings/tokens

**Comment by eriksali** [comment]
Hi Luis,

Thanks for your reply!

Yes, you are right. I used a personal access token and username of GitHub.
For the installation of roda, it seems that some dependencies could not be
accessed which I am still not able to figure out.
Any suggestions would be appreciated.

Thank you and have a great weekend!

Best,
LI

**Comment by luis100** [comment]
Which dependencies still fail?

**Comment by eriksali** [comment]
Thank you Luis, it's in submodule roda-common-util which was posted in the screenshot. I tried really hard but failed to fix it.

**Comment by eriksali** [comment]
Hi Luis,

I am now trying to import roda into Eclipse but failed:

error: invalid path 'roda-core/roda-core-tests/src/main/resources/corpora/aip/AIP_1/representations/representation_1/metadata/preservation/urn:roda:premis:event:roda_398.xml'

Btw, it can not be cloned with command git clone https://github.com/keeps/roda

Any suggestion would be appreciated.

Best,
LI

**Comment by eriksali** [comment]
The error is as follow:
Failed to execute goal on project roda-core: Could not resolve dependencies for project org.roda-project:roda-core:jar:4.3.0-SNAPSHOT: Failed to collect dependencies at org.roda-project:commons-ip2:jar:2.0.0: Failed to read artifact descriptor for org.roda-project:commons-ip2:jar:2.0.0: Could not transfer artifact org.roda-project:commons-ip2:pom:2.0.0 from/to github (https://maven.pkg.github.com/keeps/*): transfer failed for https://maven.pkg.github.com/keeps/*/org/roda-project/commons-ip2/2.0.0/commons-ip2-2.0.0.pom, status: 400 Bad Request -> [Help 1]

**Comment by eriksali** [comment]
![image](https://user-images.githubusercontent.com/43148041/162546743-af457587-085b-4a0e-a262-8fbf457614ee.png)

**Comment by luis100** [comment]
Hi could you please try:
1. Download the package directly using your GitHub username and access token https://maven.pkg.github.com/keeps/*/org/roda-project/commons-ip2/2.0.0/commons-ip2-2.0.0.pom
2. Compile using maven by running:`mvn clean package`
3. Try using IntelliJ as an IDE instead of Eclipse. Although our instructions still point to eclipse, our dev team only uses IntelliJ for years now.

**Comment by eriksali** [comment]
Hi Luis,

It works. I appreciate your help!

Best,
Li
