### ISSUE TITLE
Reduce indexed information of the entities that spend much of the index

### ISSUE THREAD

**Issue by luis100** [keeps/roda#2058]
As observed in several implementations, the following entities spend much of the index storage size:
1. Preservation events
2. Job reports
3. Files

Reduce and optimize the indexed information of these entities so to only index what needs to be searched and showed in search results. Full information about such objects, to show in the detailed panel, must always come from the model.

**Comment by 006627** [comment]
Resolved at d927ff92583c10cfbeabed8b76d028c9cde300bd and 9a05fd13b6fcd105f5b2614c6befdf86bbe0b48e, Files have not been optimized
