### ISSUE TITLE
Create menu entry Administration and Planning with the the following subitems

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#209]
# Administration

The Administration Functional Entity (labeled ‘Administration’ in the figures in this section) provides the services and functions for the overall operation of the Archive system. Administration functions include soliciting and negotiating

- Preservation actions - Jobs management
- Users - User and groups management
- Activity log - System logs for auditing reasons
- Preferences - Panels to change the administrative/preservation settings of the repository. Not the system settings (e.g. LDAP). 

# Planning

The Preservation Planning Functional Entity (labeled ‘Preservation Planning’ in the figures in this section) provides the services and functions for monitoring the environment of the OAIS, providing recommendations and preservation plans to ensure that the information stored in the OAIS remains accessible to, and understandable by, the Designated Community over the Long Term, even if the original computing environment becomes obsolete. Preservation Planning functions include

- Internal monitoring - Shows statistics about the contents of the repository
- Risk register - Risk management
- Agents register- List of installed agents and the ability to change the texts
- Format register - List of fileformats and information about these

**Comment by vitorfernandes87** [comment]
Menu options added redirects to a blank page.
