### ISSUE TITLE
Produce METS.xml according to EARK AIP

### ISSUE THREAD

**Issue by luis100** [keeps/roda#216]
From the aip.json and files in AIP generate METS.xml according to EARK AIP specification.
This task can then be used to export the AIP according to EARK AIP specification or to update existing AIPs in storage with the METS.xml.

**Comment by hsilva-keep** [comment]
Most of the work has been done already in commons-ip. 
In https://github.com/keeps/commons-ip/blob/master/src/main/java/org/roda_project/commons_ip/model/impl/eark/EARKMETSUtils.java#L67 you'll find base METS instantiation and in https://github.com/keeps/commons-ip/blob/master/src/main/java/org/roda_project/commons_ip/model/impl/eark/EARKMETSUtils.java#L274 you'll find, for example, the logic to add a descriptive metadata file to METS. 
The only thing missing is the submission part, but that is fairly easy to add.

**Comment by luis100** [comment]
Superseded by #652
