### ISSUE TITLE
Add cookie message to the welcome page

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#217]
I like the one used on this page: http://googlesystem.blogspot.pt/2013/10/youtube-drops-support-for-1080p-streams.html 

More:

https://github.com/ToX82/cookie-bar
https://cookie-script.com/

**Comment by vitorfernandes87** [comment]
https://silktide.com/tools/cookie-consent/

**Comment by vitorfernandes87** [comment]
Miguel, something like this (with different design of course)? 
This should be configurable in roda-wui.properties and loaded on runtime, allowing to set the strings by locale.
Which text should appear in the message?
We can also have a page explaining the cookies law (like http://demo.weebox.pt/community/theme/policyEN.html)

![captura de ecra de 2016-03-09 11 18 57](https://cloud.githubusercontent.com/assets/9133305/13633726/c39f57ee-e5e8-11e5-8e74-f72ed6eef305.png)

**Comment by jmaferreira** [comment]
Yes. Exactly like that. I would just change the design of the button to match our button design.

It would be nice to add a link to a page that explains the types of cookies there are. See if this helps: https://optanon.com

**Comment by vitorfernandes87** [comment]
Shouldn't be a theme page?
That way we can have the cookies page in different languages.

**Comment by jmaferreira** [comment]
Yes

**Comment by vitorfernandes87** [comment]
Closed on 1fe9348487e641c91062aea28d94dd4b67e63288
