### ISSUE TITLE
Update Fedora Commons to latest stable version

### ISSUE THREAD

**Issue by luis100** [keeps/roda#22]
Possible wait for Fedora Commons 4.0, for scalability reasons.

**Comment by ankhazam** [comment]
Hi, any news on this case as fedora is already in 4.3 stable release...

**Comment by hsilva-keep** [comment]
@ankhazam 
Yes, there are...We're doing serious changes to RODA, in what concerns its architecture (what will be known as RODA version 2.x.x), and those changes are still in progress but we are already using Fedora 4.3 (or at least it's one of the storage service that can be used in RODA). Most of the work, until the moment, is essentially being done in roda-wui and roda-common-storage (this last component may still be renamed).

**Comment by ankhazam** [comment]
Sounds good, though I understand you cannot provide any serious ETA for a stable updated RODA release?

**Comment by hsilva-keep** [comment]
@ankhazam  
That's correct, but still it will most certainly happen until the end of this year. Please stay tuned ;)

**Comment by luis100** [comment]
Support for Fedora 4 added in RODA 2.0.0
