### ISSUE TITLE
Errors in the instance page

### ISSUE THREAD

**Issue by 47Balboa** [keeps/roda#2208]
Improve error handling when trying to access to the page of an instance that has already been removed.
After deleting the distributed instance if we try to access to the old url it should redirect to the welcome page.
![image (9)](https://user-images.githubusercontent.com/36776778/175279871-597d6e33-0aeb-4ad6-922a-be3843645838.png)

**Comment by hmiguim** [comment]
https://github.com/keeps/roda/pull/2203
