### ISSUE TITLE
String "part" allowance to API /v1/aips/{aip_id}/{part}

### ISSUE THREAD

**Issue by elbre** [keeps/roda#2210]
Good day!
By API documentation is possible to download the AIP partially.
Would you be so kind and enlighten me on what kind of strings are allowed as "part"? Or how specific the call can be?

Thank you for the answer.

**Comment by luis100** [comment]
A "part" can be: "submission", "documentation" and "schemas".

https://github.com/keeps/roda/blob/a68014791b78fd453b8e563c99cae0a68b24b310/roda-ui/roda-wui/src/main/java/org/roda/wui/api/controllers/BrowserHelper.java#L2393-L2409

Metadata and data can be downloaded via other REST-API methods.
