### ISSUE TITLE
Question about RODA in Docker on Windows

### ISSUE THREAD

**Issue by mattiasmalmborg** [keeps/roda#2223]
Hey! Don't know if this is the right place to ask but here it goes. I'm trying to run RODA in docker on windows. I've pulled the image and can run the container successfully. But when I open up RODA in a browser I can't see the images or the menus on the front page. If I highlight the whole page I can see that there is content on the page but I can't navigate the menu this way (see attached images). I've deleted the image and done all the steps again with the same result. Tried different browsers as well with no luck. Is there a dependency I'm missing?

![RODA online DEMO](https://user-images.githubusercontent.com/82843789/183906010-89fb53db-6b4f-4377-8215-9d7808870569.png)
![RODA localhost new install](https://user-images.githubusercontent.com/82843789/183906014-b7609955-b1da-415e-b176-3c777fc8b4e4.png)

**Comment by luis100** [comment]
That would normally happen if something went wrong during initialization. You need to go within the RODA docker container and see the content of the /roda/log/roda-core.log to check what is failing.

**Comment by mattiasmalmborg** [comment]
Thanks for your response! Okey, it seems to happen every time. Tried running image with different variables for port and volume. Same result except when running with default port then the browser page doesn't work at all. I can see in the log (attached image) that it can't authenticate user. Not sure how to resolve this since I'm not used to using docker this way. 

I just wanted to try it out for myself on my laptop so it's a bummer it doesn't work but not the end of the world. 

![RODA error log](https://user-images.githubusercontent.com/82843789/183921879-165f66d1-3683-4a7b-84e4-3fa44f192ea8.png)

**Comment by luis100** [comment]
Can you get the whole log file? Or at least try to find the first error as those ones are just Javascript errors caused by the server being with a initialization problem.

**Comment by mattiasmalmborg** [comment]
No idea how to get the log out to a file, but here is the first part of the log. I see that it seems to have writing issues?

![RODA error log](https://user-images.githubusercontent.com/82843789/183928385-877a6b54-63b9-4540-b562-ff6801e745b4.png)

**Comment by mattiasmalmborg** [comment]
No idea how to get the log out to a file, but here is the first part of the log. I see that it seems to have writing issues?

![RODA error log2](https://user-images.githubusercontent.com/82843789/183928858-1ff420ea-fd0c-4ea7-ad28-5d72da0283e1.png)

**Comment by luis100** [comment]
Yes, it seems /roda/data is not writable within the container, how have you deployed this?
Generally, we recommend using Linux hosts to start up RODA as docker containers, and would recommend doing so using the available deploys on:
https://github.com/keeps/roda/tree/master/deploys

In RODA 5 this setup will be required, as we will be dividing services into several containers.

**Comment by mattiasmalmborg** [comment]
I followed the guide here: https://www.roda-community.org/#theme/Installation_Testing_Environments.md
Which took me to dockers home page and then I just downloaded the windows klient. Once installed i pulled down the latest RODA-image and ran in it. 

I have a Linux host at home I can try it on so might do that instead then. Thank you so much for your support!
