### ISSUE TITLE
Error downloading PREMIS

### ISSUE THREAD

**Issue by luis100** [keeps/roda#223]
When downloading PREMIS via the interface, the following error appears:
```json
{
type: "error",
message: "Cannot find file or directory at /Users/lfaria/.roda/data/storage/AIP/55739630-939d-4a31-9d42-61d036a689b5/representations/75bfda66-5873-40e8-a0e1-8bf7e2140804/metadata/preservation/75bfda66-5873-40e8-a0e1-8bf7e2140804.represen.representation.premis.xml"
}
```

**Comment by sleroux-keep** [comment]
Fixed and "updated" zip structure:

AIPID
  AGENTS
    agent1.xml
    ...
  METADATA
    PRESERVATION
      event1.xml
      ...
   REPRESENTATIONX
      representationX.xml
      fileX.xml
      ...
   ...
