### ISSUE TITLE
RODA debian package

### ISSUE THREAD

**Issue by luis100** [keeps/roda#23]
Create a debian package to install RODA. Support last Debian version and last Ubuntu LTS.

**Comment by hsilva-keep** [comment]
This won't be done as now, as part of the maven build process, a docker image can be created and uploaded to the public hub under the following url: https://hub.docker.com/r/keeps/roda/.
Also, instructions on how to install docker and run RODA container were added to the [README.md](https://github.com/keeps/roda/tree/lf_dev#install-and-run)
