### ISSUE TITLE
Plugin get version should be cached

### ISSUE THREAD

**Issue by luis100** [keeps/roda#233]
When ingesting, the get version method of each plugin is called for each run on each AIP. For plugins like Siegfried, this means executing sf --version millions of times with the same output. This is not necessary and should be cached on each Plugin implementation or at AbstractPlugin common implementation.

**Comment by hsilva-keep** [comment]
This is being done already, i.e. in the case of SiegfriedPlugin, getVersion is called multiple times but only the first one will execute the command (because getVersion caches the version after executing getVersionImpl for the first time).
