### ISSUE TITLE
Add a column to the catalogue and search results with the name of the level

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#234]
Its not obvious to everyone to infer that from the icon.
Keep the icon but add a column to its right with the expanded name.

Delegate on @vitorfernandes87 if necessary.

**Comment by sleroux-keep** [comment]
Added text level column. Need translation (see #286 )
![textlevel](https://cloud.githubusercontent.com/assets/2727798/14425949/1bf0fb64-ffe3-11e5-876c-69ba85cfafa0.png)

**Comment by luis100** [comment]
Is this done as a single column?

**Comment by luis100** [comment]
Now is done as a single column and also guards against `null` levels.
