### ISSUE TITLE
The METADATA XSLT should not display labels if no data is filled

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#235]
See example.
![screen shot 2016-03-04 at 14 25 57](https://cloud.githubusercontent.com/assets/3181302/13529623/205b53f2-e215-11e5-8325-6c7dc6519ac7.png)

**Comment by luis100** [comment]
I think normalize-space does what you want:

```xml
<xsl:if test="normalize-space(/text/p) != ''">
    ...
</xsl:if>
```

**Comment by sleroux-keep** [comment]
DC Stylesheet updated in 7cc19fc5502368453cf4b218cd86048ee389572b

**Comment by sleroux-keep** [comment]
I need samples of metadata (EAD-2002, EAD-3, EAD-C, DC) to verify the stylesheet (EAD and EAD3 schemas are "big", with a lot of possible repeated items... ):

I've already improved the stylesheets... But i need to test them with other examples...

**Comment by jmaferreira** [comment]
EAD-C you can find them on the old corpora.
All of the rest, I don't have.

**Comment by sleroux-keep** [comment]
Tested with examples from 

- http://eadiva.com/ead-samples-from-the-field/
- https://github.com/SAA-SDT/EAD3/tree/master/samples/ead3
- old corpora

(no empty labels, but may still need some fixes)
