### ISSUE TITLE
Remove zero hits facets from the sidebar

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#236]
See image.

![screen shot 2016-03-04 at 14 28 56](https://cloud.githubusercontent.com/assets/3181302/13529741/98368cca-e215-11e5-8ce7-c07fbf6e649b.png)

**Comment by luis100** [comment]
Need only to change `DEFAULT_MIN_COUNT` to `1` at:

https://github.com/keeps/roda/blob/c6a85210adcd10bb58899ab5674757fcf730eb9b/roda-common/roda-common-data/src/main/java/org/roda/core/data/adapter/facet/FacetParameter.java#L16

**Comment by vitorfernandes87** [comment]
Closed on fc319d2bebed6c9e6e82d51efc399f8b76af73de
