### ISSUE TITLE
Job and Report needed information

### ISSUE THREAD

**Issue by luis100** [keeps/roda#237]
Job:
 - items to be processed
 - items processed with success
 - items processed with failure

Report:
 - Currently running task (last started but not ended)
 - Status: running, success, failure
 - Progress: task 4 of 8

 In the job report (UI) show the currently running tasks and next tasks (waiting)

**Comment by hsilva-keep** [comment]
Done since 511e7756e4e6b4da6dbc031c05f9fa11733f2fd2. On purpose, next tasks are not set as that wouldn't be efficient.
