### ISSUE TITLE
There's duplicate code that should do the same but actually one version does more than the other

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#239]
The logic to index a preservation event is duplicated in https://github.com/keeps/roda/blob/f44ef8328ed169e63dd665b31abc78c195705f33/roda-core/roda-core/src/main/java/org/roda/core/index/IndexModelObserver.java#L87 and https://github.com/keeps/roda/blob/f44ef8328ed169e63dd665b31abc78c195705f33/roda-core/roda-core/src/main/java/org/roda/core/index/IndexModelObserver.java#L408 but the last one adds at least one more field to the created solrdocument.

**Comment by sleroux-keep** [comment]
Duplicate code remove with 1374b495fcb51442e5d258a5203d202e0d8b1647

**Comment by hsilva-keep** [comment]
I confirm that the duplicate code was removed. Also made some refinements in 6876085025ff48f9e90caf973565c968e97a01e4.
