### ISSUE TITLE
We should have a way to add DIPs manually

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#241]
My idea is to add an Edit button to the options associated to AIPs. It would open a folder navigation interface that would allow one to navigate trough the whole AIP. 

Additionally, It would also enable adding new DIP folders.

**Comment by hsilva-keep** [comment]
Aside from the fact that DIPs are in a different collection, creating DIPs manually makes sense. Still, more information is required on how to accomplish this task.

**Comment by hsilva-keep** [comment]
More detailed issue #672 exists, so I'm closing this one.
