### ISSUE TITLE
SIP ingested was not placed under the selected AIP

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#265]
Selected AIP:
http://192.168.2.19:8080/#browse/69df6b13-0c86-4143-af73-04fbec272d87

Ingested SIP: 
http://192.168.2.19:8080/#browse/427c4cd1-db58-47d8-b6c0-fc21cb089531

**Comment by hsilva-keep** [comment]
@jmaferreira You did't forced the attribution of the selected Parent AIP and the SIP had one defined but it doesn't exist. 
Should we, either forcing or not, in the case of a non existing Parent AIP (either because it was blank or it doesn't exist) use the one provided in the Job creation form?

**Comment by jmaferreira** [comment]
The AIP existed. I’ll do it again just to make sure.

**Comment by hsilva-keep** [comment]
@jmaferreira The one defined in the SIP (not the one you have chosen in the form).

**Comment by jmaferreira** [comment]
Ok. I’ve retested it.
	
The problem might be on the SIP it self as created by RODA-in. There was no indication on the UI of having an ascending AIP, however, according to the ingest process, there was that kind of information.

This is the info created by the RODA-in app:

    <structMap ID="582e0a47-6bc3-4405-8b34-c7fa30180e38" LABEL="RODA structural map">
        <div ID="bbb4126c-4766-4ffd-bc58-282299e66142" LABEL="RODA">
            <div ID="aebd8cc1-6930-45c1-bbb2-72ccfaad4c38" LABEL="Parent ID">
                <mptr xlink:type="simple" xlink:href="3bfd1f80-3d95-42b9-a8c7-85bf386a3282" LOCTYPE="HANDLE"/>
            </div>
        </div>
    </structMap>

**Comment by hsilva-keep** [comment]
@jmaferreira says that this is related to a bug from RODA-in and therefore I'm closing this one.
