### ISSUE TITLE
User actions on the UI that provoke a change on indexes to display info on the UI should force the commit on indexes

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#267]
Places where this happens:

- Transfer after upload
- Job list after create job

Alternatively, the balloons should say something about this delay.

**Comment by luis100** [comment]
A method to force the commit already exists and it was used for the detected points. There wasn't a complete analysis if this was done on all required places, but they will be done as they are found. Please create new issues if other places are found.
