### ISSUE TITLE
Make the AIP id visible on the UI

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#269]
See a suggested place in the image attached.
Drop the dates. Its repeated information anyway.

![screen shot 2016-03-21 at 22 21 51](https://cloud.githubusercontent.com/assets/3181302/13936139/8281c182-efb3-11e5-85a6-f68ae343a413.png)

**Comment by vitorfernandes87** [comment]
Closed on 65eda8f92071b10f04c057cb3f659120356a8f97
