### ISSUE TITLE
Create a plugin to erase old log entries

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#27]
The log tends to grow too much too fast.
Create a plugin that removes log entries older than N days.

Make sure the log is also saved to a text file.

**Comment by luis100** [comment]
Logs are now on the Solr search engine, still they may need to be removed.

**Comment by luis100** [comment]
Checkout this way: https://lucene.apache.org/solr/4_8_0/solr-core/org/apache/solr/update/processor/DocExpirationUpdateProcessorFactory.html

**Comment by hsilva-keep** [comment]
Solved in 58049bddc2ba169cbaa5becbca63eb9a16fa2e34. The plugin can be run via WUI (whenever an interface for creating/running misc jobs is created) or via management tasks REST API (which can be used via cronjob, and can be found in /api/v1/management_tasks/index/logclean). 
The plugin has a configuration in roda-core.properties to set the amount of days that log entries will be left in index (all the others are deleted) and can be overwritten via plugin parameters (and REST API params query parameter).
