### ISSUE TITLE
Remove from the UI the fields that are not filled on the PREMIS event viewer

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#270]
See attachment
![screen shot 2016-03-21 at 22 24 45](https://cloud.githubusercontent.com/assets/3181302/13936178/caa39a94-efb3-11e5-93f8-34fe51c4537d.png)

Delegate if necessary.

**Comment by sleroux-keep** [comment]
![event2](https://cloud.githubusercontent.com/assets/2727798/14389676/ae15f93e-fdab-11e5-95f6-d8bdb0a88589.png)
