### ISSUE TITLE
Outcome is not being presented on the PREMIS VIEWER

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#271]
This is just the most important piece of information in the whole record... :-/

See attachment
![screen shot 2016-03-21 at 22 27 31](https://cloud.githubusercontent.com/assets/3181302/13936258/4d9c33e8-efb4-11e5-8c2c-6eeacef0d518.png)

**Comment by sleroux-keep** [comment]
![event](https://cloud.githubusercontent.com/assets/2727798/14387875/45b61b7e-fda3-11e5-9f1f-82df623730a8.png)
