### ISSUE TITLE
Ingest plugins descriptions are not according to the spec defined on the EXCEL sheet and some tasks are missing

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#273]
See google drive for more info.
Additionally, I believe not all the tasks are visible on the UI, but they should be.
![screen shot 2016-03-21 at 22 41 34](https://cloud.githubusercontent.com/assets/3181302/13936550/4d51006a-efb6-11e5-943c-5e27ac16093b.png)

**Comment by hsilva-keep** [comment]
Related to #225.

**Comment by hsilva-keep** [comment]
Done in 5db2670a3d6446f5b5b41dcc96d5f5030aa4dea0.
