### ISSUE TITLE
Orthographic errors on controlled vocabulary

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#276]
Make sure this vocabulary is configurable.

See attachment.
![screen shot 2016-03-21 at 22 31 56](https://cloud.githubusercontent.com/assets/3181302/13965609/df3f6cf4-f066-11e5-865b-9c1316e0b400.png)

**Comment by jmaferreira** [comment]
Revise to:

getJobFunctions: Public service, Art and culture, Social care, Architecture and engineering, Commerce and services, Legal services, Financial services, Consulting services, Education, Research, Higher education, Industry, Creative industries, Social media, Information services

**Comment by vitorfernandes87** [comment]
The portuguese controlled vocabulary should be revised?

**Comment by vitorfernandes87** [comment]
English controlled vocabulary changed.

**Comment by jmaferreira** [comment]
Yes.
Accordingly.

**Comment by luis100** [comment]
Done
