### ISSUE TITLE
Make transfer folder indexing at request

### ISSUE THREAD

**Issue by luis100** [keeps/roda#281]
Constant monitoring is resource intensive, error-prone and ultimately not a requirement. Replace folder monitor feature by a scan at request feature.

On the transfer list interface a notice will appear:
**Last updated at 10 minutes ago. [update now]()**

On click a request will be made to the server to update re-index all (or only changed) data and the notice changes to:
**Last updated at 10 minutes ago. Updating...**

The back-end should have the following methods:
- Get last updated date and update status (i.e. if it is currently updating)
- Request an update, optionally selecting folder and if it is blocking (i.e. waits until it is updated)

**Comment by nunovieira220** [comment]
This feature was added and it is accessible via transfer page.
