### ISSUE TITLE
XML schemas could be cached

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#283]
Each time we want to validate an XML file against an XML schema, the schema is parsed and loaded into memory. Perhaps we could save some time, cpu and gc by caching the XML schemas.

**Comment by jmaferreira** [comment]
That approach has the disadvantage of not being able to update the schemas without turning off the repository.

**Comment by hsilva-keep** [comment]
That would be true if we did had already a strategy to reload internal state upon changes (we use it already for caching things like configurations, I18N, etc.), which fits perfectly for XML schemas cache.

**Comment by hsilva-keep** [comment]
Solved via fb9aed70386734d231d6b2f8d16bce515bd3e5c0
