### ISSUE TITLE
Add option to disable self register to RODA 5

### ISSUE THREAD

**Issue by hmiguim** [keeps/roda#2839]
https://github.com/keeps/roda/blob/77f4cf8dc25d2085665681a1c7a2acfee7c50c7c/roda-ui/roda-wui/src/main/resources/config/roda-wui.properties#L46

**Comment by 006627** [comment]
it is necessary to cherry-pick the RODA-4 [commit](https://github.com/keeps/roda/commit/9179f3af6a960384c4e402549764f32a1024c7e7) and test
