### ISSUE TITLE
Translate table headers and level (AIPList)

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/roda#286]
Currently, headers are hardcoded and level is displayed without translation.

**Comment by luis100** [comment]
Include BrowserMessages into the AIPList, add methods for each prefixed by `aipList` for example `aipListHeaderLevel`. Use the `DefaultMessage` annotation to add the default message which will be the same as the hard-coded one for now.

**Comment by jmaferreira** [comment]
Duplicated by #325
