### ISSUE TITLE
Update Apache Solr to version 7.x.x

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#287]

**Comment by jmaferreira** [comment]
This has VERY LOW priority.

**Comment by hsilva-keep** [comment]
No objection, I've just created the issue so this task is not forgotten.

**Comment by jmaferreira** [comment]
Excelent.

**Comment by luis100** [comment]
Started here, but got problems indexing Dates, because now it is using Java Instant.

https://github.com/keeps/roda/commit/03249e852c0641665e39b564395dc4b0fecdebe2

Also, due to dependency clash, needs #1014

**Comment by luis100** [comment]
Solr 7 has been released, now this is the target.

**Comment by jmaferreira** [comment]
This has VERY LOW priority. You may schedule this for version 3.0.
