### ISSUE TITLE
Getting NoSuchFileException while building roda-ui

### ISSUE THREAD

**Issue by jalshorji** [keeps/roda#2880]
When building roda-ui, I get NoSuchFileException on copying roda/roda-ui/roda-wui/src/main/resources/config/templates/ead.xml.hbs to target. However, I see that the filed i copied to target but still getting error. Any advise?

**Comment by luis100** [comment]
This may be due the current lack of support on the Maven latest version (3.9) to symbolic links in resources.
To [fix](https://github.com/keeps/roda/commit/52ca196d5183b24ffeb1cbc49daadbb247351611) it, we simply ditched the symbolic links and copied the files over.

This fix is included in the development branch, so can you test checking the test one? If not, you might consider downgrading Maven to version 3.8.
