### ISSUE TITLE
Issue running tests

### ISSUE THREAD

**Issue by jalshorji** [keeps/roda#2883]
Hello,

I get the following error when trying to compile with tests. 
Error executing command [sf, --version] - Cannot run program "sf": error=2, No such file or directory

Where is siegfries supposed to be running/installed?

**Comment by luis100** [comment]
You need to run it on the side with docker compose:
https://github.com/keeps/roda/blob/master/DEV_NOTES.md#debug-wui

**Comment by jalshorji** [comment]
I tried that, but it's checking for ${env:SIEGFRIED_MODE}. 
Siegfried is already running and I can run curl towards it.
