### ISSUE TITLE
Allow create risk incidents manually be selecting AIPs, representations or files

### ISSUE THREAD

**Issue by luis100** [keeps/roda#290]
Some risks can be added manually and the AIPs, representations and/or files that are affected can be selected manually to. This could be done by a final list of IDs or a filter that is more dynamic (can change through time).

**Comment by luis100** [comment]
@jmaferreira please review

**Comment by jmaferreira** [comment]
The association is working well, however the Remove incidence does not work. It outputs an error.

Additionally, the severity level that we associate to the incidence is not shown anywhere, but I guess this is on the scope of another issue.

**Comment by nunovieira220** [comment]
Removing incidences are now working well. The other new incidence actions will be associated with the #431 issue.
