### ISSUE TITLE
REST API endpoint to retrieve the last transferred resource report does not show the reports

### ISSUE THREAD

**Issue by hmiguim** [keeps/roda#2929]
Due to some changes in https://github.com/keeps/roda/issues/2058 the endpoint /api/v1/reporst/last is not working as intended. It should show the list of reports associated with the job.

**Comment by 006627** [comment]
https://github.com/keeps/roda/pull/2927

**Comment by hmiguim** [comment]
Close https://github.com/keeps/roda/releases/tag/v5.2.1
