### ISSUE TITLE
On the job report, show the plugin version

### ISSUE THREAD

**Issue by luis100** [keeps/roda#295]
For example, on the virus scan show the plugin as: `org.roda.core.plugins.plugins.antivirus.AntivirusPlugin@1.0`.

Also consider changing label "Plugin" to "Agent".

@hsilva-keep please check if the plugin version is available on the report and pass back to me to add it to the UI.

**Comment by hsilva-keep** [comment]
Done since f72e271c7ef43c47fbad2e3f25f0e7c9ab811563
