### ISSUE TITLE
It should be possible to start a job whose state is CREATED

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#297]
E.g. when the system is restarted and the job was only created (not started).
And it should be possible via web and REST interface.

**Comment by hsilva-keep** [comment]
@luis100 Just add the functionality in the interface, using method org.roda.wui.api.controllers.Jobs.startJob(RodaUser user, String jobId)

**Comment by luis100** [comment]
wontfix

This functionality has no impact as this state if very rare.
