### ISSUE TITLE
Adding new search field

### ISSUE THREAD

**Issue by jalshorji** [keeps/roda#2981]
Hi, 
I'm trying to add new search field and followed the documentation but I am getting this error. 

![Screenshot 2023-10-19 at 20 26 51](https://github.com/keeps/roda/assets/128469206/8fb3b3da-c012-43e4-b0aa-0ac3055ea2b8)

**Comment by luis100** [comment]
Solr indexing schema has [dynamic fields](https://solr.apache.org/guide/solr/latest/indexing-guide/dynamic-fields.html), which use suffixes for defining the data type of the indexed information.

Most common are *_txt for text to be stemmed, and *_ss for literal text, there are also other types for number, dates, etc.

For a complete list, check the RODA's default [managed-shema.xml](https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/resources/config/index/common/conf/managed-schema.xml).

So, if you rename your field from `caseEntityID`  to `caseEntityID_ss` it should work.
