### ISSUE TITLE
PREMIS object identifiers used to relate an object with another object are wrong

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#299]
Representation object:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<v3:object xsi:type="v3:representation" xmlns:v3="http://www.loc.gov/premis/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <v3:objectIdentifier>
    <v3:objectIdentifierType>local</v3:objectIdentifierType>
    <v3:objectIdentifierValue>OBJECT_REPRESENTATION:OBJECT_REPRESENTATION-fd0a8c40-ed5f-4154-98a9-6c9c6218c98f-rep1</v3:objectIdentifierValue>
  </v3:objectIdentifier>
  <v3:preservationLevel>
    <v3:preservationLevelValue/>
  </v3:preservationLevel>
  <v3:relationship>
    <v3:relationshipType>structural</v3:relationshipType>
    <v3:relationshipSubType>hasPart</v3:relationshipSubType>
    <v3:relatedObjectIdentifier>
      <v3:relatedObjectIdentifierType>local</v3:relatedObjectIdentifierType>
      <v3:relatedObjectIdentifierValue>OBJECT_FILE:OBJECT_FILE-fd0a8c40-ed5f-4154-98a9-6c9c6218c98f-rep1-201601_redmine_upgrade.txt</v3:relatedObjectIdentifierValue>
    </v3:relatedObjectIdentifier>
  </v3:relationship>
</v3:object>
```

File object:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<v3:object xsi:type="v3:file" xmlns:v3="http://www.loc.gov/premis/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <v3:objectIdentifier>
    <v3:objectIdentifierType>local</v3:objectIdentifierType>
    <v3:objectIdentifierValue>f7ccae68-f550-3dc6-864d-36edd70b9f67</v3:objectIdentifierValue>
  </v3:objectIdentifier>
  <v3:preservationLevel>
    <v3:preservationLevelValue>full</v3:preservationLevelValue>
  </v3:preservationLevel>
  <v3:objectCharacteristics>
    <v3:fixity>
      <v3:messageDigestAlgorithm>SHA-256</v3:messageDigestAlgorithm>
      <v3:messageDigest>7AE6EC3F650C48E65C62AAF140EA0C3E799B3EF18D7A173CB3A92C09D4AE8474</v3:messageDigest>
      <v3:messageDigestOriginator>RODA</v3:messageDigestOriginator>
    </v3:fixity>
    <v3:size>3170</v3:size>
    <v3:format>
      <v3:formatDesignation>
        <v3:formatName>Plain Text File</v3:formatName>
        <v3:formatVersion/>
      </v3:formatDesignation>
    </v3:format>
    <v3:format>
      <v3:formatRegistry>
        <v3:formatRegistryName>pronom</v3:formatRegistryName>
        <v3:formatRegistryKey>x-fmt/111</v3:formatRegistryKey>
      </v3:formatRegistry>
    </v3:format>
    <v3:format>
      <v3:formatRegistry>
        <v3:formatRegistryName>mime</v3:formatRegistryName>
        <v3:formatRegistryKey>text/plain</v3:formatRegistryKey>
      </v3:formatRegistry>
    </v3:format>
  </v3:objectCharacteristics>
  <v3:originalName>201601_redmine_upgrade.txt</v3:originalName>
  <v3:storage>
    <v3:contentLocation>
      <v3:contentLocationType/>
      <v3:contentLocationValue/>
    </v3:contentLocation>
  </v3:storage>
</v3:object>
```

**Comment by sleroux-keep** [comment]
Premis objects updated to URNs:
`<?xml version="1.0" encoding="UTF-8"?>
<v3:object xsi:type="v3:representation" xmlns:v3="http://www.loc.gov/premis/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <v3:objectIdentifier>
    <v3:objectIdentifierType>URN</v3:objectIdentifierType>
    <v3:objectIdentifierValue>urn:roda:premis:representation:b886f65d-7508-335d-94ce-9fc0675aa021</v3:objectIdentifierValue>
  </v3:objectIdentifier>
  <v3:preservationLevel>
    <v3:preservationLevelValue/>
  </v3:preservationLevel>
  <v3:relationship>
    <v3:relationshipType>structural</v3:relationshipType>
    <v3:relationshipSubType>hasPart</v3:relationshipSubType>
    <v3:relatedObjectIdentifier>
      <v3:relatedObjectIdentifierType>URN</v3:relatedObjectIdentifierType>
      <v3:relatedObjectIdentifierValue>urn:roda:premis:file:0cc9a19e-aa63-3b9a-8960-8ed7daf4fc93</v3:relatedObjectIdentifierValue>
    </v3:relatedObjectIdentifier>
  </v3:relationship>
</v3:object>`

`<?xml version="1.0" encoding="UTF-8"?>
<v3:object xsi:type="v3:file" xmlns:v3="http://www.loc.gov/premis/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <v3:objectIdentifier>
    <v3:objectIdentifierType>URN</v3:objectIdentifierType>
    <v3:objectIdentifierValue>urn:roda:premis:file:0cc9a19e-aa63-3b9a-8960-8ed7daf4fc93</v3:objectIdentifierValue>
  </v3:objectIdentifier>`

Template used:

urn:roda:premis:[file,representation,agent,...]:UUID

For LinkingObjects;
urn:roda:[aip, representation,...]:ID

**Comment by sleroux-keep** [comment]
The URN schema must also be used for RODA internal ids...

**Comment by luis100** [comment]
@hsilva-keep  please check if this issue is closed.

**Comment by hsilva-keep** [comment]
From the analysis I made, it looks good. Closing this issue.
