### ISSUE TITLE
Added permissions configuration for newly created AIPs

### ISSUE THREAD

**Issue by hmiguim** [keeps/roda#3032]
Currently when creating an AIP via Web User Interface or ingest, besides inheriting the permissions from the parent, it also adds the user itself with permissions for READ, UPDATE, CREATE and GRANT. As having user-specific permissions can be against institutional policy, we want to make this behaviour configurable:
1. Allow to set the permissions of the user that created the AIP. Allow it to be none, there is not adding the creating user at all (instead, we want to add a group).
2. Allow to set a list of groups with configurable set of permissions.
3. A requirement might be that the user that created the AIP must belong to one of the groups and it has READ and UPDATE permissions at least. If the intersection is empty, or generally, if the set permission ends up not providing the user with at least READ and UPDATE permissions to the created AIP, then these permissions must be added as user-level permissions to avoid unexpected errors.
4. An intersection of groups (groups of the user that created the AIP and groups in the configuration) might be required, specifically for multi-tenant situations. This behaviour could be optional.

**Comment by carlosjepard** [comment]
#3029
