### ISSUE TITLE
Create a new PluginParameterType with a controlled vocabulary

### ISSUE THREAD

**Issue by 006627** [keeps/roda#3049]
In some cases, the use of profiles is unfeasible and in order to continue to be user-proof, some parameters need to have a controlled vocabulary.

A new PluginParameterType must be created and the controlled vocabulary list must be configurable.

**Comment by AntonioG70** [comment]
Due to the complexity of implementation and the time it was taking, a decision was made to limit profile customization exclusively through the configuration settings.
