### ISSUE TITLE
Ingest fails to detect additional files in the representation folder that were not referenced in the METS.xml

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#307]
Corpora exists on .19. Check the "ingest test" excel for details.

**Comment by hsilva-keep** [comment]
That check is not currently being done as METS processing "mandates" that the <structMap> element is the one that declares the structure and content of the package. For doing that check, and besides the METS oriented processing, it would be necessary in the end to do the intersection of all the files processed through METS and the files inside the package in the filesystem. 
To be done correctly that's more 4 to 8 working hours. Should I proceed?

**Comment by hsilva-keep** [comment]
After this explanation, which @jmaferreira accepted verbally, I'm closing this issue.
