### ISSUE TITLE
Make ingest detailed report nicer to read.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#308]
There's a lot a redundant information, and information that doesn't add value.
Its a big mess... can´t we make it nicer? 

![screen shot 2016-05-09 at 22 03 26](https://cloud.githubusercontent.com/assets/3181302/15128198/4ad2cea2-1632-11e6-8869-fb18d3cc4bda.png)

**Comment by hsilva-keep** [comment]
Yes we can. Done since c1c620ba8c11be8cd12f84b3b21dc22235b3c354.

![captura de ecra de 2016-05-10 12 31 21](https://cloud.githubusercontent.com/assets/1315759/15145031/2ceffc24-16ab-11e6-997d-571be92bf686.png)
