### ISSUE TITLE
Create permission to list users and groups

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#311]
It is needed, for example, when a user with an AIP grant permission wants to add a new one and does not have 'administrator.user' permission.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep I think PR #396 also fixes this issue.
Assuming the method used to list users and groups is [UserManagement.findMembers(...)](https://github.com/keeps/roda/pull/396/files#diff-c7329ddce01e4c39daf6c49c17899939R117) is just necessary to define the desired role to property [core.roles.org.roda.wui.api.controllers.UserManagement.findMembers](https://github.com/keeps/roda/pull/396/files#diff-8b12f6f691aedbce8621d7a2a9b35bb1R99)
