### ISSUE TITLE
Question about Java library

### ISSUE THREAD

**Issue by jalshorji** [keeps/roda#3128]
What possibilities are there regarding the Java library? How does one import it? 
Is it possible for example to create/start job using java library instead of calling Rodas API?

I'm referring to documentation 'Convenient Java libraries are available on GitHub to allow developers to interact with RODA via its Core APIs.'

**Comment by luis100** [comment]
TL;DR I've loaded it into [SwaggerHub](https://app.swaggerhub.com/apis/keep.pt/roda-api/1.0.0), just select Export > Client SDK > your favorite language

---
RODA REST-API is specified using openapi:
https://demo.roda-community.org/api-docs/
https://demo.roda-community.org/api/openapi.json

You can generate code client in many programming languages with OpenAPI client generators:
https://swagger.io/tools/swagger-codegen/
https://github.com/swagger-api/swagger-codegen
https://github.com/OpenAPITools/openapi-generator
https://openapi-generator.tech/
