### ISSUE TITLE
AIP File download - REST AIP for RODA - v1 files

### ISSUE THREAD

**Issue by arbabhamd** [keeps/roda#3134]
I am working on Roda intergration with my project using the public APIs. I want to download files that are added in an AIP. Like how the files are listed in roda aip representation screen, we can click on files which opens the file and then there is an option to downoad from there. Is there any API that can give the same functionality?

**Comment by luis100** [comment]
Yes, you should look into the File resource. It format should be bin to get the binary. To find the uuid you should use the index resource.
