### ISSUE TITLE
Preservation actions interface and backend

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#315]
Preservation actions page can list all processes that are not ingest.

**Comment by jmaferreira** [comment]
TODO:

- Isolate plugins in independent jars
- Show on UI only the plugins that have been tested

Plugin properties:

- Domain (AIP, Representation, File, Transferred resources, etc.)
- Type (SIP to AIP, AIP to AIP, Ingest, Misc, etc.)
- [NEW] Categories (Format conversion, Characterisation, Format validation, Risk management, Feature extraction, Format identification, etc.)

UI:

- Additional combo with the categories to filter plugins.

**Comment by luis100** [comment]
All done except plugin isolation, which as moved to #363.
