### ISSUE TITLE
Add a generic method to the list table to download the itens in the list in CSV (all pages)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#319]
Pretty much the same way Redmine allows you to download a list of your search results.

**Comment by luis100** [comment]
@chalkos please point to similar code in db-visualization-toolkit that can serve as inspiration

**Comment by luis100** [comment]
This should be done in `IndexResource` REST API, for GET and POST find methods.
A accept header can be used to activate the feature.

On the client, a button can be used to download, calling a method that uses RequestBuilder to send a POST request to REST API and defined the HTTP headers.

http://www.gwtproject.org/doc/latest/DevGuideServerCommunication.html#DevGuideHttpRequests

Pass this to me when the method exists, so I can create this button(s).

**Comment by chalkos** [comment]
The method to get the results from Solr as CSV is at https://github.com/keeps/db-visualization-toolkit/blob/1e001ac09683a35328455416376ad7a0fc7fbc6b/dbvtk-model/src/main/java/com/databasepreservation/visualization/utils/SolrUtils.java#L343

The main part is

```
QueryRequest queryRequest = new QueryRequest(query);
queryRequest.setResponseParser(new InputStreamResponseParser("csv"));
QueryResponse response = queryRequest.process(index, collection);

Object stream = response.getResponse().get("stream");
if (stream instanceof InputStream) {
  return (InputStream) stream;
}
```

That uses an `InputStreamResponseParser` which internally makes Solr ask for results in CSV. The result contains a stream that can be used to read the CSV (as plaintext).

My problem did not include faceting, I don't know if or how that is returned in Solr, but that can easily be tested on a web browser using the get parameter asking for a CSV response instead of JSON (i.e. wt=csv), see https://cwiki.apache.org/confluence/display/solr/Response+Writers

**Comment by rui-castro** [comment]
@chalkos did you use the CSV feature with [embeded solr server](http://lucene.apache.org/solr/5_5_1/solr-core/org/apache/solr/client/solrj/embedded/EmbeddedSolrServer.html) or just with the HTTP version?

**Comment by chalkos** [comment]
I used it with the HTTP version.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #558 

To produce CSV in `/index` requests, simply use header 
`Accepts: text/csv`

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep support for facet data complete

### Results in CSV
#### Request
```
GET http://127.0.0.1:8888/api/v1/index?
  returnClass=org.roda.core.data.v2.user.RODAMember
```
#### Response
```csv
id,isActive,isUser,name,fullName,email,groups
rui,true,true,rui,Rui,rui.castro@gmail.com,[users]
guest,true,true,guest,Guest,demo-guest@roda-community.org,[guests]
producers,true,false,producers,Producers,,
users,true,false,users,Users,,
archivists,true,false,archivists,Archivists,,
administrators,true,false,administrators,Administrators,,
guests,true,false,guests,Guests,,
admin,true,true,admin,Administrator,demo-admin@roda-community.org,"[guests, archivists, administrators]"
```

### Facets in CSV
#### Request
```
GET http://127.0.0.1:8888/api/v1/index?
  returnClass=org.roda.core.data.v2.user.RODAMember&
  facet=isUser&
  facet=isActive
```
#### Response
```csv
field,label,value,count
isUser,false,false,5
isUser,true,true,3
isActive,true,true,8
```

**Comment by luis100** [comment]
checked and integrated a2c96ffe0de60d057bf1868ea24df22e72b5d2d9

**Comment by luis100** [comment]
works, but now needs the button to download on the UI.

**Comment by rui-castro** [comment]
@luis100 you said 

> Pass this to me when the method exists, so I can create this button(s).

**Comment by jmaferreira** [comment]
This has already been done.
