### ISSUE TITLE
Add index methods in REST API

### ISSUE THREAD

**Issue by luis100** [keeps/roda#323]
Support `find`and `count` in REST APIs.

Add a new `Index` resource that allows to use the full potential of the already existing find and count methods. Create new `FindRequest` and `CountRequest` classes that have all necessary arguments for find and count, respectively. Add POST methods that receive the requests and returns the `IndexResult`.
```
POST /api/index/find
{
  returnClass: AIP,
  filter: {...},
  sorter: {...},
  sublist: {...},
  facets: {...}
}
```
Also, add simplified versions of find and count that use GET methods to make simple searches, like search in a field (using `SimpleFilterParameter`).

```
GET /api/index/find/aip/?originalId=1234&title=my+title`
```

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #480 
It's only the first version, but I would like to have some feedback.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep I updated my PR #480. It should have all find/count functionalities.
The GET version only allows simple filters (a=1) and simple facets.
The POST version allows everything supported by **Browser#find** method.

**Comment by hsilva-keep** [comment]
@luis100 @jmaferreira the pull request associated with this issue has been integrated (#480). Anything missing?

**Comment by luis100** [comment]
Tested examples and it works properly.
