### ISSUE TITLE
File format identification manual override

### ISSUE THREAD

**Issue by hmiguim** [keeps/roda#3256]
The automatic file format identification tools provide a very accurate result for well-designed file formats that properly identify themselves, but that is not the case for every file format. For many formats, the identification tool has to guess the format based on heuristics. This sometimes creates a misidentification of file formats, which will stand out when the identified format is outside of the accepted policy.

When such a case happens, a validation of the file format would first need to happen. In case a misidentification is confirmed, there is currently no easy way to fix it manually.

In this task, we propose a new feature to manually set the file format information on the Web user interface.

**Comment by SugaryLump** [comment]
Feature implemented as an internal plugin (`EditFileFormatPlugin`) in https://github.com/keeps/roda/pull/3255
