### ISSUE TITLE
Statistics and reporting engine

### ISSUE THREAD

**Issue by luis100** [keeps/roda#326]
Allow to create graphics based on find with filter / facets results. Have a REST API that produces content in a format (e.g. CSV) that is ready to be consumed by a client-side chart library (like highcharts). Make some examples on how to use it to produce charts (e.g. mime type charts).

Use the theme mechanism to create a template page for the statistics.
Look into ./config/theme/help.html for inspiration

**Comment by jmaferreira** [comment]
Top javascript charting libraries:
- https://www.sitepoint.com/15-best-javascript-charting-libraries/
- It needs to be open source.

**Comment by jmaferreira** [comment]
Examples of statistics:

# AIP Index

- Total No. of descriptive records
- Total No. of fonds

- Distribution of description levels (pie or bars)

# Representations Index

- Total No of Representations
- Distribution of representation types (pie or bars)

# Files index

- Total No. of files
- Distribution of mimetypes (pie or bars)
- Distribution of PRONOM IDs (pie or bars)
- Distribution of MB per mime type (bars)

# IngestJob index

- Total No of Ingest jobs
- Min, max and Average ingest time

#Users and groups index

- Total No. of users
- Distribution of number of users per group (Pie or Bars)

#Log index

- Total No of logins
- Total No of failed logins

**Comment by jmaferreira** [comment]
More statistics available at:

http://demo.roda-community.org/?locale=en#administration.statistics

**Comment by jmaferreira** [comment]
Use the static page that @vitorfernandes87 is going to create for you on  #463

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #480
It's only the first version, but I would like to have some feedback.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep updated PR #481 with many new features.
The engine is fully implemented on the client side.
For more complex statistics server side services would need to be developed.

**Comment by hsilva-keep** [comment]
@luis100 @jmaferreira the pull request associated with this issue has been integrated (#481). Anything missing?

**Comment by jmaferreira** [comment]
No. I don’t think so.

**Comment by luis100** [comment]
Note that the selected chart js library is a bit limited, without, for example, horizontal bar charts, which would be needed for statistics like the file format distribution, on big repositories with thousands of different formats.

Nevertheless, this issue resolution will be accepted as is for now, other issues might be created in the future when new needs are found.
