### ISSUE TITLE
TLS-support for Roda

### ISSUE THREAD

**Issue by SebastianThorn** [keeps/roda#3279]
Hi,

Is TLS supported by Roda?
Or is a 3rd party proxy is required?

I can't seem to find any documentation on how to apply a certificate for TLS communications.

Br Sebastian Thörn

**Comment by luis100** [comment]
Hello, in a Docker setup we would usualy use Traefik for HTTP router and SSL termination.

https://doc.traefik.io/traefik/getting-started/install-traefik/

Internally, RODA 5 Docker image uses Apache Tomcat which can also be setup for SSL termination.
