### ISSUE TITLE
Cross-AIP relationships via search request

### ISSUE THREAD

**Issue by luis100** [keeps/roda#329]
Allow a new guest-side search method to allow relationships via search fields. For example `#search/aip/field/value`.

Make an example to allow an relationship present in original data to be followed. One document has in metadata a relationship with another via an original id, the original id is indexed as `originalId`, and the HTML stylesheet shows this relationship as a link to `#search/aip/originalId/1234`.

**Comment by luis100** [comment]
Needs now an option to jump directly to the result if it is only one.

**Comment by vitorfernandes87** [comment]
Added a Relation class to jump directly to the result if it is only one.
Closed on 0af2128a172269fa19d8c72c50ee1c29a1e9b325
