### ISSUE TITLE
Representations list, view metadata and edit files

### ISSUE THREAD

**Issue by luis100** [keeps/roda#330]
- [x] In browse on an AIP show the list representations with information about type, size, and number of files. 
- [x] Allow to add a new (empty) representation
- [ ] When viewing a representation, allow to add or delete files or folders (reuse existing upload panel)
- [x] Allow to view the representation descriptive metadata (using the same components as the AIP descriptive metadata)
- [x] Allow to delete a representation (on the AIP view or when viewing a representation that is empty)

**Comment by vitorfernandes87** [comment]
@luis100 please review the developments done.
The file and folder upload/remove should be done in the next version (maybe v2.1).

**Comment by luis100** [comment]
Checked.

Moved file/folder edition to #609
