### ISSUE TITLE
Representation Information AIP

### ISSUE THREAD

**Issue by luis100** [keeps/roda#331]
Add a new AIP type `RepresentationInformation`. Create schemas for metadata. Allow to link files with certain mime types or pronom IDs to AIPs of `RepresentationInformation` that represent the specific formats.

Segregate AIPs in Catalogue and Search (i.e. hide) and have a new option in Search to search on Representation Information AIPs.
# Representation Information Subtypes
## Structure Information (from OAIS)
- PRONOM-Report (search for XSD)
- Are there other XML based registries?
## Semantic Information (from OAIS)
- XHTML (for free use. Try to use modular XSD to impose restrictions on the tags that can be used, e.g. javascript should not be available. Only structural and visualisation elements)
## Representation Rendering Software (from OAIS)
- I don’t thing there will be a XSD for this. We can build our own based on the information we can collect.
## Access Software (from OAIS)
- Intrinsic. According to OAIS these are the integrated viewers and their source code.

**Comment by luis100** [comment]
@jmaferreira please make the design of necessary changes, e.g. AIP type, aip.json relationships, and design of the interface changes.

**Comment by jmaferreira** [comment]
My work here is done. Assign to someone to be developed.

**Comment by luis100** [comment]
This needs to be divided into small issues.

**Comment by jmaferreira** [comment]
Done.
