### ISSUE TITLE
Index preservation agents

### ISSUE THREAD

**Issue by luis100** [keeps/roda#339]
When re-indexing AIPs, preservation events are being re-indexed, but the repository-wide preservation agents they refer are not indexed.

As a consequence, when re-indexing the repository, preservation agents are not indexed, and when creating a new event that refers this preservation agent, it will not be created (as file already exists) and will not be indexed again, making a situation that will result on agents never being indexed.

**Comment by nunovieira220** [comment]
Everytime a reindex of AIPs is executed, it automatically reindexes the preservation agents.
