### ISSUE TITLE
Changing password in profile makes user loose all groups and permissions

### ISSUE THREAD

**Issue by luis100** [keeps/roda#348]
When the admin tries to change password on Profile (not on User management), it will loose all permissions or groups it belongs to.

Also, if the admin has full name and document id, necessary to change password (see #335), it will not show up in the Profile.

**Comment by rui-castro** [comment]
Is not clear if this happens for all users or just the admin. It's necessary to check that.

**Comment by luis100** [comment]
Link to profile #profile, link to user management #administration/user

It may happen to other users, didn't check.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check PR #411.
This solves the problem is changing admin password.
For the other users, first it's necessary to fix #409 and #410. After these are fixed it will be easy to see if there's a problem changing passwords.

**Comment by rui-castro** [comment]
Create a new user to manage LDAP that should be different from admin.
The new user should not be visible in interface.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #429 with a fix for this issue.

**Comment by rui-castro** [comment]
@luis100 ping

**Comment by luis100** [comment]
Just tested and changing the admin password makes it loose all roles.

**Comment by luis100** [comment]
Fixed 2037238673bcb019afba9df1a55dfa65c0b3b6c0
