### ISSUE TITLE
Deactivate included ingest workflows

### ISSUE THREAD

**Issue by luis100** [keeps/roda#358]
Having included ingest workflows (configurable and minimal) is convenient for new installations, but there should be a way to hide these default ingest workflows in production systems.

This could be done with a configuration in `roda-core.properties`.

**Comment by luis100** [comment]
The same any other included plugin, like the SIP to AIP plugins, clamav virus check, siegfried, etc.

**Comment by hsilva-keep** [comment]
Done since b54c5ea17c27ff03a3522f13671261cd48b8e894 (even if a typo existed and fix was introduced later in b2b9a4f36e649b09afb9fcdc9916ba5ab7c3cf85).
