### ISSUE TITLE
File advanced search should allow search by two PRONOM ids

### ISSUE THREAD

**Issue by luis100** [keeps/roda#359]
For example, search for files that have PRONOM id "fmt/101" or "fmt/102".

This could be done by allowing to add more PRONOM field filters, such like in AIP advanced search, but this repetition should be a OR and not an AND.

**Comment by jmaferreira** [comment]
I think we can assume terms in the same textbox to be separated by ANDs and if we repeat a given atribute/textbox then these will be separated by OR.

**Comment by luis100** [comment]
@jmaferreira yes, that is a good approach, but right now the file advanced search fields, like pronom, cannot be repeated (so that's one task). Nevertheless, the logic of OR in separated fields and AND in the same could be applied to all advanced search fields.

**Comment by luis100** [comment]
Blocked by #428.

**Comment by vitorfernandes87** [comment]
Closed on 30ecb3b111a3faf9de85436dfadbd769f6e61348
