### ISSUE TITLE
AIP.json additional fields

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#364]
AIP.json should support the following extra fields in a backwards compatible way:

```
format: {
  name: "EARK",
  version: "1.0"
},
relationships: [
  relationship: {
      relationType: "SEMANTIC"
      relationName: "isPartOf",
      relatedObject: "4321"
  }, relationship: {
      relationType: "SEMANTIC"
      relationName: "references",
      relatedObject: "4321"
  }, relationship: {
      relationType: "REPRESENTATION_INFORMATION"
      relationName: "interpretedUsing",
      relatedObject: "23"
} ]
```
Check http://dublincore.org/documents/rdf-relation-types/

# Control fields

In order to support the future development of OAI-PMH interfaces it is fundamental that we also record the following data:

- createdOn
- createdBy
- updatedOn
- UpdatedBy

And support a **deleted** status

**Comment by nunovieira220** [comment]
Additional fields added to AIP.
