### ISSUE TITLE
Review authorization roles

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#380]
All roles need to be reviewed and associated with the specific methods.
It may be necessary to create new roles.

**Comment by luis100** [comment]
https://github.com/keeps/roda/tree/c959e09971d1804e32dfc1e7134c971f62f48b3d/roda-ui/roda-wui/src/main/java/org/roda/wui/api/controllers

**Comment by luis100** [comment]
https://docs.google.com/spreadsheets/d/1IKFZ5vd6TqfcbnSKkIWjp0QY4RtM2BKZpLh_MlrCXJo/edit?usp=sharing

**Comment by luis100** [comment]
Possibly use a properties config file which would have the method and the list of roles it needs.

```
org.roda.wui.api.controllers.Browser.getItemBundle: BROWSE
org.roda.wui.api.controllers.Browser.getItemBundle: EDIT
```

Check if reflection works here:
```
String name = new Object(){}.getClass().getEnclosingMethod().getName();
```

Use the following method to get config file.

https://github.com/keeps/roda/blob/c959e09971d1804e32dfc1e7134c971f62f48b3d/roda-core/roda-core/src/main/java/org/roda/core/RodaCoreFactory.java#L914

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep Please check my PR #396

**Comment by rui-castro** [comment]
Document https://docs.google.com/spreadsheets/d/1IKFZ5vd6TqfcbnSKkIWjp0QY4RtM2BKZpLh_MlrCXJo/edit?usp=sharing was also updated with methods and respective roles.

**Comment by rui-castro** [comment]
@luis100 @jmaferreira Document https://docs.google.com/spreadsheets/d/1IKFZ5vd6TqfcbnSKkIWjp0QY4RtM2BKZpLh_MlrCXJo/edit?usp=sharing was updated with new methods.

**Comment by rui-castro** [comment]
Done
