### ISSUE TITLE
Import to LDAP new roles from configuration file

### ISSUE THREAD

**Issue by luis100** [keeps/roda#381]
The roles that are defined at #380 should be loaded into the system on boot.

https://github.com/keeps/roda/blob/c959e09971d1804e32dfc1e7134c971f62f48b3d/roda-core/roda-core/src/main/java/org/roda/core/RodaCoreFactory.java#L745

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #397

**Comment by hsilva-keep** [comment]
Tested, merged into master.
