### ISSUE TITLE
Use Apache DS directly

### ISSUE THREAD

**Issue by luis100** [keeps/roda#382]
Right now RODA is using Apache DS to create an LDAP server and exposing it via a network port in the web.xml and then using old code to connect to the LDAP server and provide all features.

Change this to access Apache DS directly.

**Comment by rui-castro** [comment]
LdapUtility methods should be reimplemented to use ApacheDS classes.
ApacheDS should not run as a service.

**Comment by rui-castro** [comment]
This issue is still not ready. 
Need 1 day more of testing and bug fixing.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep Take a look at my PR #469
