### ISSUE TITLE
Investigate strategies to enable support for external authentication via CAS

### ISSUE THREAD

**Issue by luis100** [keeps/roda#383]
Via configuration enable CAS authentication. If enabled, instead of using internal login (#login) it will redirect to the external service. On the callback, check if received user exists and if it doesn't create it in Apache DS.

Also review authentication in REST to make it work with the CAS service.

**Comment by luis100** [comment]
CAS filters are defined here (commented): https://github.com/keeps/roda/blob/c959e09971d1804e32dfc1e7134c971f62f48b3d/roda-ui/roda-wui/src/main/webapp/WEB-INF/web.xml

RODA authentication filters are here:
https://github.com/keeps/roda/tree/c959e09971d1804e32dfc1e7134c971f62f48b3d/roda-ui/roda-wui/src/main/java/org/roda/wui/filter

**Comment by rui-castro** [comment]
https://wiki.jasig.org/display/CAS/Home

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep @jmaferreira 

Apache Shiro is a framework to implement security (authentication, authorization, session management, etc) in java applications. It doesn't fit out purpose.

CAS is a single sign-on solution and it fits the desired purposes; single point of authentication and integration with [multiple backend systems](https://wiki.jasig.org/display/CASUM/Authentication).
There are several [implementations of single sign-on](https://en.wikipedia.org/wiki/List_of_single_sign-on_implementations). 

I think CAS is the way to go.

**Comment by luis100** [comment]
@rui-castro thank you for your analysis. Please look now how we can implement this in a configurable way, i.e. without having to recompile the application or change files inside the WAR application.

**Comment by luis100** [comment]
I supose the last request would be equivalent to #539, so I'm closing this for now.
