### ISSUE TITLE
Initialize risks, formats and example AIPs

### ISSUE THREAD

**Issue by luis100** [keeps/roda#384]
When starting up, check if risks are empty and if so copy over default risks (that are now on the risks orphan branch and should be removed after this). Do the same for formats (that are on the formats orphan branch).

Also, add some example AIPs with RODA documentation.

After adding a re-index should be called.

**Comment by nunovieira220** [comment]
Default risks, formats and AIPs with RODA documentation are automatically added when RODA initializes.
