### ISSUE TITLE
Aggregate all install artifacts in roda-installer

### ISSUE THREAD

**Issue by luis100** [keeps/roda#385]
Create (or re-activate) roda-installer project which should aggregate all install artifacts, e.g. roda-wui.war and all plugins. It should also have a profile to create the docker container based on the aggregated artifacts.

**Comment by luis100** [comment]
Postponed until real world cases demands it.

**Comment by hsilva-keep** [comment]
This no longer applies as now the "installer" is the RODA docker image. 
Closing issue without further actions.
