### ISSUE TITLE
Ingest plugin that moves successfully ingested SIPs to a special folder under the transferred-resources folder

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#388]
Example:
/ingested-sips/2016-06-07/*

**Comment by jmaferreira** [comment]
Assign to the right person, please.

**Comment by hsilva-keep** [comment]
We should have three properties containing the name of the folders to where the SIPs should be moved:
* PROCESSED/SUCCESSFULLY_INGESTED
* PROCESSED/UNDER_APPRAISAL
* PROCESSED/UNSUCCESSFULLY_INGESTED
An extra property should exist to activate/deactivate this behavior.

**Comment by hsilva-keep** [comment]
Almost done (since 22c3d68f503aa90d85aa7f6f4b9ff755326a8a8c). The only part missing is using the relative path of the transferred resource also in the target.

**Comment by hsilva-keep** [comment]
Update to my previous comment: that is done since b8cd7c646eaa63d7a1dc984780704af08af2033d and therefore I'm closing this issue.
