### ISSUE TITLE
Premis files and risk files when stored on disk on a Mac replace ":" with "/"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#407]
See example attached.
![screen shot 2016-07-14 at 18 10 18](https://cloud.githubusercontent.com/assets/3181302/16848576/46d634f2-49ee-11e6-8a02-7d0c71afe961.png)

**Comment by jmaferreira** [comment]
Apparently on the Mac this is not an issue. Mac loads the filenames correctly.

**Comment by hsilva-keep** [comment]
Just for posterity, this happened when running RODA through docker. Running RODA directly on Mac using Tomcat does not raise the reported behaviour. Which makes me believe that this is a docker related "problem".
