### ISSUE TITLE
User registration form is losing information

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#409]
Some information entered in user registration form is not being stored in LDAP.

## Steps

1. Goto "Sign up" page (page title is "RODA - REGISTER")
2. Enter all mandatory fields and press "SIGN UP" button
3. A message appears saying the registration was successfull.
4. Login with admin, go to "Administration -> Users and groups" and select the new user.

## Results
Some fields are missing (Area of activity, Document of identification type, Date and Local of issue type)

**Sign up form**
![screenshot from 2016-07-15 12 33 49](https://cloud.githubusercontent.com/assets/4218366/16873325/60b2c3bc-4a8a-11e6-8ab8-7f24d2f3640f.png)

**LdapUtility#addUser user parameter**
![screenshot from 2016-07-15 12 34 25](https://cloud.githubusercontent.com/assets/4218366/16873351/916f2bc6-4a8a-11e6-8b89-98622a7b2f57.png)

**LDAP record**
![screenshot from 2016-07-15 12 58 15](https://cloud.githubusercontent.com/assets/4218366/16873543/f741f13a-4a8b-11e6-8244-81eb009fbab6.png)

**Administration -> Users and groups -> ruicastro**
![screenshot from 2016-07-15 12 36 39](https://cloud.githubusercontent.com/assets/4218366/16873342/752a210a-4a8a-11e6-92f4-4253b1fa91f3.png)

**Comment by jmaferreira** [comment]
I guess this will be solved by @rui-castro . Assign to the right person please.

**Comment by jmaferreira** [comment]
This issue will be fixed magically by #414
