### ISSUE TITLE
User profile page is only showing username and email

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#410]
The user profile page is only showing fields `username` and `email`.

## Steps

1. Register a new user with all mandatory fields
2. Login with that user
3. Goto profile page (/#profile)

## Result

Only the `username` and `email` fields have information.

**User registration form**
![screenshot from 2016-07-15 12 33 49](https://cloud.githubusercontent.com/assets/4218366/16873502/b05543b2-4a8b-11e6-8a5f-98fe4ba24fa2.png)

**LDAP record**
![screenshot from 2016-07-15 12 58 15](https://cloud.githubusercontent.com/assets/4218366/16873524/dba5ab60-4a8b-11e6-8c5e-b177f18295e9.png)

**User profile page**
![screenshot from 2016-07-15 12 36 39](https://cloud.githubusercontent.com/assets/4218366/16873488/8930fa7e-4a8b-11e6-8845-e7f767e08dee.png)

**Comment by jmaferreira** [comment]
Assign to someone please.

**Comment by luis100** [comment]
This relates to #448

**Comment by luis100** [comment]
Actually, it doesn't relate to #448 but to the fact that profile users RodaUser instead of User. Solution is to merge both classes into a single one.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep created PR #484 that should fix this issue.

**Comment by luis100** [comment]
Now problem relates to the not execution of the template system in the specific method that allows a user to change its own information. Assigning @nunovieira220

**Comment by luis100** [comment]
Fixed at 829255445b66a759631e7e01ad4f16a4adf1536f
