### ISSUE TITLE
UserUtility.checkRoles() should receive the roda object class 

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#412]
UserUtilityu.checkRoles should receive the roda object class  to distinguish permissions for different types of objects.
<T extends IsRodaObject> checkRoles(RodaUser user, String declaringClass, String methodName, Class<T> clazz)

roda-roles.properties change syntax to
roda.role.org.roda....Browser.find(IndexedAip) = browse.aip

**Comment by luis100** [comment]
@rui-castro what is the status of this one?

**Comment by rui-castro** [comment]
@luis100 picking this as soon as possible.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #473

**Comment by hsilva-keep** [comment]
Merged into my branch & it will be merged into master until the end of the week.
