### ISSUE TITLE
If user is not active and tries to login, a more clearer message should be presented 

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#413]
ATM, when an inactive user tries to login, a message of "invalid username or password" is presented. This is caused by throwing the wrong exception when verifying if user is inactive. 
Also, this message should put available the option of resending the activation link (this functinality does not exist).

**Comment by rui-castro** [comment]
@hsilva-keep @luis100 Check my PR #413
**2 notes regarding this PR:**
1. What should I do regarding the missing functionality to resend the verification email? 
 Should I create a new issue for that feature?
 Should I implement it in the context of this issue? I don't have experience with GWT so it may take me a while to do it.
2. The message in [ClientMessages_es_CL.properties](https://github.com/rui-castro/roda/blob/b4abfe13329064c3ee020c59375424bf23ffa6f0/roda-ui/roda-wui/src/main/resources/config/i18n/client/ClientMessages_es_CL.properties#L650) came from Google translate!

**Comment by luis100** [comment]
1. Create a new issue
2. No problem, but now we use transifex client to manage translations (see README.md). If you don't want to manage the translations update, always warn me whenever translations are changed.

**Comment by rui-castro** [comment]
@luis100 
1. Issue #434 created.
2. I don't want to manage the translations update :) the new message is [here](https://github.com/rui-castro/roda/blob/rcastro_413_user_not_active_message/roda-ui/roda-wui/src/main/java/config/i18n/client/ClientMessages.java#L1229)

**Comment by luis100** [comment]
@rui-castro tests showed that a de-activated user login in is presented with an error message saying "Wrong username or password", which was the problem detected.

**Comment by rui-castro** [comment]
@luis100 https://github.com/keeps/roda/pull/433#issuecomment-234623449

**Comment by luis100** [comment]
Version tested deployed was after the pull-request was merged, but only tested now.

**Comment by luis100** [comment]
In fact comment: 

> User with email verified but inactive, on login atempt will see message "Wrong username or password", as it was before.

Shows solution does not solve this issue as requested.

> ATM, when an inactive user tries to login, a message of "invalid username or password" is presented. This is caused by throwing the wrong exception when verifying if user is inactive.

**Comment by rui-castro** [comment]
@luis100 what is the expected behaviour?

**Comment by luis100** [comment]
1. User found, password correct, active, email verified: login
2. User found, password correct, active, email not verified: Cannot login, show error "Email not yet verified", have an option to resend the email #434 
3. User found, password correct, inactive: Cannot login, show error "Your user was deactivated, please contact the administrator"
4. User found, password incorrect: show error "User not found or incorrect credentials" 
5. User not found: show error "User not found or incorrect credentials"

**Comment by luis100** [comment]
@rui-castro what is the status of this one?

**Comment by rui-castro** [comment]
@luis100 picking this later today

**Comment by rui-castro** [comment]
@luis100 check my PR #472

**Comment by hsilva-keep** [comment]
Merged into my branch & it will be merged into master until the end of the week.
