### ISSUE TITLE
Add extra field to User to contain xml with user attributes

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#414]
Remove all fields from User and,
add field User#extra.

**Comment by jmaferreira** [comment]
This issue blocks #448

**Comment by rui-castro** [comment]
This issue is still not ready. 
It's currently blocked by #382.

**Comment by luis100** [comment]
No longer blocked.

**Comment by rui-castro** [comment]
@luis100 working on this now

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #471

**Comment by luis100** [comment]
merged

**Comment by luis100** [comment]
To note that the profile doesn't show saved fields, due to #410
