### ISSUE TITLE
Add state attribute to LogEntry

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#415]
* State: SUCCESS, UNAUTHORIZED, FAILURE
* Change index accordingly
* RodaCoreService helper methods should be extended

**Comment by hsilva-keep** [comment]
Done all over the code except in GWT since a33fbdfc571c303c781dab48cefa7e0e097dc758. @luis100 you're next bringing that new attribute up to GWT.

**Comment by vitorfernandes87** [comment]
Closed on ad28dbf616adaf563e7685df11f9be8dc9a868e5
