### ISSUE TITLE
Create a OrFilterParameter that represents the union of two or more filter parameters 

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#428]
This development is needed when we are doing an advanced search with multiple atributions of the same field.

![example](https://cloud.githubusercontent.com/assets/8982932/17030820/3eea712e-4f69-11e6-9b2f-6784d8e6bf35.png)

In this example it should display only the intellectual entities with 'Curadoria*' OR 'SCAPE*'.

**Comment by jmaferreira** [comment]
The only thing missing is a clear way to explain the user that the OR operator is being used.

**Comment by vitorfernandes87** [comment]
Closed on 30ecb3b111a3faf9de85436dfadbd769f6e61348
