### ISSUE TITLE
Add more info to Risk incidence

### ISSUE THREAD

**Issue by luis100** [keeps/roda#431]
* **Status**: Unmitigated, Mitigated, Accept risk, False positive
* **Severity**: the severity of the incidence (use same levels as in the Risk entity)
* **Who detected:** which person or plugin created the incidence
* **When was detected**: the date when the incidence was created
* **Who mitigated**: which person or plugin who resolved the incidence
* **When was mitigated**: the date when the incidence was resolved
* **How it was mitigated**: a text field with the explanation of how the incidence was resolved
* **Why/note**: a text field with the explanation of why the incidence was created

Add this to the list of incidences, which should jump to a page that details the incidence (instead of going to the AIP).

The AIP should jump to the list of incidences and not the list of risks. Remove the BrowserService#getRiskOnAIP() method.

**Comment by nunovieira220** [comment]
All the risk incidence actions were added.
