### ISSUE TITLE
Implement functionality to re-send email verification message

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#434]
## Description

Implement functionality to re-send email verification message and update [inactive user message](https://github.com/keeps/roda/blob/lf_dev/roda-ui/roda-wui/src/main/java/config/i18n/client/ClientMessages.java#L1255) to include a link/button to resend the verification email.

The message could be something like:

You must validate your email to login. 
* Please check your inbox for the verification email and follow the link in the message, or
* **Click here to resend the verification email**.

**Comment by hsilva-keep** [comment]
@rui-castro The message part is done, but what about the resend functionality? ETA?

**Comment by rui-castro** [comment]
@hsilva-keep this issue was not assigned to me. So it was not planned.
The issues for this week are #323 and #326 and they will pass to the next milestone.
You can set this task also to the next milestone (2.0.0-alpha13).

**Comment by luis100** [comment]
@rui-castro what is the status of this issue?

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #542

**Comment by luis100** [comment]
Works well, but when validating the message "Validate password" appears instead of, e.g. "Confirm email xxx@xxx.org".

**Comment by luis100** [comment]
Merged into lf_dev

**Comment by luis100** [comment]
Updated translations 155ef134846d859166f3ede360aefea2a01416d1
