### ISSUE TITLE
Change CSS rule for metadata .form-separator class

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#440]
Use this

.form-separator {
    color: #089de3;
    font-size: 1.8rem;
    margin: 1em -15px 0 -15px !important;
    padding: 5px 15px !important;
}

**Comment by sleroux-keep** [comment]
Done
![selection_007](https://cloud.githubusercontent.com/assets/2727798/17549956/aaaaeab6-5eea-11e6-83b3-a0e8c081aa9f.png)
