### ISSUE TITLE
Apply permissions to all below recursively timeout on UI

### ISSUE THREAD

**Issue by luis100** [keeps/roda#442]
When applying permissions to all below on a very large collection, an error appears after a while, but the task keeps running on background. This should be some timeout on the UI.

The solutions should be alike the on in the transferred resources refresh.

**Comment by nunovieira220** [comment]
A solution similar to the transferred resources refresh was implemented, please test it.

**Comment by luis100** [comment]
Not solved, this issue is going to be replaced by the more generic #490.
