### ISSUE TITLE
Remove white borders from toolbar buttons

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#443]
.toolbarLink {
    display: inline-block;
    font-size: 20px;
    line-height: 35px;
    width: 35px;
    height: 35px;
    cursor: pointer;
    cursor: hand;
    color: white;
    background-color: #999;
    text-align: center;
    /* border-left: 1px SOLID WHITE; */
}

**Comment by vitorfernandes87** [comment]
@sleroux-keep @jmaferreira 
I can change this because I'm adding a new button on the view representation toolbar
