### ISSUE TITLE
When a SIP fails to ingest, the link to the SIP on the ingest report is wrong (because the SIP moved to the UNSUCCESSFULLY_INGESTED folder)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#444]

**Comment by hsilva-keep** [comment]
@jmaferreira This issue was already solved since 96f542d4b4d8b5208beee7d9ccc829d7daf6d5fa (was registered in keeps gitlab). I'm closing the issue but, if after updating the repository to the last base code the problem still persists, please reopen the issue.
