### ISSUE TITLE
Missing translation for descriptions levels

### ISSUE THREAD

**Issue by frakinho** [keeps/roda#446]
![screenshot_63](https://cloud.githubusercontent.com/assets/3912131/17181356/c84f7416-5417-11e6-9305-94742f862214.png)
SC => (en)-(Section)  (pt)-(Secção)
...
collection => (en)-(Collection) (pt)-(Coleção)

**Comment by luis100** [comment]
This is an implementation issue, moving it to the correct issue tracker.
