### ISSUE TITLE
Use the metadata templating system to define and edit the user metadata

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#448]
The outcome should be a XML file with the extra user information except:

- username
- password
- email
- full name
- roles
- groups

It should support edit and visualisation (XSLT) and indexing XSLT

**Comment by luis100** [comment]
Field already exists and can start to develop for user management, profile will still need #410 to be fixed.

**Comment by nunovieira220** [comment]
User metadata templating system added to user CRUD, please review it.

**Comment by luis100** [comment]
works fine
