### ISSUE TITLE
Concurrency problem on HTML stylesheet

### ISSUE THREAD

**Issue by luis100** [keeps/roda#456]
Seen when re-indexing a large amount of AIPs and trying to access the descriptive metadata HTML version.

`GenericException: Could not process descriptive metadata binary aip/c8bca4fd-d2ba-4a84-b9f2-9873db411a81/metadata/descriptive/md_cellar_3376bd0a-b46e-11e5-8d3c-01aa75ed71a1.rdf metadata type op-work and version null, caused by java.util.concurrent.ExecutionException: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; Premature end of file.`

**Comment by sleroux-keep** [comment]
Fixed at 92e1e947107d1ce7ebf0a48ed965b12dd2626289

**Comment by luis100** [comment]
Solution tested, closing.
