### ISSUE TITLE
Ingest process counters are not working well

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#458]
See examples attached:

- process complete but 32 still processing
- However, on the list of SIPs... all of them are there.

![screen shot 2016-08-01 at 09 23 32](https://cloud.githubusercontent.com/assets/3181302/17287997/a5509d8a-57ca-11e6-868b-6feed7ed89fa.png)
![screen shot 2016-08-01 at 09 23 29](https://cloud.githubusercontent.com/assets/3181302/17287998/a5760d72-57ca-11e6-881f-b391bdef1096.png)

**Comment by hsilva-keep** [comment]
@jmaferreira Without access to this instance, it's hard to diagnose what's going on. So, and using our internal channels, please provide me credentials to this instance (i.e. roda.eark.keep.pt).

**Comment by hsilva-keep** [comment]
Most certainly an error has occurred and therefore some counters are not getting properly updated. In this case, the wise decision to make is in the end of the job to clean these counters, i.e., if there are counters of objects still being processed they must be set to failures.

**Comment by luis100** [comment]
Closing this until it can be reproduced.
