### ISSUE TITLE
Use se same design for comboboxes (the blue one form search page) on all combos of the repository

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#461]
Use the same height as comboboxes

**Comment by sleroux-keep** [comment]
the blue one form search page ???

**Comment by jmaferreira** [comment]
The blue combobox where you can change the type of object to search for - IE, File, Representation…

**Comment by luis100** [comment]
This is not essential.
The combobox of the search page had to be re-implemented because there is no way to style listboxes.
This makes the combobox loose functionality, e.g. keystroke actions.

Therefore I recommend doing this later.

**Comment by hsilva-keep** [comment]
The same design is used since RODA version 3. Closing without further actions.
