### ISSUE TITLE
Add a search box to the descendants of a given AIP

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#464]

**Comment by vitorfernandes87** [comment]
Closed on 4ba633398aeb854f1db7fa3e3189a81bdd3fc090

**Comment by jmaferreira** [comment]
Call the button Search "In descendants" or "In this scope". It should allow the user to search for representations or files that are inside any of the descendants of that AIP.

Relates to an indexing issue that @nunovieira220 is handling.

**Comment by vitorfernandes87** [comment]
Closed on 7f22035bbcced16d3f5b357b63b4aa30f9415b90 by @nunovieira220
