### ISSUE TITLE
Risk incidence register page description

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#468]
It is necessary to add a description and its translation to the risk incidence list page.

**Comment by jmaferreira** [comment]
Nuno, why was this issue assigned to me? If done, just close it.

**Comment by nunovieira220** [comment]
@jmaferreira, it is not done. There is not a correct description for the risk incidence list page.

**Comment by jmaferreira** [comment]
You created the issue… so… why is that assigned to me? Work that out with @luis100 please.

**Comment by luis100** [comment]
@jmaferreira please create a paragraph with the description, then pass it to  @nunovieira220  to implement

**Comment by jmaferreira** [comment]
@luis100 I need the demo to be updated so that I can see the new page.

**Comment by jmaferreira** [comment]
@luis100 the incidence page was your idea. You should write the description. I have no idea.
