### ISSUE TITLE
Stop job execution

### ISSUE THREAD

**Issue by luis100** [keeps/roda#474]
Allow to (gracefully) stop the execution of a job that is currently running. This could be done by sending a high priority message that would make workers skip all following messages.

**Comment by luis100** [comment]
Check also the Kill Actor procedure:
http://doc.akka.io/docs/akka/snapshot/scala/actors.html#Killing_an_Actor

**Comment by hsilva-keep** [comment]
Done since 5e271e97f65d1586aa319c29878a0029a9b78525 (with this commit it's possible to stop the job via WUI).
