### ISSUE TITLE
Add "mandatory field" support to template implementations 

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/roda#487]
This parameter must be available to all templates (users, metadata, etc...).
Something like:
```
{{~field mandatory="true" name="name"  (...)
```

**Comment by jmaferreira** [comment]
I think this is already supported. @luis100 and @adrapereira can you confirm this?

**Comment by luis100** [comment]
I don't think it was

**Comment by jmaferreira** [comment]
It has. Its already in the documentation. 
http://192.168.2.19:8080/?locale=en#theme/InstallingNewDescriptiveMetadataFormats.html

@sebastien, its important that you update the documentation page with your changes to this procedure.

**Comment by luis100** [comment]
Its documented but was only implemented support in RODA-in, this issue reports to the support in RODA.

@sleroux-keep I agree that any change needed to the documentation should be included as part of this issue

**Comment by sleroux-keep** [comment]
Documentation updated.

**Comment by jmaferreira** [comment]
Reviewed.
