### ISSUE TITLE
Add "error summary" at the top of the forms

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/roda#491]
When a form have a lot of field, a summary a the top, with the validation errors, may be useful.

**Comment by jmaferreira** [comment]
There’s already an issue about that. The errors should show up in the top of the form.

**Comment by jmaferreira** [comment]
I can't seem to find the other issue.. maybe someone has already fix it?! @vitorfernandes87 did you work on this?

if not, just move the error message to the top of the form.

**Comment by luis100** [comment]
I think this was done by @adrapereira in the case of the schema validation errors of descriptive metadata.

The validation for other cases, specifically the user extra metadata, is the other possible case, this is what is referred on this issue.

**Comment by sleroux-keep** [comment]
Stable @ 0250317e3d7560623a7d305594b4690304cb9105

**Comment by luis100** [comment]
checked
