### ISSUE TITLE
Support template validation on metadata forms

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/roda#492]
Currently, the validation is only schema-based. With the addition of the "mandatory" parameter to the template, a "template-based" validation may be useful (i.e. force the title of EAD to be filled).

**Comment by jmaferreira** [comment]
The templates are for visualisation purposes. The schema will handle the validation. We can add some javascript that changes the color of the field to warn the user if a mandatory field is not being used.

However, if necessary the administrator can change the schema to make fields mandatory.

**Comment by luis100** [comment]
@sleroux-keep is the "*" added to the label when the field is marked as mandatory? If it is we can close this issue.

**Comment by sleroux-keep** [comment]
If the field is marked as mandatory, the "*" is added:
![star](https://cloud.githubusercontent.com/assets/2727798/18281116/9018f28c-7453-11e6-86e5-db3796417d4e.png)
