### ISSUE TITLE
All RODA Member methods should be accessible via ModelService

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#495]
Also, LDAPUtility exceptions should be mapped to RODAExceptions (e.g. NotFoundException, etc.)

**Comment by rui-castro** [comment]
in LDAPUtility, map LDAP exceptions to existing exceptions (subclasses of RODAException).

**Comment by luis100** [comment]
Controller classes are currently calling LdapUtility directly and should use ModelService instead. Some of this work as already done by  @hsilva-keep  but not completed.

Also, some exceptions that are all getting wrapped into LdapUtilityException should be mapped instead into subclasses of RODAException. GenericException should be used as a fallback case (this gives an internal server error or REST API), NotFoundException when retrieves don't find what they are looking for, etc.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep  Please provide an example of a method that is calling LdapUtility directly and should use ModelServive instead.

**Comment by rui-castro** [comment]
@luis100 ping

**Comment by jmaferreira** [comment]
@luis100 pong

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep check my PR #560 

Only RodaCoreFactory, UserUtility and ModelService use LdapUtility directly.
All other classes use ModelService to perform user/group/roles actions.

Is this what was expected?

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep done in PR #560

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep the PR is ok? can you close this issue?

**Comment by luis100** [comment]
done.
