### ISSUE TITLE
Change in email notification broke user register when email SMTP is not configured

### ISSUE THREAD

**Issue by luis100** [keeps/roda#496]
Before, if email SMTP was not configured, and a user registered, the user would be ativated as email verification could not be sent. Now, user remains locked and cannot unlock himself because email was never sent.

New email notification system should be able to inform when notification cannot be sent so the user email verification can behave properly when SMTP is not configured.

**Comment by sleroux-keep** [comment]
Fixed (but some work needs to be done with the notification... email related fields should be removed).

**Comment by hsilva-keep** [comment]
@sleroux-keep they shouldn't be removed but instead revised & renamed to be more generic (e.g. 'recipientUsers' perhaps should be renamed to 'recipients').

**Comment by luis100** [comment]
This works, closing.

@hsilva-keep if a generalization needs to happen, please create a new issue.
