### ISSUE TITLE
It should be possible to execute a piece of code in the end of an ingest

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#499]
E.g. do some processing with the resulting AIPs.

**Comment by jmaferreira** [comment]
Is this already implemented? Is this fundamental or a nice to have? Can we move it to unplanned?

**Comment by luis100** [comment]
@hsilva-keep This is necessary for the replication task.

**Comment by hsilva-keep** [comment]
Done since c481f908caeebd11dc99408a6333ab99012d2024.
