### ISSUE TITLE
Browse descriptive metadata tab title is not using the metadata type

### ISSUE THREAD

**Issue by luis100** [keeps/roda#503]
It is falling back to showing the file name. It should show the label for the metadata type.

**Comment by sleroux-keep** [comment]
Fixed with 77985e561ff86a410305ee30e149dbb9a3f5ab18

Note: if you create a descriptive metadata of type EAD-2002 and save it. Then, you create another EAD-2002 descriptive metadata. The template is "pre-filled" with the title of the first file... Bug?

**Comment by luis100** [comment]
On the note, bug registered on #505.

**Comment by luis100** [comment]
cheched.
