### ISSUE TITLE
Descriptive metadata form pre-filled when a file of the same type/version already exists

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/roda#505]
1 - Create a descriptive metadata of type EAD 2002 
2 - Set the title and other fields and save.
3 - Create a new Descriptive Metadata of type EAD 2002 for the same AIP.
4 - The form is "pré-filled" with the data of the first file.

**Comment by sleroux-keep** [comment]
The "title" field is using " auto-generate='title' "... This generator is causing this behaviour.

**Comment by luis100** [comment]
this is the expected behavior, closing.
