### ISSUE TITLE
Don't hardcode "users" in the register page

### ISSUE THREAD

**Issue by luis100** [keeps/roda#507]
Make it configurable, and probably should make this server-side.

**Comment by sleroux-keep** [comment]
Fixed at 0be139cc8e19ac504ed7f40b02e3afce7aea6edd

Configuration name: ui.register.defaultGroups .

**Comment by luis100** [comment]
This (and previous) method is insecure, as an RPC request can be manifactured to register a user in the administrators group.

When registering a user, reset the groups and roles of a user to the ones defined in the configuration. Add `ui.register.defaultRoles` for completeness.

If configuration don't exist, assume empty groups and roles.

**Comment by sleroux-keep** [comment]
Fixed @ a8de4cc4e30f47353d1cbc807e08a29760bc90fc

**Comment by luis100** [comment]
When registering user and email SMTP not active, user doesn't get into default group. May be due changes in notification, check  555d565920486ec4960d572cd9588deb0077b0a1

**Comment by sleroux-keep** [comment]
Fixed @ e1c32527f77c1d6cf712630d631c1194f6faa1fa

**Comment by luis100** [comment]
checked.
