### ISSUE TITLE
Better handle session expire

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#510]
When the session expires, and one tries to do something (e.g. consult the catalogue), a message saying that the user 'guest' does not have the needed permissions appears. In this case, the user should be redirected to the login page.
![captura de ecra de 2016-09-08 14 54 10](https://cloud.githubusercontent.com/assets/1315759/18351985/5b658046-75d4-11e6-9e2b-12afd64b87f7.png)

**Comment by luis100** [comment]
Replaced by #696
