### ISSUE TITLE
Statistics enhancements

### ISSUE THREAD

**Issue by luis100** [keeps/roda#512]
- [x] Set chart background white, add a border 2px #eee
- [x] Needs bottom padding in cards
- [x] Remove legend from bar chart (at least when in facets distribution)
- [x] Support sorting of facet distribution by means of `data-view-sort="DESC"`
- [x] Support limiting the number of results of facet distribution by means of `data-view-limit="10"`.
- [x] Bonus if presenting the sum of all "others" in an "others" column.
- [x] Support facet value i18n
- [x] Add some extra charts (see below)

Catalogue
- Transferred resources:
  - [x] Number
  - [x] Distribution of ingested successfully, failed and to process (is this possible?)
- File
  - [x] Distribution of PRONOM
  - [x] Distribution of MIME type

Preservation
- Premis events:
  - [x] Number
  - [x] Distribution of type
  - [x] Distribution of agents
- Risk
  - [x] Number
  - [x] Distribution of posMitigationSeverity
- RiskIncidences
  - [x] Number
  - [x] Distribution of severity
  - [x] Distribution of status

Processes and actions
- Job
  - [x] Distribution by status
  - [x] Distribution by plugin type
- Job Report
  - [x] Number
  - [x] Distribution of plugin
  - [x] Distribution of plugin type
- Logs
  - [x] Distribution of users, filtering by some selected method (e.g. find, check RODA 1.0)

Communication
- Notification 
  - [x] Number
  - [x] Distribution of acknowledgement

**Comment by nunovieira220** [comment]
All statistics changes were made.
