### ISSUE TITLE
Log entry panel show outcome and add facet

### ISSUE THREAD

**Issue by luis100** [keeps/roda#514]
- [x] On the log entry panel show the outcome (using the label defined in HTMLSnippetUtils)
- [x] Add outcome facet to UserLog
- [x] Find all methods that produce UNKNOWN state log entries and fix them (e.g. retrieve log entry action) 
- [x] Sort log entry facets by count (all of them), using the new facet parameter attribute

**Comment by luis100** [comment]
Needed methods are on commit cb314ec5ed58718eadc4bb64b81b067f0fca3610

**Comment by sleroux-keep** [comment]
Implemented at 7a6637ca057a2e7fdfab345b0c627527398430d8

**Comment by luis100** [comment]
- [ ] Outcome facet values UNAUTHORIZED and UNKNOWN are not translated

**Comment by sleroux-keep** [comment]
Fixed @ abb541298a9586b4281a10ab168db7e83af8c95e

**Comment by luis100** [comment]
Checked.
