### ISSUE TITLE
Facet i18n of log entry components

### ISSUE THREAD

**Issue by luis100** [keeps/roda#515]
Use facet i18n system to translate the current log entry component values.

**Comment by sleroux-keep** [comment]
Fixed at 1ebd2cb1ea3bd4bda8102f9d7511c239bfc32a7f

**Comment by sleroux-keep** [comment]
Review the translations (ui.facets.LogEntry.actionComponent,XXXXXX(

**Comment by luis100** [comment]
Checked.

**Comment by luis100** [comment]
This method could be generalized to fit other facet value translations in lists.
Use the same strategy to keep IndexResult in AsyncTableCell and create method that allows to translate a facet value on request, to be used by list implementations.

**Comment by sleroux-keep** [comment]
Implemented @ 768bbab49fb2a3d79f805ec82034dc06c4449f6a

**Comment by luis100** [comment]
Checked.
