### ISSUE TITLE
Add a way to view all the versions of a description object

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#52]
All the versions of a description object are already stored by Fedora Commons. Add functionality to read the full history of changes in the UI.

**Comment by luis100** [comment]
This includes adding support for versioning on the backend, use this feature for editing descriptive metadata files, and allow to view previous version via the interface.

**Comment by luis100** [comment]
Added versioning support in the backend, missing UI and REST API method support.

**Comment by luis100** [comment]
Added all features to the UI

**Comment by luis100** [comment]
Done since 60d792667cb56b3d44e87583d851dba97f77a0a9
