### ISSUE TITLE
Revise action button colors

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#520]
The grey color is not working out for me. It may be confused with the disabled button.

I recommend using 4 colours:
1. Grey for disabled
2. Green for the main creation actions (e.g. NEW)
3. Red for destroyers (e.g. delete)
4. Blue for all the others

Some ideas or color button paletes.

![bootstrap-button-styles1](https://cloud.githubusercontent.com/assets/3181302/18410004/f3a77010-774d-11e6-904b-1d5a7ce3c9b3.png)

![flat_ui_colors](https://cloud.githubusercontent.com/assets/3181302/18409984/bdf502fc-774d-11e6-8b31-93a8afc51538.png)

**Comment by luis100** [comment]
@jmaferreira is this a priority? if not I would recommend postponing to another sprint.

Also, there is a way to make colors easier to change by using GSS instead of CSS, see #521

**Comment by jmaferreira** [comment]
1. It is not a major priority. It can be postponed
2. GSS will not enter this version of RODA.

**Comment by luis100** [comment]
Done
