### ISSUE TITLE
When creating a new desc. metadata with a existing file name, show a proper error

### ISSUE THREAD

**Issue by luis100** [keeps/roda#525]
Now the error is not well catched and shows on a red notification in top-right corner of the screen.
Show a proper error in the below the file name text field, in red.

**Comment by sleroux-keep** [comment]
Implemented @ 4dd1b9bf65c648184e17ca97327b92a1cac938da

**Comment by luis100** [comment]
Schema validation/file already existing errors are not cleaned up when alternating through.

**Comment by sleroux-keep** [comment]
Fixed @ dba78ef0d2162fdb92993040697829509b0c2a74

**Comment by luis100** [comment]
checked.
