### ISSUE TITLE
FileStorageService support for folder scattering

### ISSUE THREAD

**Issue by luis100** [keeps/roda#527]
Anti-cluttering technique similar to [hashed directory structure](http://michaelandrews.typepad.com/the_technical_times/2009/10/creating-a-hashed-directory-structure.html).

For folders that will have entries that are randomly generated, like the `storage/aip`, that will have a sub-folder for each AIP with the ID as the folder name, which ill be an [randomly generated UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier), we can use a technique to work-around the possible cluttering of billions of directory entries.

Example: 123e4567-e89b-12d3-a456-426655440000
123/e45/123e4567-e89b-12d3-a456-426655440000

Have a configuration in `roda-core.properties` that defines the folders where this technique will be used and with what configuration.

```
core.storage.filesystem.sparse = aip
core.storage.filesystem.sparse = jobreport
# base path regex pattern
core.storage.filesystem.sparse.aip.base = aip/
# first block with 3 characters, second block with 2 characters, then entry with all characters
core.storage.filesystem.sparse.aip.path = aip/%3/%2/%all 
# if path first not found, fallback to second option
# first block with 3 characters, second block with 2 characters, then entry with rest of characters
core.storage.filesystem.sparse.aip.path = aip2/%3/%2/%rest 

# base path regex pattern
core.storage.filesystem.sparse.jobreport.base = job-report/(.*)/
core.storage.filesystem.sparse.jobreport.base = job-report/$1/%2/%all
```

**Comment by nunovieira220** [comment]
Done on 47ffeac9ca454850a194a4a02ad5b742ab5ad6fe
