### ISSUE TITLE
Template field list separate options and translation logic

### ISSUE THREAD

**Issue by luis100** [keeps/roda#534]
For template fields of type list, have the arguments:
- options: The list of possible values, e.g. `options: ["opt1","opt2"]`
- labels: Labels for the possible values, in several possible translations, e.g. `labels: {"opt1": {"en": "Option 1", "pt_PT": "Opção 1"}, "opt2": {"en": "Option 2", "pt_PT": "Opção 2"}}`
- labelI18nKeyPrefix: Key prefix of external resolutions of the labels for the possible values, e.g. `labelI18nKeyPrefix: "example.label."`

**Comment by sleroux-keep** [comment]
The "labels" and "labelI18nKeyPrefix" must be renamed to "optionsLabels" and "optionsLabelI18NKeyPrefix" to avoid confusion with the label of the field.

**Comment by sleroux-keep** [comment]
Updated @ 4798e72551e62c8aabce30a14bb4d65cd42edf9f 

NOTE: Templates used in implementations needs to be updated!

Example of field:

```
{{~field 
name="statusDescription"
order="470" 
type="list" 
value="final"
options="[\"final\",\"revised\",\"draft\"]"
optionsLabels="{\"final\": {\"en\":\"Final\", \"pt_PT\":\"Final\"},\"revised\": {\"en\":\"Revised\", \"pt_PT\":\"Verificado\"},\"draft\": {\"en\":\"Draft\", \"pt_PT\":\"Rascunho\"}}"
optionsLabelI18nKeyPrefix="crosswalks.dissemination.html.ead.statusDescription" 
label="{\"en\": \"Status description\", \"pt_PT\": \"Estado da descrição\"}" 
xpath="/*:ead/*:archdesc/*:odd[@type='statusDescription']/*:p/string()"
~}}
```

**Comment by luis100** [comment]
checked
