### ISSUE TITLE
Statistics export CSV functionality

### ISSUE THREAD

**Issue by luis100** [keeps/roda#536]
Depends on #319

Extend statistics jquery plugin to allow a new view to create the export button.

The definition of the query can be via normal `data-` attributes or via a new attribute that can reference another element by id, where to get the `data-` attributes.

```html
<div class="col_8 chart_col_card">
	<h4>Distribution of description levels (top 10)</h4>
	<canvas id="stat-desc-levels" class="statistic" data-source="index" 
                data-source-class="org.roda.core.data.v2.ip.IndexedAIP" 
                data-source-facets="level" data-view="chart" 
                data-view-field="facetResults" data-view-type="pie" 
                data-view-limit="10"></canvas>
	<span class="statistic" data-view="download" data-ref="stat-desc-levels">
		<i class="fa fa-download" aria-hidden="true"></i>
	</span>
</div>
```

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep @jmaferreira when the statistic is showing facet data (like the example above),  the button should download the actual data in CSV, not the facet data, right?

**Comment by jmaferreira** [comment]
In my very humble opinion there are two different cases:

1. Export data that was used to build the chart
2. Export data displayed on any RODA table

I believe @rui-castro is talking about case 1. In this case I would export exactly the data that was used to build the chart, nothing else. If we want a full list of data, we can get it via search results table.

**Comment by rui-castro** [comment]
@jmaferreira @luis100 @hsilva-keep  ok. that raises a question... how should the facet data be transformed into CSV?

This query
```
http://127.0.0.1:8888/api/v1/index?
  returnClass=org.roda.core.data.v2.ip.IndexedFile&
  start=0&
  limit=0&
  onlyActive=true&
  facet=formatMimetype&
  facet=formatPronom
```
...produces this output...
```json
{
  "offset": 0,
  "limit": 0,
  "totalCount": 6,
  "results": [],
  "facetResults": [
    {
      "field": "formatPronom",
      "totalCount": 4,
      "values": [
        {
          "label": "fmt/19",
          "value": "fmt/19",
          "count": 3
        },
        {
          "label": "fmt/17",
          "value": "fmt/17",
          "count": 1
        },
        {
          "label": "fmt/215",
          "value": "fmt/215",
          "count": 1
        },
        {
          "label": "fmt/276",
          "value": "fmt/276",
          "count": 1
        }
      ],
      "selectedValues": []
    },
    {
      "field": "formatMimetype",
      "totalCount": 2,
      "values": [
        {
          "label": "application/pdf",
          "value": "application/pdf",
          "count": 5
        },
        {
          "label": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          "value": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          "count": 1
        }
      ],
      "selectedValues": []
    }
  ],
  "date": 1474555773916
}
```

What's the expected CSV for this data?

**Comment by hsilva-keep** [comment]
@luis100 @rui-castro @jmaferreira 
```
field, label, value, count
formatPronom, fmt/19, fmt/19, 3
formatPronom, fmt/17, fmt/17, 1
formatPronom, fmt/215, fmt/215, 1
formatPronom, fmt/276, fmt/276, 1
formatMimetype, application/pdf, application/pdf, 5
...
```
???

**Comment by luis100** [comment]
de notar que o sistema atual não suporta mais que uma facet de uma vez, logo a primeira coluna pode ser informação que não interessa. Do mesmo modo, o label pode não ser traduzido. Assim o output ficar melhor assim:
```csv
formatPronom, count
fmt/19, 3
fmt/17, 1
fmt/215, 1
fmt/276, 1
application/pdf, 5
...
```

No entanto, esta pode ser muito restritiva se o label for traduzido (como nos níveis descritivos), ou se no futuro adicionarmos várias facets.

A opção do @hsilva-keep é a mais segura, mas melhorias opcionais como as que apresentei aqui podem ser muito convenientes.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep suggestion is more generic, I'll use that.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep @jmaferreira since we will have 2 different outputs in CSV (results and facets), should we have 2 different URLs or just 1?

1. Single URL
 * results - http://127.0.0.1:8888/api/v1/index?... (without facet params)
 * facet - http://127.0.0.1:8888/api/v1/index?... (with facet params)

2. Two URLs
 * results - http://127.0.0.1:8888/api/v1/index?...
 * facets - http://127.0.0.1:8888/api/v1/index/facets?...

**Comment by hsilva-keep** [comment]
@rui-castro IMHO, single URL with query param otherwise we're running away from REST.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep done in PR #559

It can be used, specifiyng all attributes, like this:
```html
<span class="statistic btn"
	  data-source="index"
	  data-source-class="org.roda.core.data.v2.ip.IndexedRepresentation"
	  data-source-facets="type"
	  data-view="download"
	  data-view-filename="representation-types.csv">
	<i class="fa fa-download" aria-hidden="true"></i>
</span>
```
Or, referencing the attributes of another statistic, using attribute `data-ref` with the **id** of the other element.
```html
<canvas id="stat-desc-levels" class="statistic"
		data-source="index"
		data-source-class="org.roda.core.data.v2.ip.IndexedAIP"
		data-source-facets="level"
		data-view="chart"
		data-view-field="facetResults"
		data-view-type="pie"
		data-view-limit="10"></canvas>
<span class="statistic btn"
	  data-ref="stat-desc-levels"
	  data-view="download"
	  data-view-filename="description-levels.csv">
	<i class="fa fa-download" aria-hidden="true"></i>
</span>
```

Added these examples to statistics page.

**Comment by luis100** [comment]
checked and integrated a2c96ffe0de60d057bf1868ea24df22e72b5d2d9
