### ISSUE TITLE
Enable support for external authentication via CAS

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#539]
After the research phase (#383), we must develop the CAS integration.

**Comment by rui-castro** [comment]
CAS filters are defined here (commented): https://github.com/keeps/roda/blob/c959e09971d1804e32dfc1e7134c971f62f48b3d/roda-ui/roda-wui/src/main/webapp/WEB-INF/web.xml

RODA authentication filters are here:
https://github.com/keeps/roda/tree/c959e09971d1804e32dfc1e7134c971f62f48b3d/roda-ui/roda-wui/src/main/java/org/roda/wui/filter

CAS documentation: https://apereo.github.io/cas/4.2.x/index.html

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep @jmaferreira check PR #596 

Renamed filters to:
* **InternalWebAuthFilter** - internal auth filter for website requests.
* **InternalAPIAuthFilter** - internal auth filter for API requests.
* **CasWebAuthFilter** - CAS auth filter for website requests.
* **CasAPIAuthFilter** - Cas auth filter for API requests.

Created a new type of filter `OnOffFilter` that can wrap other filters and enable/disable them based on RODA configuration. It also uses RODA configuration to init the filters.

```xml
<filter>
	<filter-name>InternalApiAuthFilter</filter-name>
	<filter-class>org.roda.wui.filter.OnOffFilter</filter-class>
	<init-param>
		<param-name>inner-filter-class</param-name>
		<param-value>org.roda.wui.filter.InternalApiAuthFilter</param-value>
	</init-param>
	<init-param>
		<description>Realm to be used</description>
		<param-name>realm</param-name>
		<param-value>RODA REST API</param-value>
	</init-param>
	<init-param>
		<description>comma separated list of relative paths to exclude in filter logic (using regular expressions for extra power)</description>
		<param-name>exclusions</param-name>
		<param-value>^/swagger.json,^/v1/theme/?</param-value>
	</init-param>
</filter>
```

Internal filters are **enabled** by default.
CAS filters are **disabled** by default.

To enable a filter simply add a line like this to **roda-wui.properties**
`ui.auth.filter = InternalWebAuthFilter`

To enable CAS uncomment the following lines:
```
ui.auth.filter = CasWebAuthFilter
ui.auth.filter = CasApiAuthFilter
ui.auth.filter = CASAuthenticationFilter
ui.auth.filter = CASValidationFilter
ui.auth.filter = CASRequestWrapperFilter
```

# API access with internal filters

Use Basic auth.

# API access with CAS filters

3 ways of accessing the API with CAS.

1. Basic auth with username and password (slower - 3 requests to CAS per API request).
2. Ask for a **Ticket Granting Ticket** and use it in request header `tgt`. (slow - 2 requests to CAS per API request).
2. Use an authenticated session (faster - 1 request to CAS per API request).

## 1. Basic auth

```bash
curl -v -u admin:roda http://localhost:8888/api/v1/index?returnClass=org.roda.core.data.v2.ip.IndexedAIP
```

## 2. Using a ticket

### Create a new ticket
```bash
curl --data "username=admin&password=roda" http://localhost:8888/api/auth/ticket
```
Result:
`TGT-12-hkfI7etcR0WDGiuFNFz6o6kufeUTgUHDIXWfWcrpOp3jdApheq-cas01.example.org`

### Put the ticket in header `tgt`
```bash
curl -v -H "tgt: TGT-12-hkfI7etcR0WDGiuFNFz6o6kufeUTgUHDIXWfWcrpOp3jdApheq-cas01.example.org" http://localhost:8888/api/v1/index?returnClass=org.roda.core.data.v2.ip.IndexedAIP
```

## 3. Authenticated session

Using a client that can store cookies:
1. use one of the previous methods to authenticate the first time,
2. use the same session to make subsequent requests.

**Comment by rui-castro** [comment]
@hsilva-keep @luis100 @jmaferreira I think my PR implements all the requisites. Can you close this issue?

**Comment by hsilva-keep** [comment]
@rui-castro Apologies for being so direct, but until you've sorted out the code reviews I've made in the pull request (about CasClient.java & AuthTicketResource.java), I won't review the PR more than I've done so far (to take a look at source code). 
I'm not even complaining about configurations and how they could be less (as several related to CAS are replicated just because they are used in different CAS filters). 
But it's up to @luis100 & @jmaferreira to decide if I'm being to picky & PR analysis should be done even without you doing the changes mentioned in the code review.

**Comment by rui-castro** [comment]
@hsilva-keep I don't any comments in PR #596. Where did you put them?

**Comment by hsilva-keep** [comment]
@rui-castro My apologies, I've forgot to submit the code review :( damn it...

**Comment by rui-castro** [comment]
@hsilva-keep done

**Comment by hsilva-keep** [comment]
@rui-castro thanks for the update & once more my apologies for that misunderstanding (about the code review; my bad). 
I'll test the code, merge it, close related issues/pull request but will most certainly open other issues related to improvements that must be introduced (which in the time you had could not be addressed).

**Comment by hsilva-keep** [comment]
Code was merged & pull request closed.
