### ISSUE TITLE
Registration email with wrong language

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#541]
## Description

When a user registers viewing the website in Portuguese, the registration email is in English.

**Comment by vitorfernandes87** [comment]
This also happens with recover login email.
The notify producer email is also in one language but in that case the template should be generic (maybe with the text in different languages).

**Comment by vitorfernandes87** [comment]
Closed on af0b2ac7b818da649dfcb3fc419dd37c2a37bef8
