### ISSUE TITLE
Alternative create job panel

### ISSUE THREAD

**Issue by luis100** [keeps/roda#543]
Besides current create job panel, that is better suited when preemptively selecting the objects that should be affected by the process, create a new alternative one for when one want to create a process without first selecting the objects.

This panel should appear when clicking new process on process list page.
Suggestion screenshot is below, list should show all available plugins and list of possible objects classes to run is filtered according to the selected plugin.

![create_process_alternative](https://cloud.githubusercontent.com/assets/631728/18583843/079fa266-7c05-11e6-822e-a7ae1f6ce217.png)

**Comment by nunovieira220** [comment]
Create job alternate page is implemented.
