### ISSUE TITLE
It's not possible to use emails with '+'

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#545]
## Description

If one tries to use an email with a `+` sign, like `rui.castro+teste@gmail.com` a validation message appears saying **Wrong e-mail format**.

The `+` sign is a valid character for an email and should be possible to use it.

**Comment by vitorfernandes87** [comment]
I think this problem only happens in UserDataPanel.
The email verification regex needs to be changed. Right now the regex is:

`^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[_A-Za-z0-9-]+)`

**Comment by vitorfernandes87** [comment]
Added support for '+' and '%' characters on 1c70b320189b02462971c90b58c3a27cc59fef08
