### ISSUE TITLE
When updating own user, don't allow to change groups and roles

### ISSUE THREAD

**Issue by luis100** [keeps/roda#550]
Currently a user could manufacture a GWT RPC request to add himself to the administrators group, or add all the roles.

Reset groups and roles to the ones in the system when changing own user (e.g. for Preferences).

**Comment by sleroux-keep** [comment]
The updateMyUser function was updated with the following "filter":

```
private static User resetUser(User newUser, User oldUser) {
    newUser.setActive(oldUser.isActive());
    newUser.setDirectRoles(oldUser.getDirectRoles());
    newUser.setAllRoles(oldUser.getAllRoles());
    newUser.setGroups(oldUser.getGroups());
    return newUser;
  }
```

@ c4bb7313be0709d207d860ef33726849b9263f89
