### ISSUE TITLE
Update RODA plugin descriptions

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#555]
Use the names and descriptions on the attached file.
Please read them and review them if necessary.
[RODA plugin descriptions.docx](https://github.com/keeps/roda/files/484710/RODA.plugin.descriptions.docx)
[RODA plugin descriptions.pdf](https://github.com/keeps/roda/files/484714/RODA.plugin.descriptions.pdf)

**Comment by jmaferreira** [comment]
@luis100 do you want to take a look at the descriptions before implementing them?

**Comment by nunovieira220** [comment]
The plugin descriptions on the document were updated.
