### ISSUE TITLE
IndexService.findCSV should return an IterableIndexResult instead of requesting Solr all the objects at once (SolrUtils.findCSV))

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#561]
ATM, as IterableIndexResult is only used for IndexService.findAll methods, one cannot ask for the first X amount of objects. But you may do the necessary changes to allow that. But be careful because besides providing an Iterator, this class also does de-duplication.

**Comment by luis100** [comment]
It must also give an ProvidesInputstream that would be used to create a StreamingOutput in the REST API. Right now this give a out of memory error if the number of results is too big because it keep the **whole CSV**  in memory as a string.

**Comment by rui-castro** [comment]
@luis100 `IterableIndexResult` is not a class, right? 
I suppose you mean `IndexResult<T>` where `<T extends IsIndexed>`, is that it?

I think it would be easier  and more efficient to return a InputStream (a Reader, etc) directly;

Method [SolrUtils.find](https://github.com/keeps/roda/blob/mferreira_dev/roda-core/roda-core/src/main/java/org/roda/core/index/utils/SolrUtils.java#L228) does:
1. queries the index, 
2. gets a list of `SolrDocument`,
3. for each `SolrDocument`, transform it into the respective (`IsIndexed`) object,
4. returns a list of (`IsIndexed`) objects.

The problem I see with returning an iterator of `IsIndexed` classes, is that we would be transforming `SolrDocument`s into `IsIndexed` objects and returning that to the `IndexResource`.
The `IndexResource` would have to transform each `IsIndexed` object into a `String (CSV row)`.

The alternative is to transform `SolrDocument`s directly into `String (CSV row)`, which is [already done and is very simple](https://github.com/keeps/roda/blob/mferreira_dev/roda-core/roda-core/src/main/java/org/roda/core/index/utils/CSVQueryResponse.java#L80); append the `String` to a `Stream` and return that `Stream`.

Another disadvantage of intermediary `IsIndexed` classes it the fact that there are 16 of them. So, we would have to implement 16 methods `.toCSV()` or 1 method with 16 `ifs`.

**Comment by rui-castro** [comment]
@luis100 check PR #583 

Export results in CSV is done with streaming, using `IterableIndexResult`.
`IterableIndexResult` doesn't support Sublist. All requests for results in CSV will output all results.

**Comment by luis100** [comment]
checked.
