### ISSUE TITLE
Remove AIP (button) does not delete all AIPs (if all are selected)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#582]
The Remove AIP plugin works fine though...

**Comment by nunovieira220** [comment]
A problem related to AIP remove was solved, please review if it is really fixed.

**Comment by jmaferreira** [comment]
I need a new release to test this.
I'm stuck with Version build on 30.09.2016 @ 12:41:56 WEST

**Comment by luis100** [comment]
Checked.
