### ISSUE TITLE
Alterar a configuração da DGLAB para que permissão "aip.create (não traduzido)" não apareça

### ISSUE THREAD

**Issue by frakinho** [keeps/roda#584]
é preciso traduzir

**Comment by jmaferreira** [comment]
Falta a tradução PT e ES.

**Comment by luis100** [comment]
essa já não existe, é preciso atualizar é a configuração que estás a usar

Luis Faria
Innovation Director
KEEP SOLUTIONS, LDA.
Rua Rosalvo de Almeida, nº 5
4710-429 Braga, Portugal
W www.keep.pt E info@keep.pt
T +351 253066735 F +351 253067248

**Comment by jmaferreira** [comment]
Humm… ok.

Cumprimentos,
Miguel Ferreira

- -
Diretor executivo
KEEP SOLUTIONS, LDA.
Rua Rosalvo de Almeida, nº 5
4710-429 Braga, Portugal
W www.keep.pt E info@keep.pt 
T +351 253066735 F +351 253067248

**Comment by luis100** [comment]
Faltava atualizar a configuração da implementação em questão
