### ISSUE TITLE
Effect problem select/hover events

### ISSUE THREAD

**Issue by frakinho** [keeps/roda#585]
When you select one item the selected color only appears after moving mouse out.

![screenshot_1](https://cloud.githubusercontent.com/assets/3912131/19044057/946ee71e-898a-11e6-8814-81a980b85d6f.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3912131/19044058/9470df06-898a-11e6-900a-1f3fba0812e9.png)

**Comment by jmaferreira** [comment]
Might need a CSS rule to override the hover when selected.

**Comment by vitorfernandes87** [comment]
Closed on 123bf99e4dfbaecb251b27dc5b76cb6bc8f07453
