### ISSUE TITLE
Ingest process counter problem when "Uploaded File/Folder" SIP type is selected

### ISSUE THREAD

**Issue by vitorfernandes87** [keeps/roda#586]
Shows "6 of 7"

![roda 96bb69b3 ade0 42f8 9851 a70297b4f6eb](https://cloud.githubusercontent.com/assets/9133305/19045200/6a8cb0c0-898f-11e6-9963-ee7b285b47c1.png)

**Comment by jmaferreira** [comment]
E-ARK SIP ingest works fine.
Probably is worth checking if BagIt is also working well.

**Comment by nunovieira220** [comment]
I can't reproduce this issue with the same corpora and parameters.

**Comment by vitorfernandes87** [comment]
After updating to the last version I can't reproduce this issue.
