### ISSUE TITLE
Ingest process problem with permissions

### ISSUE THREAD

**Issue by vitorfernandes87** [keeps/roda#588]
Admin user doesn't have CREATE_TOP_LEVEL_AIP_PERMISSION permission on a clean installation (after removing .roda folder).
After reindex users everything works fine.

![roda eeab864d a98d 415d bebf 71fde7ee0812 d09cd065 ff9c 48d8 9ccc 147e9f6fa850](https://cloud.githubusercontent.com/assets/9133305/19045576/85158924-8991-11e6-8204-43fcab266de1.png)

**Comment by jmaferreira** [comment]
It should be the default LDAP settings...

**Comment by vitorfernandes87** [comment]
Forcing a reindex after creating roles.
Closed on c108218d0397774cdf1de48430d1f89ebd19ef97
