### ISSUE TITLE
The user doesn't have CREATE_TOP_LEVEL_AIP_PERMISSION permission happens when ingesting SIPs of type "Uploaded file/folder (1.0)"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#593]
![screen shot 2016-10-04 at 12 01 42](https://cloud.githubusercontent.com/assets/3181302/19072020/e51b3834-8a2a-11e6-98e3-937b61b1735d.png)

**Comment by vitorfernandes87** [comment]
Repeated of #588
