### ISSUE TITLE
The Reindex all plugin should also reindex jobs and users

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#594]
The plugin that indexes individual indexes should also be updated to support users and jobs

**Comment by nunovieira220** [comment]
The reindex all plugin now automatically reindexes log entries and users (based on index for now) however jobs are not because it causes some inconsistencies on the reports.

**Comment by jmaferreira** [comment]
What do you mean by "based on the Index"?
Do we have the option to index just the users (using the Reindex entity) plugin?
