### ISSUE TITLE
In ingest job, have a button to list all created AIPs

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#598]
The idea is to be able to remove all AIPs from an ingest job in case the ingest didn't go well, or while doing experiments.

**Comment by luis100** [comment]
There is already a plugin to remove all AIPs. Problem is to get the search parameters right to be able to orchestrate the plugin correctly.

So, what is needed is a button in the job ingest plugin that allow to define search with all AIPs created by the Job.

**Comment by nunovieira220** [comment]
There is now a button on show ingest job that links to ingestJobId filtered search.
