### ISSUE TITLE
On BrowserHelper remove all StreamingOutput

### ISSUE THREAD

**Issue by luis100** [keeps/roda#599]
StreamingOutput is a REST API specific class that should not be part of the main methods.

Replace StreamingOutput by ProvidesInputStream or ConsumesOutputStream.

Then, on the REST API resource, transform the classes by using RodaStreamingOutput.

**Comment by sleroux-keep** [comment]
Fixed @ e3b306633def1b9042f8d33717b5a4a464be5b96

javax.ws.rs.* classes only appears in REST API related classes.

**Comment by luis100** [comment]
@hsilva-keep please review

**Comment by hsilva-keep** [comment]
I've followed the commits related to this task, so I can affirm that everything is good.
