### ISSUE TITLE
Improve BrowserHelper.retrieveClassficationPlan()

### ISSUE THREAD

**Issue by luis100** [keeps/roda#600]
- [x] use index.findAll() instead of manually iterating through index.find()
- [x] ensure only information accessible by user is being provided
- [x] Don't return StreamResponse, see #599
- [x] Filename to be (optionally) defined on the REST API (query) parameters
- [x] Replace used deprecated methods

**Comment by sleroux-keep** [comment]
Fixed @ a16dd194b145ec003fe5a3c700bbdda6d4e7479d

Created ClassificationPlanUtils to keep all the code related to ClassificationPlan

**Comment by luis100** [comment]
- [ ] Instead of using StringWriter wrap OutputStream into an OutputStreamWriter and write directly into the output stream

**Comment by sleroux-keep** [comment]
No need to use OutputStreamWriter... The ObjectMapper accept the OutputStream directly...

Fixed @ 5f524cc862249aa1ecd39c14703fdc9e03771a19

**Comment by luis100** [comment]
@hsilva-keep please review

**Comment by hsilva-keep** [comment]
From what I've seen in the code and from what I've tested, everything looks good. In the process, I've removed some unused imports (235d0dc7e21180794a14ceb7223e2039df9bf50f)
