### ISSUE TITLE
Add controller assistant and permissions check to Browser.retrieveScanUpdateStatus() and Browser.updateAllTransferredResources()

### ISSUE THREAD

**Issue by luis100** [keeps/roda#603]
Also, might need to refactor retrieveScanUpdateStatus() first.

**Comment by sleroux-keep** [comment]
updateAllTransferredResources is not used anywhere... refactoring (remove) done.

**Comment by sleroux-keep** [comment]
Implemented / refactored @ 381ddbbbe35570046bac04b7100c0cfb2b8a72cc

Should the updateAllTransferredResources appears on REST API?

Note: in the transferred resource REST, the "Reindex" features for Transferred resource appears in 2 endpoints: /v1/transfers/reindex and /v1/management_tasks/index/reindex . Show the /v1/transferes/reindex be removed?

**Comment by luis100** [comment]
The `transfers/reindex` serves for a bit different purpose, to enable ingest by easily adding transferred resources that are already on the disk to the index.

The may be merged in the future. (in fact, all management tasks should be removed in the future)

**Comment by luis100** [comment]
- [ ] Missing register action
- [ ] Needs refactor so name of Browser methods and BrowserHelper method are the same

**Comment by sleroux-keep** [comment]
Fixed @ ef22743355e9782e979641f41aee57ea547a8ee3

**Comment by luis100** [comment]
@hsilva-keep please review

**Comment by luis100** [comment]
checked.
