### ISSUE TITLE
Check permissions on Browser.retrievePreservationEventViewBundle()

### ISSUE THREAD

**Issue by luis100** [keeps/roda#604]
If an event is related to an AIP, Representation or File, check if the user has permissions to READ the objects.

**Comment by sleroux-keep** [comment]
Implemented.
When a user tries to acess directly to an event in Roda WUI and he doesn't have the READ permissions, a pop is displayed "Do not have permission to do this operation. Details: The user 'sleroux' does not have permissions to READ".

Problem. After clicking on "OK", an "empty event" is displayed:
![eventempty](https://cloud.githubusercontent.com/assets/2727798/19487460/cda06a7c-955a-11e6-9464-674d3b8f9342.png)

**Comment by jmaferreira** [comment]
Why didn’t you fix the “problem"?

**Comment by sleroux3386** [comment]
> The popup with the 'Do not have permission to do this operation....' needs to be replaced with a "You don't have permission..." page.
by @luis100

This only happens when accessing directly an event... No need to fix the problem and then throw away the code...

**Comment by luis100** [comment]
In this case, I guess that the best option would be to redirect to the WELCOME page.

**Comment by sleroux-keep** [comment]
The handling of the AuthorizationDeniedException exception is "global" (AsyncCallbackUtils , used by "all" view panels...).
The "redirect to welcome" is only for the ShowPreservationEvent panel ?

**Comment by luis100** [comment]
I've created a more general issue at #696
Closing this one, as the solution needs to apply to all pages.
