### ISSUE TITLE
Browser.retrieveObjects check object permissions and return type

### ISSUE THREAD

**Issue by luis100** [keeps/roda#605]
If object class is on of AIP, Representation or File, check if user has READ permissions to these objects.

Also, review the return type RODAObjectList<?>, which might better be RODAObjectList<IsRODAObject>.

**Comment by sleroux-keep** [comment]
Implemented @ f5785fa3b791c1d9d55a344dffe00ac8ea4e7f63
Tests (via REST API):
Admin have acess to all AIPS / Representation / File
A user with no admin permission have only access to the AIP he creates

review the return type RODAObjectList<?>, which might better be RODAObjectList. ????

**Comment by luis100** [comment]
This should not be implemented this way but moving the code to the REST API classes and reusing the Browser.find() method to implement the permissions and logging.

**Comment by sleroux-keep** [comment]
RetrieveObject methods and roles removed and replaced with Find.

IndexResult to RODAObjectList method moved to APIUtils class

**Comment by luis100** [comment]
Small fixes to types at 2fbce7c956a8d08fd23586707e972a133e1e5266
Checked.
