### ISSUE TITLE
CAS LDAP configuration instructions and example

### ISSUE THREAD

**Issue by luis100** [keeps/roda#607]
Provide instructions and example on how to set up CAS authentication using an LDAP server.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep @jmaferreira done in PR #596 
https://github.com/rui-castro/roda/blob/rcastro_539_cas_support/doc/cas.md

**Comment by hsilva-keep** [comment]
@rui-castro There are several fixes to be made in the documentation:
- **etc/services/roda.json**: the json provided is not valid
- **etc/cas.properties**: differentiate from values that should be changed (server.name, cas.logout.followServiceRedirects) to the ones that should be added (ldap.url, ldap.useStartTLS, etc.)
- **pom.xml**: clarify which values should be added & which should be changed

**Comment by hsilva-keep** [comment]
I'll create new issue for documentation improvements. Closing this one.
