### ISSUE TITLE
Support representation file and folder edition (DGLAB REQUIREMENT)

### ISSUE THREAD

**Issue by luis100** [keeps/roda#609]
Support folder create, update and delete and file upload and delete. Changes to representations MUST generate a PREMIS event. 

The same applies when this change is done using the REST API.

THIS IS A REQUIREMENT OF THE DGLAB.

**Comment by luis100** [comment]
Still missing:
- [ ] Create PREMIS event whenever the AIP is updated
- [ ] Ability to select representations on the AIP browse and make actions with them
- [ ] Ability to execute PREMIS skeleton plugin and Siegfried on representations and files

**Comment by luis100** [comment]
@nunovieira220 please get back to this task, @sleroux-keep has a lot to do in roda-in

**Comment by nunovieira220** [comment]
Done on 1572eb4e3e0ced7cbc58aaea6ece48348652cfaa. Please review it.

**Comment by luis100** [comment]
- [ ] Edit representation metadata is getting metadata from AIP to base edition
- [ ] Saving from edit representation metadata then jumps to AIP
- [ ] Opening a preservation event from a representation and then going back show the preservation event list of the whole AIP
- [ ] There are some events (e.g. adding a folder manually) giving FAILURE output
- [ ] Outcome detail of representation change type is not sufficient
- [ ] Can't see the inputted reasons on the preservation events.

**Comment by nunovieira220** [comment]
- [ ] Missing (file) target on create file or representation

**Comment by chalkos** [comment]
- [ ] creating an AIP with EAD metadata keeps the scrolling in place, showing only the footer background until I scroll up. When I scroll up, the extra spacing in the bottom is removed.
