### ISSUE TITLE
Digital signature plugin (for DIP) is not working very well

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#612]
Look at the screenshots. The failure reason is easy to understand... but the reporting is wrong.
![screen shot 2016-10-17 at 11 43 36](https://cloud.githubusercontent.com/assets/3181302/19434719/14cbabfc-945f-11e6-884e-882dfa06f6b2.png)
![screen shot 2016-10-17 at 11 42 53](https://cloud.githubusercontent.com/assets/3181302/19434720/14eef77e-945f-11e6-90c3-e5df74fa5dc7.png)

**Comment by nunovieira220** [comment]
This issue should be fixed. Please review it.

**Comment by nunovieira220** [comment]
The reporting is wrong because the table does not support multiple similar rows. I swapped the representation id for its uuid and this should be solved.
