### ISSUE TITLE
The "unoconv" plugin doesn't work

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#614]
It fails on some files for no particular reason.
When it says success.. the created representation does not contain any files. 
The new representation should contain = all the files in the original representation - the converted files + new versions of converted files

**Comment by nunovieira220** [comment]
@jmaferreira What parameters did you pass to the plugin? 
The plugin behaviour when creating a new representations is exactly what you described.

**Comment by luis100** [comment]
@jmaferreira can't reproduce, can you?

**Comment by jmaferreira** [comment]
- When one file fails, the counter of failed AIPs is set to the number of all files processed (instead of 1).
- Sometimes the plugin fails for no reason (unoconv exit code 251)
- Filenames with spaces break the plugin

**Comment by nunovieira220** [comment]
It should be solved in 7ab6ceff4bf7ca5d8f901ef223be308c6c62e9f4. Please review it.

**Comment by luis100** [comment]
@jmaferreira please review if the commit solved the problem

**Comment by jmaferreira** [comment]
I need a new version of the plugins.

**Comment by luis100** [comment]
@jmaferreira what's the status of this issue?

**Comment by jmaferreira** [comment]
Haven’t tested yet.

**Comment by hsilva-keep** [comment]
I've tested what I could, i.e. file whose filename has spaces, and everything worked as expected. 
Just made some minor adjustments to the tests (e41d798bfdc942e2d1233d4a5bfa00a1ead6f94d), but besides that it looks good.
