### ISSUE TITLE
Droid plugin is not working properly

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#615]
Issues:
- Droid is not installed, yet some AIPs reported successful
- When failed, 3 equal lines of the report error are added to the report (add the full path of the command to the report for easier debugging as other plugins do)

![screen shot 2016-10-17 at 12 22 48](https://cloud.githubusercontent.com/assets/3181302/19435826/af4f6560-9464-11e6-8f93-3f7a8a9c06b1.png)
![screen shot 2016-10-17 at 12 25 09](https://cloud.githubusercontent.com/assets/3181302/19435840/c932eb82-9464-11e6-98f3-c5af69fd4b7e.png)

**Comment by nunovieira220** [comment]
DROID plugin is now working correctly.
