### ISSUE TITLE
Change to the AIP actions

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#617]
Information Package

1. Translate new representation to portuguese and call it "Add representation"/Adicionar representação
2. Move the Download representation option to the AIP section
3. Remove the button download schemas (its not necessary)

Search

1. Neste contexto -> Descendentes / Descendants 
2. Neste Pacote de Informação -> Neste pacote / In this package 

![screen shot 2016-10-17 at 13 05 58](https://cloud.githubusercontent.com/assets/3181302/19436876/9632f500-946a-11e6-8f0d-ecc6b9bd36c6.png)

**Comment by nunovieira220** [comment]
There are more hidden download buttons besides those two (download submissions and download documentation). Should I remove them too?

**Comment by jmaferreira** [comment]
Yes. 

Comment those lines until they proven necessary. I guess they will never will!

**Comment by nunovieira220** [comment]
Done.
