### ISSUE TITLE
PDF to PDFA conversion plugin reporting is not well

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#619]
Look at the numbers on the picture

![screen shot 2016-10-17 at 15 11 00](https://cloud.githubusercontent.com/assets/3181302/19441021/0443d10c-947c-11e6-92bf-cb00eef22886.png)

**Comment by nunovieira220** [comment]
@jmaferreira Did RODA stop/crash when executing the plugin?

**Comment by luis100** [comment]
@jmaferreira can't reproduce, can you?

**Comment by jmaferreira** [comment]
Haven't tested yet.

**Comment by jmaferreira** [comment]
The problem has to do with the fact that ghostscript was not installed on the container.
This resulted in a crash of the entire RODA system. Make sure that when the command doesn't exit, it doesn't break the entire system.

**Comment by nunovieira220** [comment]
@jmaferreira I executed a plugin using a tool that was not installed and it did not crash the entire system. Is it possible the problem is happening because you were using docker on Mac?

**Comment by jmaferreira** [comment]
Can be! What can I do then?

**Comment by luis100** [comment]
We can try to update the verapdf library. If that doesn't work, we can try to use verapdf as a REST service (like siegfried).

**Comment by jmaferreira** [comment]
Is the REST service feature already present in VERA? I'm not sure..

**Comment by luis100** [comment]
VeraPDF library was updated but fails due to a bug on the dependencies:

Blocked by https://github.com/veraPDF/veraPDF-library/issues/646

**Comment by luis100** [comment]
https://github.com/veraPDF/veraPDF-library/issues/646 was closed

**Comment by jmaferreira** [comment]
Wont fix.
