### ISSUE TITLE
Add some new questions to FAQ

### ISSUE THREAD

**Issue by luis100** [keeps/roda#62]
Translate these questions and answers to English and post them on FAQ page.

---

 Na seção INGEST, opção PRE-INGEST, encontro alguns itens pré cadastrados. Para que servem, e onde os utilizo?

Os items que aparecem na secção pre-ingest informam o utilizador atual dos planos de classificação que tem permissão para criar SIPs em. Esta lista é apenas informativa.

No RODA, o plano de classificação deve ser criado sempre à priori por um arquivista (ou outro utilizador com essa permissão, como o administrador). Depois, no item de topo do plano de classificação (o fundo na terminologia ISAD), pode escolher na aba "produtores" quais são os utilizadores ou grupos que podem enviar SIPs para esses planos de classificação.

O acordo do plano de classificação no RODA é considerado ser um passo manual de comunicação entre o produtor e o arquivo, que resulta, no final, deste plano ser criado no sistema por um arquivista competente.
- Na seção INGEST, opção SUBMIT, aba SEND PACKET, existe a opção de “Escolher arquivo” para ser carregado, mas, independente do arquivo, sempre recebo o erro de arquivo inválido para o tipo de representação. Então, como definir o tipo de representação por natureza do arquivo?

A opção SEND PACKET serve apenas para enviar SIPs no _formato RODA_. Ficheiros deste tipo têm de ser criados com a aplicação RODA-in, que pode ser baixada na mesma página.

Para enviar um ficheiro na interface online deve utilizar a opção CREATE PACKET.

Nota: pode mudar o idioma do RODA para português na barra no topo direito.
- Na seção INGEST, opção SUBMIT, aba CREATE PACKET, como preencher devidamente os campos para criação de um PACKET válido. E, após criado um PACKET, ele servirá para um único arquivo, uma única vez, ou poderá ser reutilizado posteriormente em arquivos de mesma natureza?
1. Para conseguir criar um pacote deve preencher todos os metadados descritivos, incluindo as data, e tendo certeza que a data final é posterior ou igual à inicial. Nenhum campo deve ficar com o fundo vermelho.
2. É necessário escolher o tipo de pacote e adicionar os ficheiros que quiser.
3. Escolha o ponto no plano de classificação onde este documento será inserido.
4. Carregue em submeter.

Ao lado do Botão submeter tem infomação das razões porque o SIP ainda não é válido ou informação do estado de envio.

NOTA: A opção CREATE PACKET serve apenas para enviar um ficheiro de forma rápida, e não está optimizada para envio de uma grande quantidade de ficheiros. Para isso deve utilizador o RODA-in ou criar programas ou scripts que utilizem as bibliotecas disponíveis para integração com os sistemas existentes ou para efetuar ingestão em lote.

**Comment by hsilva-keep** [comment]
Largely part of this information no longer applies to RODA version 2 nor 3. Closing issue without further actions.
