### ISSUE TITLE
VeraPDF validator plugin has reporting issues

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#620]
![screen shot 2016-10-17 at 15 33 40](https://cloud.githubusercontent.com/assets/3181302/19441850/23e49750-947f-11e6-8743-cc7adfe8c5d4.png)

**Comment by jmaferreira** [comment]
There is also an issue with the reporting. There are a "//" that shouldn't be there in the invocation, and the report should have break lines between files.

![screen shot 2016-10-17 at 15 35 24](https://cloud.githubusercontent.com/assets/3181302/19441932/71608c46-947f-11e6-8fae-98dff0efcee5.png)

**Comment by nunovieira220** [comment]
This issue should be fixed. Please review it.

**Comment by luis100** [comment]
@jmaferreira what is the status of this task?

**Comment by jmaferreira** [comment]
I haven't tested it yet.

**Comment by jmaferreira** [comment]
The veraPDF has reporting issues:

Se
![screen shot 2016-11-10 at 16 07 14](https://cloud.githubusercontent.com/assets/3181302/20184267/ffffe300-a75f-11e6-9131-428ed0b59a29.png)
![screen shot 2016-11-10 at 16 06 32](https://cloud.githubusercontent.com/assets/3181302/20184268/00269676-a760-11e6-9e8c-4d159e921bd3.png)

**Comment by nunovieira220** [comment]
Solved in 7ab6ceff4bf7ca5d8f901ef223be308c6c62e9f4
