### ISSUE TITLE
Improve the way SIPs are moved to SUCCESS or UNSUCCESS folder

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#623]
**Scenario:** SIP is located in **`TRANSFERRED_RESOURCES/a/b/sip.zip`**. It is ingested, unsuccessfully. Then, if the configuration to move after ingest is active, the SIP will be moved into **`TRANSFERRED_RESOURCES/PROCESSED/UNSUCCESSFULLY_INGESTED/a/b/sip.zip`**. If the ingest is conducted again, with the SIP in that location but now with success, it will be moved into **`TRANSFERRED_RESOURCES/PROCESSED/SUCCESSFULLY_INGESTED/PROCESSED/UNSUCCESSFULLY_INGESTED/a/b/sip.zip`** whereas it should be moved into **`TRANSFERRED_RESOURCES/PROCESSED/SUCCESSFULLY_INGESTED/a/b/sip.zip`**.

**How to solve:** if the relative path of the transferred resource starts with either success or unsuccess paths (obtained from configuration), then the resource will be moved into the right place by ignoring that part of the resource path.

**Comment by nunovieira220** [comment]
Done.
