### ISSUE TITLE
In a ingest with one-to-many sip-aip relationship, failure counters are not well calculated

### ISSUE THREAD

**Issue by luis100** [keeps/roda#624]
If one SIP creates several AIPs, if some of the AIPs fail due, for example, invalid descriptive metadata, the counters count several failures, one for each AIP, even when they belong to the same SIP. This can make Successes to become negative.

- [x] Only count one failure for each SIP in which an AIP has failed
- [x] If at least one AIP of SIP fail, then set all other AIPs of that same SIP that have passed to failure, add report that describes why it has failed.
- [x] Strategy to change the plugin name and report counter when creating the new report that describes other failures

**Comment by nunovieira220** [comment]
It should be solved.
