### ISSUE TITLE
On transfer, when we hit refresh there are 2 messages, and one is not translated

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#632]
See attachment.

Do we really need two messages? Can we show just one?

![screen shot 2016-10-20 at 00 22 58](https://cloud.githubusercontent.com/assets/3181302/19541058/7ceeac22-965b-11e6-84d4-f74b88aea59b.png)

**Comment by vitorfernandes87** [comment]
Closed on 5e7604a316a0b3985b80c2966895fe635e4cb5a2
