### ISSUE TITLE
Review AIP ancestor hierarchy fix is not working

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/roda#635]

**Comment by jmaferreira** [comment]
It finishes without counters or report.

**Comment by nunovieira220** [comment]
@sleroux-keep @jmaferreira I can not simulate this issue. The counters are working fine here.

**Comment by jmaferreira** [comment]
@sleroux-keep can you reproduce?

**Comment by sleroux-keep** [comment]
No.
