### ISSUE TITLE
If an AIP, representation or file has associated risks a badge should show up in the UI to alert the user

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#637]
REQUESTED BY DGLAB.

If this is easy to do, just do it now. Otherwise move it to 2.1.

**Comment by luis100** [comment]
Not easy, moving to 2.3

**Comment by hsilva-keep** [comment]
In RODA version 3 this information is presented in AIPs, Representations & Files (right after the title of the first two, in file details for Files).
