### ISSUE TITLE
Button on AIP browse to go to the job report

### ISSUE THREAD

**Issue by luis100** [keeps/roda#639]
If AIP has a ingestJobId, then show a button to allow to go to the job report that created this AIP.

**Comment by nunovieira220** [comment]
Place it on the list of ids bellow the tittle

AIP ID: 1234982390482348
SIP ID: 2904839048239048234
Process ID: 23904823094823048

Maintain the design. On hover becomes blue.

**Comment by nunovieira220** [comment]
Done.
