### ISSUE TITLE
"AIP corruption risk assessment" generates a premis event with "Outcome objects"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#646]
Instead of outcome objects, it should associate the event to each tested file in the AIP as "Source objects".

Is it possible to show the note as text instead of XML? Is there a good reason for this to be XML? Ask faria!

![screen shot 2016-10-20 at 23 49 14](https://cloud.githubusercontent.com/assets/3181302/19580767/67d6c28c-9720-11e6-81fc-cb0837f587e8.png)

**Comment by nunovieira220** [comment]
Done
