### ISSUE TITLE
Plugin that generates the "METS.xml" from the exiting AIP information in the storage layer

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#652]
The specification is here:
http://www.eark-project.com/resources/project-deliverables/53-d43earkaipspec-1/file

The Commons-IP library helps with the creation of this METS.XML file.

## 2016-11-30 hsilva update
**This task depends on [commons-ip task #18](https://github.com/keeps/commons-ip/issues/18).**

So, in order to close this task, two things need to happen:

1. Commons-ip supports E-ARK AIP (build/parse) & new method to generate only METS files (1 for the whole AIP + 1 per each representation; [commons-ip task #18](https://github.com/keeps/commons-ip/issues/18))
2. A plugin exists that processes RODA AIPs, and for each RODA AIP will generate one E-ARK AIP in memory to invoke commons-ip method that generates only the METS files, files that will be added to RODA AIP (using just storage methods to add or update each METS file). Please make sure that this logic of `create or update METS files in RODA AIP using commons-ip` is isolated in order to be able to apply the same logic in other plug-ins that will be created & need METS files created/updated inside each RODA AIP.

**Comment by rui-castro** [comment]
@jmaferreira can you provide a sample METS.xml ?

**Comment by jmaferreira** [comment]
@rui-castro well kind of! Just download this app http://rodain.roda-community.org and create a SIP with it. Unpack the SIP and you'll find a METS.XML on the root folder. This METS.XML is the one found on the SIP specification, but I think its exactly the same. @hsilva-keep do you know if there are any differences?

I've attached an example.

[sakila - IDec234adb-fe77-4a60-bdac-c41c21fd68ed.zip](https://github.com/keeps/roda/files/610183/sakila.-.IDec234adb-fe77-4a60-bdac-c41c21fd68ed.zip)

**Comment by luis100** [comment]
@rui-castro the METS of an AIP is not the same as the SIP. To start, it is not only one METS, every representation has its own METS file. Also, the AIP can have submission and several representations.

Note that the correct approach is to fork the [commons-ip](https://github.com/keeps/commons-ip) project and add AIP support for this library and then use it to create a plugin that does the generation of the METS files for an RODA AIP.

**Comment by hsilva-keep** [comment]
@jmaferreira @rui-castro the major difference between SIP & AIP (aside from some attributes) is the possible existence of the *submission* folder (folder with zero or more files/folders inside; files/folders are the SIPs that were used to create/update the AIP).

But, as @luis100 said, the correct approach would be to add the AIP stuff to the [commons-ip](https://github.com/keeps/commons-ip) library & afterwards use it in RODA. But, @jmaferreira, you need to define the purpose of this RODA plugin: is it supposed to create an E-ARK AIP (with all the METS files & data)? Or should the plugin create just the METS files (ROOT & one for each representation)?

**Comment by jmaferreira** [comment]
The goal is just to create the METS files in the right place inside the existing AIPs in the storage.

**Comment by rui-castro** [comment]
@jmaferreira @hsilva-keep @luis100 this task is named (and was discussed and agreed) as "Plugin that generates the **root** "METS.xml" from the exiting AIP information in the storage layer".
If there are other METS, that is something to be done in a different task.

**Comment by rui-castro** [comment]
@jmaferreira to continue this issue it's necessary to complete https://github.com/keeps/commons-ip/issues/18 first.
Please change the milestone of this issue to **alpha20**.

**Comment by jmaferreira** [comment]
More E-ARK AIPs can be found at http://earkdev.ait.ac.at/eark/pilots/aips/

**Comment by rui-castro** [comment]
@luis100 @jmaferreira done in PR #738. This code depends on new commons-ip PR https://github.com/keeps/commons-ip/pull/20.

**Comment by rui-castro** [comment]
@luis100 ping

**Comment by hsilva-keep** [comment]
@rui-castro Commons-ip PR review is being done. 
And, so that you know, RodaFolderAIP will be removed from commons-ip (and other RODA related stuff) because these implementation dependent classes/resources must stay on the RODA side. It needs to be this way because there are some ENUMs and so on that are only applicable to RODA and if they change in RODA that should not create a need for updating commons-ip as well. And this has implications in the PR that you have done in RODA related to this issue.

**Comment by rui-castro** [comment]
@hsilva-keep ok. If you need something from me, let me know.

**Comment by hsilva-keep** [comment]
@rui-castro as soon as I finish the review, I'll update commons-ip version in RODA. From that moment on, you must retrieve the classes related to RODA that I've removed from commons-ip (I'll give you the last commit id that have them) and add them to RODA. Then, you can change the plugin to use those classes that are now in RODA (and not in commons-ip).

**Comment by rui-castro** [comment]
@hsilva-keep @luis100 any update?

**Comment by hsilva-keep** [comment]
@rui-castro Your code to support E-ARK AIP was merged into commons-ip version alpha25. Now, as I told you before, you need to get the code related with RODA that was removed from commons-ip & add it to RODA (fixing the plugin to use the code placed in RODA). Commons-ip last commit with that code is [11bc5320cb5297d24892cb8045dafd6111e8c359](https://github.com/keeps/commons-ip/commit/11bc5320cb5297d24892cb8045dafd6111e8c359). Any other question? So you can close this issue?

**Comment by rui-castro** [comment]
@hsilva-keep PR #738 updated.
There's one thing missing, preservation Agent metadata.
In RODA AIPs where is the agent information stored, for AIP and representations?

**Comment by luis100** [comment]
Agents are not stored within AIPs but centralized at `storage/preservation/agents`

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep what should this plugin do about agent information?

**Comment by luis100** [comment]
Optionally (by parameter) copy agent PREMIS into metadata/preservation. Do not copy by default.

**Comment by hsilva-keep** [comment]
Code integrated (closed PR #738). @jmaferreira / @luis100, can we close this issue?
