### ISSUE TITLE
Advanced search on job reports

### ISSUE THREAD

**Issue by luis100** [keeps/roda#653]
Allow to search by plugin (not just the last one) and their state.
For example, on ingest the Siegfried plugin can fail (e.g. if the Siegfried server is not running), and ingest be successful nonetheless. We need to be able to search for all reports that have a failure on the siegfried plugin.

This may need support for nested document index in Solr, indexing sub-reports as nested documents, and support for using block join parent queries to search on sub-reports state.

https://cwiki.apache.org/confluence/display/solr/Other+Parsers#OtherParsers-BlockJoinQueryParsers

**Comment by luis100** [comment]
This will be postponed until a real world production case demands it.

**Comment by hsilva-keep** [comment]
Since RODA version 3 basic search is available for searching in job reports. Closing this until a real need occurs.
