### ISSUE TITLE
Showing job when created via REST API problems

### ISSUE THREAD

**Issue by luis100** [keeps/roda#659]
Could not find sipToAipPlugin in pluginsInfo.

**Comment by luis100** [comment]
Use 3d993684a29eb1b56e9346a9509a8130e5ddc714 to check, as it has debug messages and is prepared to inject default values and is guarding against not found sip to aip plugins

**Comment by luis100** [comment]
@nunovieira220 please give priority to this issue

**Comment by nunovieira220** [comment]
Issue solved.
