### ISSUE TITLE
Plan the migration of legacy data

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#661]
Analyse data, think about the right approach. Quick and dirty approach.

**Comment by rui-castro** [comment]
Migration will be done using a DataSource for Repository Integration Pipeline.

**Comment by rui-castro** [comment]
@jmaferreira this issue can be closed, right?

**Comment by jmaferreira** [comment]
Yes.

**Comment by rui-castro** [comment]
@jmaferreira close it, then :-)
