### ISSUE TITLE
Migration of legacy data

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#662]
Based on the planning defined on the previous sprint.

**Comment by rui-castro** [comment]
@jmaferreira until the data is ready this issue should not have a milestone, right?

**Comment by rui-castro** [comment]
@jmaferreira ping

**Comment by jmaferreira** [comment]
Milestone added.

**Comment by rui-castro** [comment]
@jmaferreira @luis100 the data is ready to continue with this task?

**Comment by jmaferreira** [comment]
Still waiting for the original data to be migrated.

**Comment by hsilva-keep** [comment]
A sprint will be created as soon as data is available.

**Comment by hsilva-keep** [comment]
This has been done already. Closing it.
