### ISSUE TITLE
Search pre-filters results can be overwritten by default find all results

### ISSUE THREAD

**Issue by luis100** [keeps/roda#663]
If using a pre-filter, like listing all AIPs of a Job or listing all descendants, two searches are made, the default search for everything, and then the search with the filter.

If the default search for everything takes more time to respond that the other, it can come after and overwrite the results.

Be sure that in the case of search pre-filters being used in Search, only one search is made.

**Comment by vitorfernandes87** [comment]
Closed on 648f81030f5be653d4fd7de234b4885a6a2a360c
