### ISSUE TITLE
Index REST endpoint should be able to produce XML

### ISSUE THREAD

**Issue by luis100** [keeps/roda#664]
Currently supporting JSON and CSV, could also support XML output.

**Comment by nunovieira220** [comment]
No easy way to configure the system to produce XML of classes with generic types was found.
As this is not a priority, the issue will be pushed to a future roadmap.

**Comment by luis100** [comment]
Just needs some annotations, done at 239be3740d16172b1ef3582c87f8391b5b2bf599
