### ISSUE TITLE
Improve CAS documentation

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#666]
There are several fixes to be made in the documentation (doc/cas.md):
- **etc/services/roda.json**: the json provided is not valid
- **etc/cas.properties**: differentiate from values that should be changed (server.name, cas.logout.followServiceRedirects) to the ones that should be added (ldap.url, ldap.useStartTLS, etc.)
- **pom.xml**: clarify which values should be added & which should be changed

**Comment by rui-castro** [comment]
@hsilva-keep done in PR #692

**Comment by luis100** [comment]
Checked and integrated into lf_dev branch 61f21704a8a39178fb25a4d824ad63101fd1dac6
