### ISSUE TITLE
Support suggestions on any field of advanced search

### ISSUE THREAD

**Issue by luis100** [keeps/roda#669]
- [ ] Add a new type for the advanced search configuration (e.g. `text_with_suggestions`)
- [ ] Use convention for fields, e.g. parameter is "fieldName" and both `fieldName_ss` and `fieldName_txt` must be used
- [ ] Change indexing configuration and advanced search configuration to support suggestion in `level` field.

**Comment by vitorfernandes87** [comment]
@luis100 @sleroux-keep 
Please check if the commit 61c37c1ff0253084c98a28b0d966996c8adda7ac solves this issue

**Comment by hsilva-keep** [comment]
As @vitorfernandes87 stated, it is already possible to configured a field (any type, i.e. item, representation, file, whatever) as suggest. I've confirmed that it actually works by changing roda-wui.properties to configure item > level as suggest. Afterwards, I've commented out as that field is already configured as controlled vocabulary. Closing this issue.
