### ISSUE TITLE
If we run the siegried plugin on an AIP that has files without the PREMIS object (e.g. because they were uploaded directly uploaded to the representation) it doesn't fail, but it doesn't register any information either

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#674]
The problem relies on the fact that the plugin needs the PREMIS skeleton to attach its output. Without it it doesn't work.

Maybe it should check for this and create the skeleton when necessary or warn the user about this fact. Ask @luis100 for an opinion on the behaviour.

**Comment by luis100** [comment]
It should fail and warn the user that PREMIS is missing.

**Comment by luis100** [comment]
@nunovieira220 please check if this is dome

**Comment by nunovieira220** [comment]
It is. It creates a base PREMIS representation if it does not exist.
