### ISSUE TITLE
In the "example-configs" folder there are client side messages in "i18n" folder. If these cannot be changed without compiling the repository, they should be removed from the examples

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#681]

**Comment by hsilva-keep** [comment]
@jmaferreira this happens because all files in the classpath whose path starts with /config/i18n are copied into example-configs. We need to program a way of defining inclusions/exclusions to avoid the situation you've mentioned.

**Comment by nunovieira220** [comment]
Solved on 86765ac10085de9682262c20c8b26cb31c3f0667
