### ISSUE TITLE
Broken design on a "Add" button

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#682]
There might be other instances of this...

![screen shot 2016-11-04 at 12 29 16](https://cloud.githubusercontent.com/assets/3181302/20005485/64969ec4-a28a-11e6-9efd-80311e99f652.png)

**Comment by jmaferreira** [comment]
@luis100 This is your game. You should fix it quicker.

**Comment by nunovieira220** [comment]
Solved 91f2f0dd92acfdb13ca68a07d1327a5c5d575a62
