### ISSUE TITLE
Undecent graphic. Make bigger

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#684]
![screen shot 2016-11-07 at 09 13 22](https://cloud.githubusercontent.com/assets/3181302/20052366/a5d108f0-a4cb-11e6-8cd7-0d7e7a533cc8.png)

**Comment by hsilva-keep** [comment]
@jmaferreira this is most certainly due to the space taken by the labels. We'll have to find a way of making the graphic independent of the amount/length of the labels. By the way, nice issue title.

**Comment by jmaferreira** [comment]
Yes. It has to be one of the big rectangulars.

**Comment by luis100** [comment]
Changed to an horizontal bar diagram.
