### ISSUE TITLE
Remove blue borders from buttons (Safari issue)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#69]
Solution: 
http://stackoverflow.com/questions/20340138/remove-blue-border-from-css-custom-styled-button-in-chrome

Example:
![screen shot 2015-02-18 at 12 01 17](https://cloud.githubusercontent.com/assets/3181302/6246922/0fe82a02-b766-11e4-873f-18457f75934f.png)

**Comment by luis100** [comment]
Design overhaul in version 2.0.0 fixes this.
