### ISSUE TITLE
Test filesystem limit for AIPs on the same directory

### ISSUE THREAD

**Issue by luis100** [keeps/roda#693]
Try to discover the limit number of AIPs on the following file systems: EXT4, ZFS, XFS.
Generate AIPs up to a order of magnitude and test ingest, reindex, see metadata, download AIP, and remove.

Increment the order of magnitude until a limit is found (e.g. 1 million, 10 million, 100 million, 1 billion, 10 billion, 100 billion, 1 trillion, etc.)

**Comment by luis100** [comment]
Some tests scripts were produced, but results highly depend on the specific systems and storage architecture and conditions.

**Comment by jmaferreira** [comment]
Let me report on this. I've made a small scale test about creating a few million folders under the same folder. What happens is that the process (bash script) fails after a small limit of folders (a few thousands) if we are using EXT3. 

If we mount ZFS filesystem and run the test on that one, the process works fine.

The conclusion is...ZFS is a requirement for local storage filesystems that will be supporting RODA.
