### ISSUE TITLE
WUI should deal better with authorization denied

### ISSUE THREAD

**Issue by luis100** [keeps/roda#696]
1. If the user is guest present (also when session has expired) present a information dialog stating that user has not permissions or his session has expired, and present a button to go to LOGIN, or a button to CANCEL and go to the Welcome page
2. If the user is not guest present a information dialog stating the user has not permissions perform the operation. If the operation needs to occur to open a new page, then go back to the previous page, or the Welcome page if it does not exist.

**Comment by hsilva-keep** [comment]
#510 is related to this issue. @luis100 should #510 be closed in favour of this issue?
