### ISSUE TITLE
JobReport source objects ends up empty when SIPs are removed or moved after ingest

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#700]
The list of SIP files that have taken part on an ingest job should be kept forever. It cannot disapear from the resource just because the files have been moved.

@luis100 Analyse this and assign to a developer.

**Comment by luis100** [comment]
Hide list if empty and job is complete.

**Comment by hsilva-keep** [comment]
@nunovieira220: where @luis100 said "job is complete" it should be "job is in final state" (which map to several states; see https://github.com/keeps/roda/blob/hsilva_dev/roda-common/roda-common-data/src/main/java/org/roda/core/data/v2/jobs/Job.java#L217)

**Comment by nunovieira220** [comment]
Solved on 9182ec2a713f5e157de0aa7265f1e581583f9468
