### ISSUE TITLE
PREMIS Events for actions that update AIPs

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#704]
For each specific action it is needed the PreservationEventType, the event description and the outcome detail and, in some cases, the entity the event will be associated with (for example, when creating a file, the event should be on its representation?).

**Comment by jmaferreira** [comment]
@nunovieira220 What do I need to do?

**Comment by nunovieira220** [comment]
@jmaferreira Using an example, when creating a file on an AIP, what preservation event type, event description and outcome detail should the PREMIS event have (basically the content of the events related to updating AIPs)? And will it be associated to its representation or the file itself since it was its creation?

**Comment by jmaferreira** [comment]
Deleting a file from an AIP should create the following event. The event should be associated to the representation, as the file is going to be deleted:

**Event type:** 
Deletion

**Event description:** 
The file <filename> has been manually removed from the AIP <AIP id>. The following reason has been reported by the user:
<text collected from the user input popup>

**Outcome detail:** 
Success

**Comment by nunovieira220** [comment]
@jmaferreira There are more cases of AIP updates like renaming folders, moving AIPs, changing representation type, etc. Which situations really need an event created?

**Comment by jmaferreira** [comment]
Please provide a complete list of actions so that we can reflect.

**Comment by nunovieira220** [comment]
- Update and move AIP
- Create, update and remove representation
- Create, update, remove and move file/folder
- Rename folder
- Change representation type
- Change AIP permissions

I do not know if there is any more examples of AIP updates.

**Comment by nunovieira220** [comment]
Done on 1572eb4e3e0ced7cbc58aaea6ece48348652cfaa.
