### ISSUE TITLE
REST API last report with non existing id gives (last?) report

### ISSUE THREAD

**Issue by luis100** [keeps/roda#708]
It should give NotFoundException (404) instead.

**Comment by luis100** [comment]
Also, don't use count to find out a specific limit, and use findAll() to get all items without a limit.

**Comment by luis100** [comment]
Use int start and limit, do the parsing in the ReportsResource.

**Comment by luis100** [comment]
In `listTransferredResourcesReportsWithSIP` don't find AIPs and then find Job Reports. Search for SIP ids directly on job report.

**Comment by nunovieira220** [comment]
Done on 74eb131ea911e095a64f68d1530a85a96e8303f6
