### ISSUE TITLE
Misplaced "Cancel" button on "Reset password" screen

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#710]
![screen shot 2016-11-24 at 13 36 06](https://cloud.githubusercontent.com/assets/3181302/20600333/0ac60aa8-b24b-11e6-8f98-363aefe010be.png)

**Comment by chalkos** [comment]
Done in 57dc7b0
![screenshot](https://cloud.githubusercontent.com/assets/98429/20979237/035169f8-bca4-11e6-9c21-bfce5f68a88a.png)
