### ISSUE TITLE
Representation date created and updated

### ISSUE THREAD

**Issue by luis100** [keeps/roda#712]
Add the following fields to representation and changed model methods to maintain this information. Show date created on the representation list and all other information in the representation panel.
```java
private Date createdOn = null;
private String createdBy = null;
private Date updatedOn = null;
private String updatedBy = null;
```

**Comment by luis100** [comment]
Allow old representations (without this information) to be parsed by the new implementation and inherit this information from AIP in case it doesn't exist (if inheritance is hard or non-performant, create plugin to fix it).

**Comment by luis100** [comment]
@nunovieira220 is this already done?

**Comment by nunovieira220** [comment]
Done with a migration that can update the new representation fields with AIP information
