### ISSUE TITLE
DIP dynamic configuration and variable replacement

### ISSUE THREAD

**Issue by luis100** [keeps/roda#713]
- [x] Create a new field for DIP to identify the "type" it belongs to. For example a DIP created by the database visualization toolkit can have a "type: dbvtk".
- [x] Instead of "openExternalURL" and "deleteExternalURL" in DIP have "properties" which has a key-value map. Example: `properties: {"database": "1234"}`
- [x] Have configuration in `roda-core.properties` that define the `openExternalURL` and allows to use variables based on the properties of the DIP. Example: `dip.dbvtk.openExternalURL: http://127.0.0.1:9999/index.html#database/{{database}}`
- [x] Have configuration in `roda-core.properties` that define the `deleteExternalURL`, with variable substitution as above, and also allow to define the HTTP method to use. Example: 

```
dip.dbvtk.deleteExternalURL: http://127.0.0.1:9999/api/v1/manage/database/database/{{database}}/destroy 
dip.dbvtk.deleteExternalURL.method: GET
``` 
- [x] Create IndexedDIP that has field openExternalURL pre-calculated

**Comment by nunovieira220** [comment]
Solved on 35957f0226f1e2e859cc4201c5a90d91e248c5ad
