### ISSUE TITLE
Call delete external URL when deleting a DIP

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#717]

**Comment by nunovieira220** [comment]
Solved on c81aa99503aaeb1f4c623ea37d0ff2ea17fc91d0. @chalkos please review it with the dbptk plugin.

**Comment by chalkos** [comment]
Code looks fine. When I implement the delete part I will get back to this.

**Comment by chalkos** [comment]
b2db026 fixes DIP retrieval and the removal works in the REST API. still missing the UI to do it.

**Comment by luis100** [comment]
checked
