### ISSUE TITLE
Configuration mismatch between Dublic Core used by RODA & RODA-in

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#726]
RODA-in has Dublin Core metadata schema configured as
- TYPE="DC"
- VERSION="SimpleDC20021212"

whereas RODA

- TYPE="DC"
- VERSION=""

This makes RODA, when ingesting SIP from RODA-in:
1. Storing metadata info. in AIP.json as `DC version SimpleDC20021212`
2. Ingesting info. is stored into the index using `DC` stylesheet (as a fallback solution as no `DC version SimpleDC20021212` is found)
3. Validating xml file against the `DC` schema (as a fallback solution as no `DC version SimpleDC20021212` is found)
4. When disseminating xml in html, `DC` stylesheet is used (as a fallback solution as no `DC version SimpleDC20021212` is found) **BUT WUI says dc.xml in the metadata tab instead of "Dublin Core" because it does not find any i18n for `DC version SimpleDC20021212`**.

Perhaps the easier solution for this mismatch is ensuring that WUI also uses this fallback stratagy and shows i18n for `DC`if no `DC version SimpleDC20021212` i18n is found. What do you think @luis100 ???

**Comment by jmaferreira** [comment]
@sleroux-keep You worked on this. Is there a reason why DC is not yet compatible with RODA? Can we fix it on the RODA-in side?

**Comment by sleroux-keep** [comment]
DC is compatible with RODA... The SimpleDC20021212 is sent by RODA-IN since JUNE, and I never looked at the tab name (the crosswalks and schemas were working).

Two solutions:
- The fallback should also be used in the metadata tab (if there is a fallback mechanism, the fallback should be implemented in ALL sections, not just the crosswalks and schemas...)
- Set the dc version of roda to SimpleDC20021212...

**Comment by jmaferreira** [comment]
I've tried to fix it on the RODA-in side by setting the version to nothing on the config. 

`<mdRef ID="dc.xml" LOCTYPE="URL" MDTYPE="DC" MDTYPEVERSION="" xlink:type="simple" xlink:href="metadata%2Fdescriptive%2Fdc.xml" SIZE="418" CREATED="2016-12-04T18:57:54.753Z" CHECKSUM="6DB8372DA31E872477463615F5B124529D50D060589C87FA6DC1232B762A4144" CHECKSUMTYPE="SHA-256"/>
`

The end result was the same. RODA doesn't recognise the metadata schema that the SIP specifies.

**Comment by jmaferreira** [comment]
Can we fix this monday morning?

**Comment by sleroux-keep** [comment]
"I've tried to fix it on the RODA-in side by setting the version to nothing on the config." -> I have to check how the metadata version is handled by roda-in and also how an empty metadataversion is handled by roda (probably roda doesn't handle empty version very wel...).
"Can we fix this monday morning?" -> yep.

**Comment by sleroux-keep** [comment]
Added fallback to roda (descriptive metadata label):
https://github.com/keeps/roda/commit/d180ee2af1355ce8f3abd0977b25430803b75688

For roda-in, when the metadataversion exist but is empty, the MDVERSION is set to empty in the METS file. To remove the MDVERSION, just remove / comment the line metadata.XXX.version from configuration.

**Comment by jmaferreira** [comment]
@sleroux-keep ,

On RODA, the DC version SimpleDC20021212 is **NOT YET** configured. 
The schemas that come with RODA-in, namely EAD version 2002 and DC version SimpleDC20021212, **MUST** be set on RODA. The ingest should be flawless, as well as editing, indexing and everything else. Support for these schemas MUST BE COMPLETE.

Please fix this ASAP.

**Comment by sleroux-keep** [comment]
Added SimpleDC2002-12-12 to RODA (sleroux-dev branch).

NOTE: I've updated some "code" to fix issues related to lowercase for the version... @hsilva-keep may need to review...

![dc1](https://cloud.githubusercontent.com/assets/2727798/20922813/665d5a38-bba1-11e6-989b-3a70f101efd0.png)
![dc2](https://cloud.githubusercontent.com/assets/2727798/20922814/667731ce-bba1-11e6-838b-8e7ce5d40e6a.png)

**Comment by hsilva-keep** [comment]
Reviewed. Everything looks ok. Closing issue as code was already merged.
