### ISSUE TITLE
Risk assessment plugins should update incidences and not just add more

### ISSUE THREAD

**Issue by luis100** [keeps/roda#730]
For example, with the file not characterized risk assessment plugin, when a file is detected not to have the sufficient characterization information, and incidence is create. 

If, as a result, then the file is identified and its metadata is updated, after running the plugin again, the incidence should be updated to be mitigated.

Also, if the same file is detected to be lacking characterization, it should not create yet another incidence about the same, it is simply a verification of the same incident.

The same with the format representation information risk assessment plugin.

**Comment by rui-castro** [comment]
@luis100 done in PR #748 
Please change the milestone to 2.0.0-alpha20.

**Comment by luis100** [comment]
checked and merged into lf_dev at e928e48643cc3aaa92ed30843b8b3904ca77230e
