### ISSUE TITLE
Change name/description from plugins that formerly were only applicable to AIP to something that doesn't make reference to the concept of AIP

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#734]
E.g. https://github.com/keeps/roda/blob/b9f87de0924c2b7d28800ab279a083e1a3fdfd1f/roda-core/roda-core/src/main/java/org/roda/core/plugins/plugins/ingest/characterization/SiegfriedPlugin.java

**Comment by jmaferreira** [comment]
I believe the title is self-explanatory. If not, please ask.

**Comment by nunovieira220** [comment]
Changed on 67a55c7796ffcd1db706cf82d036fc5ae5a81279
