### ISSUE TITLE
Add software license to every file in the source code

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#74]
See example at https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/app/checker/ChecksumChecker.java

**Comment by hsilva-keep** [comment]
Done in c6a85210adcd10bb58899ab5674757fcf730eb9b using the same plugin DSpace uses. 
File LICENSE_HEADER.txt has the text with the license that will be inserted in each .java file. It may contain variables that will be replaced dynamically (the variables are defined in the plugin configuration inside pom.xml). 
Using mvn license:check, mvn license:format and mvn license:remove one can check if there is any java file without the license text, one can add/update the license text in each java file or one can remove the license text from each java file.
