### ISSUE TITLE
There's no support for AND operator in current FilterParameter implementations

### ISSUE THREAD

**Issue by rui-castro** [keeps/roda#740]
## Description

With current implementations of `FilterParameter` there's no way to do this types of queries `(a AND b) OR c`.
I think, there should be a `AndFilterParameter` that takes a list of `FilterParameter` and does AND between all of them.

A practical example of would be:
search for a `Format` that has name `N` AND version `V` OR  name `N`.
```
(format.name=name OR format.alternativeDesignation=name) AND format.version=1.5
OR 
(format.name=name OR format.alternativeDesignation=name)
```

**Comment by hsilva-keep** [comment]
Done since 06170eb648150c248a6e82c3eeb3faf5c5249d9a.

Here's the code for doing the query that you want (please confirm it):
```java
Filter f = new Filter();
String name = "name";
List<FilterParameter> mainOrList = new ArrayList<>();
OrFiltersParameters mainOr = new OrFiltersParameters("mainOr", mainOrList);
f.add(mainOr);
    
List<FilterParameter> leftAndList = new ArrayList<>();
FilterParameter leftFilter = new AndFiltersParameters("leftAnd", leftAndList);
mainOrList.add(leftFilter);
List<FilterParameter> leftLeftOrList = new ArrayList<>();
leftLeftOrList.add(new SimpleFilterParameter("format.name", name));
leftLeftOrList.add(new SimpleFilterParameter("format.alternativeDesignation", name));
leftAndList.add(new OrFiltersParameters("leftLeftOr", leftLeftOrList));
leftAndList.add(new SimpleFilterParameter("format.version", "1.5"));

List<FilterParameter> rightOrList = new ArrayList<>();
FilterParameter rightFilter = new OrFiltersParameters("rightOr", rightOrList);
mainOrList.add(rightFilter);
rightOrList.add(new SimpleFilterParameter("format.name", name));
rightOrList.add(new SimpleFilterParameter("format.alternativeDesignation", name));

System.out.println(SolrUtils.parseFilter(f));
```

**Comment by luis100** [comment]
@hsilva-keep the name here is superfluous, create it from a constant and hide it on the AndFilterParameters and OrFilterParameters constructor.

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep I would also suggest to name the classes `AndFilterParameter` and `OrFilterParameter`, since both classes are implementations of `FilterParameter`.

**Comment by hsilva-keep** [comment]
@luis100 done since 03a360e044eb0acf1f287bdf711ca9bf560978b9 .
@rui-castro more improvements could be done, but none will be done right now.
