### ISSUE TITLE
Create list method in ModelService for LiteRODAObject

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#752]
The list model should efficiently (e.g. when returning an AIP, it should be done only using the storage info avoiding this way loading the AIP,json) return LiteRODAObjects.

Commit c8969037da6ee411132610222a18aac64b10cb51 puts available the class LiteRODAObject & the factory LiteRODAObjectFactory.

**Comment by nunovieira220** [comment]
Created on 1c20d5f02024f6ab479ffd0a61a45e5152bda465
