### ISSUE TITLE
Reduce size of IndexedPreservationEvent to reduce index size

### ISSUE THREAD

**Issue by luis100** [keeps/roda#760]
Create a new POJO `PreservationEvent` to keep all information needed for the `PreservationEventViewBundle`. Change `PremisV3Utils.getSolrDocument()` to return PreservationEvent or other if appropriate. 

Reduce the information in the IndexedPreservationEvent and the related index to reduce its size down to the absolutely necessary to present the information in the tables and supported filters and facets.

**Comment by hsilva-keep** [comment]
Its done since e46711a0f0be64e0950afa98bc0d4a35ff0b4e8c. From my tests, a reduction of about 30% is expected.
