### ISSUE TITLE
Support download for a directory within a DIP

### ISSUE THREAD

**Issue by luis100** [keeps/roda#769]
Right now, when trying to download a DIP file that is a directory the following message appears.

`GET /api/v1/dipfiles/ca2b0294-58cf-3c4f-b070-f404451b1f0c?acceptFormat=bin`

```xml
<apiResponseMessage>
<message>
RequestNotValidException: Looking for a binary but found something else
</message>
<type>error</type>
</apiResponseMessage>
```

Check if the file is a directory, and if so download all its contents as a ZIP file.

**Comment by nunovieira220** [comment]
Done on 2b89a53ba50f1eb5ffc0d9d7b8c7b7b0b594e782
