### ISSUE TITLE
Remove AbstractConvertPlugin.orderParameters() method and re-implement order

### ISSUE THREAD

**Issue by luis100** [keeps/roda#772]
Use other backend map implementation that maintains order or add orderWeight in each parameter to re-order them.

Current implementation give a `NULL` plugin parameter because the following code does not find the `PLUGIN_PARAMS_COMMAND_ARGUMENTS` in the params because these params have not been changed by overriden `getDefaultParameters()`.

```java
protected List<PluginParameter> orderParameters(Map<String, PluginParameter> params) {
    List<PluginParameter> orderedList = super.orderParameters(params);
    orderedList.add(params.get(RodaConstants.PLUGIN_PARAMS_COMMAND_ARGUMENTS));
    return orderedList;
}
```

**Comment by nunovieira220** [comment]
The NULL issue was solved on a47d6c89baf3f51c7ce27ec0e944e3b763000a3c, however the parameter ordering approach did not change. Other immediate approaches would bring similar issues when using plugins with more than one superclass level.
