### ISSUE TITLE
Storage to support keeping binaries as a reference

### ISSUE THREAD

**Issue by luis100** [keeps/roda#786]
Instead of keeping the binaries themselves, keep a reference to the binary on an external system and available by a protocol, e.g. http, file, etc. 

All processes of RODA should support their normal operation using binaries as reference, from ingest to access.

This should enable digital preservation on existing data without moving or copying information to a controlled RODA environment.

**Comment by luis100** [comment]
Setting to unplanned until the need arises from current real world implementations.

**Comment by hsilva-keep** [comment]
If no need for this occurred during 2 years, I'm closing the issue without further actions.

**Comment by jmaferreira** [comment]
This is still an important thing.

**Comment by wbz-hot** [comment]
> Instead of keeping the binaries themselves, keep a reference to the binary on an external system and available by a protocol, e.g. http, file, etc. 
> 
> 
> 
> All processes of RODA should support their normal operation using binaries as reference, from ingest to access.
> 
> 
> 
> This should enable digital preservation on existing data without moving or copying information to a controlled RODA environment.

It's very important

**Comment by luis100** [comment]
Note that this issue is currently being developed as part of RODA 5, and initial implementation is already done for https://github.com/keeps/roda/releases/tag/v5.0.0-alpha1
