### ISSUE TITLE
Create unit test for ingest of desc. metadata invalid against schema

### ISSUE THREAD

**Issue by luis100** [keeps/roda#788]

**Comment by hsilva-keep** [comment]
Create an AIP with a descriptive metadata file in xml that is syntactically valid but semantically invalid (against a xml schema).
- [ ] Check if that xml schema is in the resources (use RodaCoreFactory.getConfigurationFile...). Fail if it doesn't exist
- [ ] Create job that uses DescriptiveMetadataValidationPlugin & check for the end result. The associated report must have the state failure for the test pass.

**Comment by nunovieira220** [comment]
Added on d85ea0256c33eb8a40838b75ff4a606c10fe4571
