### ISSUE TITLE
Review developer info

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#790]
Remove obsolete instructions from https://github.com/keeps/roda/wiki/Developer-guide#-how-to-get-the-source-code

**Comment by jmaferreira** [comment]
@nunovieira220 can you please take on this task?

**Comment by nunovieira220** [comment]
I think the information is now updated. @hsilva-keep or @jmaferreira please review it.

**Comment by jmaferreira** [comment]
I’m really not the best person to advise here. Hélder?

**Comment by hsilva-keep** [comment]
Reviewed.
