### ISSUE TITLE
Button titles are smaller than facet titles on the sidebar

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#791]
Is it just a small CSS issue or is it intentional?

**Comment by jmaferreira** [comment]
Can I see it live? Call me into your office when please!

**Comment by jmaferreira** [comment]
I guess they are the same size. Maybe using the same classes you'd be better.

**Comment by nunovieira220** [comment]
Solved on ed202b91a908ccc45dced05742cac3255bb90388
