### ISSUE TITLE
Translate to PT the help page and its subpages

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#793]

**Comment by nunovieira220** [comment]
Help pages translated on 7720f6dd86d5d43fc6ac4782fd533e3a1167ebc0

**Comment by nunovieira220** [comment]
@jmaferreira please review them

**Comment by jmaferreira** [comment]
- The link under "Descarregar e correr demo" is not pointing to the right anchor.
- Descarregar e correr demo > Descarregar e correr o demonstrador
- Instalar novos formatos de metadata descriptiva > Instalar novos formatos de metadados descritivos
- Passar "Adicionar tópico de ajuda nesta página" para debaixo do item "Configuração"

**Comment by nunovieira220** [comment]
Done on 1053ed57a8bd79b0ce8e8545b5c7996a81047c2e
