### ISSUE TITLE
Translate into PT the What is RODA page

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#794]
There is a page that is half translated.
...?locale=pt_PT#theme/What_is_RODA.html

**Comment by nunovieira220** [comment]
Translated on 46772d6172a0bdec6b320d8bc2ea26e76b84970f

**Comment by nunovieira220** [comment]
@jmaferreira please review it

**Comment by jmaferreira** [comment]
Phrases with problems:

- que este seja melhorados >  que este seja melhorado
- re-configurado > reconfigurado
- acções > ações
- técnica do ficheiros  > técnica dos ficheiros 
- Todos os formatos de metainformação descritiva (baseados em XML) são suportados.  > Todos os formatos de metainformação descritiva são suportados desde que baseados em XML. 
- são guardados juntos dentro do AIP (Pacote de Informação de Arquivo) para facilidade de replicação e escalabilidade > são guardados dentro do AIP (Pacote de Informação de Arquivo) para maior facilidade de replicação e escalabilidade
- visualizadores embebidos no seu navegador Web.  > visualizadores Web embebidos. 
- distintas podes ser disponibilizadas para o mesmo > distintas podes ser disponibilizadas para o mesmo 
- incluíndo > incluindo 
- O RODA incluí funcionalidade de adminstração avançadas como gestão de utilizadores, relatórios, configuração dos fluxos de ingestão, registo de atividade, gestão de permissões, etc. > O RODA inclui funcionalidades de adminstração avançadas como gestão de utilizadores, relatórios, configuração de fluxos de ingestão, registo de atividade, gestão de permissões, etc.
- O RODA incluí a funcionalidade de directório de riscos que permite os gestores de preservação organizar e mitigar as ameaças e oportunidades que circundam o ambiente do repositório. > O RODA inclui um directório de riscos que permite aos gestores organizar e mitigar ameaças e oportunidades que circundam o ambiente do repositório.
- O RODA suporta qualquer formato de ficheiro e esquemas de metadados (desde que baseados em XML).  > O RODA suporta qualquer formato de ficheiro e esquemas de metadados (desde que baseado em XML). 
- caracterizaçao > caracterização 
- Ferramenta de conversão de formatos especializada  > Ferramentas de conversão de formatos especializadas
- Incluí aspetos relacionados com recursos humanos > Inclui aspetos relacionados com recursos humanos 
- que é o pré-requisito à confiabilidade > que é o pré-requisito para a confiabilidade
- RODA implementa estam alinhados com as unidades funcionais e terminologia definada no OAIS, o que simplifica e grande modo a adoção e a usabilidade. > RODA implementa estão alinhados com as unidades funcionais e a terminologia definida no OAIS, o que simplifica de grande modo a adoção e a usabilidade.

**Comment by nunovieira220** [comment]
Done on 1053ed57a8bd79b0ce8e8545b5c7996a81047c2e
