### ISSUE TITLE
Add a help page about how to add entries to the help page

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#795]
There are two types of help:

- Introductory text on each page
- Help page

Add info about both cases. PT and EN

**Comment by nunovieira220** [comment]
Added on daa18b7bacd2b90058ffdccc7f81c57e7a4515f0

**Comment by nunovieira220** [comment]
@jmaferreira please review it

**Comment by jmaferreira** [comment]
Its still pretty rough... we need more information (e.g. folders where to put stuff and files to edit)

**Comment by nunovieira220** [comment]
Improved on 11dba3e3637d85c226e8489ea0fe169dd61f3514
