### ISSUE TITLE
"Origination" label (EAD 2002) is being shown even though it is not filled in

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#796]
![screen shot 2017-01-31 at 13 55 57](https://cloud.githubusercontent.com/assets/3181302/22467587/23ce44aa-e7bd-11e6-84ef-7f70ab18f91c.png)

**Comment by sleroux-keep** [comment]
Fixed @ f882b3f38e3a12d8bff50a345afd32b5e4ad96ac

**Comment by hsilva-keep** [comment]
I've just tested (42e06380cd5561ee695389c781cd7a1213febc28) and it's indeed fixed.
