### ISSUE TITLE
"Representation type" should be a controlled vocabulary

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#798]

**Comment by luis100** [comment]
Changes to the model should occur on milestone 2.1.0.
The controlled vocabulary should come from roda core or wui configurations.
@jmaferreira please define the ones by default.

**Comment by jmaferreira** [comment]
Which types do we have at the moment?

**Comment by nunovieira220** [comment]
None, It is not a controlled vocabulary. It is just a text field.

**Comment by jmaferreira** [comment]
Yes. I know... but what kind of representations are we coping at the moment in our clients?

For example, RODA-in already sets this vocabulary based on the commons IP + SIP specification.

**Comment by nunovieira220** [comment]
On RODA-in the representation types used are: GeoRasterGeoTiff, GeoVectorXML, MIXED, MOREQ, OTHER, SIARD, SIARD2, SIARDDK, SMURF, SMURFERMS, SMURFSFSB.

**Comment by jmaferreira** [comment]
Lets start with those.
I should display a combobox or a suggest box based on this vocabulary.

**Comment by nunovieira220** [comment]
Done on f3426a396be77a22d41122482f7baeba9c19554b
