### ISSUE TITLE
The AIP '7a36a115-0e99-4b35-876f-2e887878660c' has not been manually deleted.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#799]
I believe the sentence should be

_The AIP '7a36a115-0e99-4b35-876f-2e887878660c' has been manually deleted._

As that was exactly what happened. Also, It would be nice to have the name of the file in the message.

![screen shot 2017-01-31 at 14 15 44](https://cloud.githubusercontent.com/assets/3181302/22468388/fc505dc0-e7bf-11e6-954c-d38099a09ad7.png)

**Comment by nunovieira220** [comment]
Solved on 36aa65a008e630a68457e3330a98aa1101304509
