### ISSUE TITLE
Error "ticket permission verification is not supported" when using CAS

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#804]
Steps to reproduce the problem:

1. Use CAS
2. Use the REST API call `/v1/auth/ticket` to get a TGT
3. Use the REST API call `/v1/permissions/{username}/{permission_type}` with the TGT to authenticate

Error 400 Bad Request:
`{"type":"error","message":"RequestNotValidException: ticket permission verification is not supported"}`

**Comment by nunovieira220** [comment]
Solved on f43f9793eebd216655d7f0a7a8e5a4bb653f53e3
