### ISSUE TITLE
Align i18n files (en & pt_PT)

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#806]
There are files related to i18n that are not aligned, i.e., the Portuguese version has properties missing.

./roda-ui/roda-wui/src/main/resources/config/i18n/ServerMessages.properties
./roda-ui/roda-wui/src/main/resources/config/i18n/ServerMessages_pt_PT.properties
&
./roda-ui/roda-wui/src/main/resources/config/i18n/client/ClientMessages.properties 
./roda-ui/roda-wui/src/main/resources/config/i18n/client/ClientMessages_pt_PT.properties

**Comment by nunovieira220** [comment]
Done on 476f04301cf5e89dfad4167e9e5da8a7732515ad
