### ISSUE TITLE
Move all permissions related logic from RODA-WUI to RODA-CORE

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#812]
E.g. https://github.com/keeps/roda/blob/development/roda-ui/roda-wui/src/main/java/org/roda/wui/api/controllers/BrowserHelper.java#L3370 ; https://github.com/keeps/roda/blob/development/roda-ui/roda-wui/src/main/java/org/roda/wui/api/controllers/BrowserHelper.java#L3388

**Comment by nunovieira220** [comment]
Solved on 15a98c0d6793ab71b8df87b4487be87edcd21f31
