### ISSUE TITLE
Endpoint to support embedding RODA viewers on front-end applications

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#816]
The high-level requirements are:

- Developments on the front-end application should be minimal (adding a JS should be enough)
- Access to objects is managed by the front-end applications based on the integration level 2 (unlisted records). This means that a person that has access to the AIP ID is capable of consulting it. Access to the AIP ID is managed by the front-end application
- RODA viewers should be displayed on a popup on the front-ed
- Front-ed is expected to be Web based.

Concrete actions:

1. Develop a sample/demo html page that contains a button with an AIP ID and a javascript line that opens a popup to display the RODA viewer for that AIP. 

2. RODA GUI should have no branding (special parameter should be supported by RODA). This could be done using javascript that looks at the window.location for that special parameter and then applies an additional CSS that hides unnecessary information.

3. A new endpoint on RODA should be created that using basic authentication and the parameters AIP ID and language should be able to authenticate the user on GWT and redirect it to the correct page on the GUI. Example: http://app:app_pass@roda.keep.pt/aip/11faacaf-4280-4d39-8104-94b9edb94b3a?locale=en

**Comment by nunovieira220** [comment]
Done on 5ece7bd511b0492ce48bd08614b63be0015b3bfb. Please confirm it @jmaferreira

**Comment by hsilva-keep** [comment]
The tasks associated to this issue have been done.
