### ISSUE TITLE
Plugin for the ingest workflow that creates a record on DigitArq after the ingest process

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#817]
Hélder,

Please create the skeleton for this development and then pass it on to paulo, please.

**Comment by jmaferreira** [comment]
Let's hold this task for now. Let me talk to the client first.

**Comment by hsilva-keep** [comment]
@jmaferreira what is the status of this task? To be done, stand still or be dropped?

**Comment by jmaferreira** [comment]
Stand still.

**Comment by hsilva-keep** [comment]
If no need for this occurred during one & half year, I'm closing the issue without further actions.
