### ISSUE TITLE
When showing a job with a big list of objects to act upon, an error related to Solr shows up

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#823]
WUI tries to query Solr with oneofmany filter, i.e., in a job with 5k uuids Solr client will build an URL with 5k uuids.

Possible ways to solve this:
1. When a job has a list of objects, and that list size is greater that X, simply show a message saying that the list of objects is too big to show.
2. TBA.

**Comment by nunovieira220** [comment]
A threshold property was added on roda-wui.properties to define a limit of source objects to show. Now it is showing a warning instead of the list.
