### ISSUE TITLE
Create a 'Dissemination' preservation event type

### ISSUE THREAD

**Issue by chalkos** [keeps/roda#827]
The DBVTK plugin event type is dissemination, but it does not exist in `RodaConstants.PreservationEventType`. I'm currently using `RodaConstants.PreservationEventType.MIGRATION` in the plugin.

**Comment by jmaferreira** [comment]
Ask Nuno to add it.

**Comment by nunovieira220** [comment]
I think the preservation event type enumeration is controlled so I do not think a new type should be added. @luis100 what is the best way to solve this?

**Comment by luis100** [comment]
From the [list](http://id.loc.gov/vocabulary/preservation/eventType/collection_PREMIS.html) the terms that best fit are creation and migration (which is a specific type of creation) being that the result that not change the AIP but rather creates a DIP. From the [definition](http://id.loc.gov/vocabulary/preservation/eventType/mig.html): "A transformation of an object creating a version in a more contemporary format."

It's not perfect, I would prefer to specifically define a "DIP creation" event that would mark the "creation of a version of an object in a format suitable of the contemporary designated community". But PREMIS events don't currently have such an option, we could deviate from the control vocabulary already and then try for our changes to be accepted, but ultimately the one doing this decision should be the client (i.e. repository owner/policy maker).

**Comment by luis100** [comment]
So create the constant but allow it to be overriden by (roda-core.properties) configuration.

**Comment by hsilva-keep** [comment]
Done since 20b08c52f1fb30bec1071a06a242ae3c47cdb635. 
Now it's possible to redefine preservation event type string value via roda-core.properties (with reload capabilities & put back original value by commenting out the property).

**Comment by jmaferreira** [comment]
Guys, guys... We are not following the LoC list of PREMIS events. Its to small. Instead we are using a list a proposed event types that is being voted by the community. See 

https://docs.google.com/spreadsheets/d/1Ncu0My6tf19umSClIA6iXeYlJ4_FP6MygRwFCe0EzyM/edit#gid=2002361720

In this list there is already an event for this purpose:

Event Type: **dissemination**

The process of transforming one or more archival information packages (AIP) into a dissemination information package (DIP) for use outside of the preservation repository

Take care.

**Comment by nunovieira220** [comment]
Type added on 4ae8bfced7635fb44dd268916be4e5d9095a7d93. @chalkos change it on database visualization plugin

**Comment by chalkos** [comment]
Done in https://github.com/keeps/roda-dbptk-plugin/commit/18c1cd5756a0aa8c0c1ca83bc6bcc2deced0d5ba
