### ISSUE TITLE
Dissemination panel on browse file has problems when there are too many DIPs

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda#828]

**Comment by nunovieira220** [comment]
Added scroll panel on 6eeadb71c9dfb698ea4bba7d3cd684cdea7bf8e2. @jmaferreira can you test if thats ok?

**Comment by jmaferreira** [comment]
Did I created this issue?!

**Comment by jmaferreira** [comment]
I need to sit with you and see it.

**Comment by nunovieira220** [comment]
Reviewed by @luis100
