### ISSUE TITLE
Allow to filter jobs that have failures

### ISSUE THREAD

**Issue by luis100** [keeps/roda#831]
On the job list (ingest, action, etc.) it should be possible to filter out the jobs that have failures using facets.

**Comment by nunovieira220** [comment]
@luis100 Isn't it already done using a facet for the job state?

**Comment by nunovieira220** [comment]
- [ ] Create advanced search of jobs and reports on ingest process 
- [ ] Add facets to advanced search (name, dates, pluginState, etc)
- [ ] Add multiple value list on reports to save agent with failure on ingest (to filter by facet)

**Comment by nunovieira220** [comment]
Done
