### ISSUE TITLE
Check if the file size limit is being imposed on text/SQL viewer of the default configuration of RODA

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#838]
I tried to open a large SQL file and it broke my browser. A file size limit should be activated by default that truncates the file.

I believe the default is set to 20MB.. which is way too big. Should be 1MB tops.

```
# Viewer file size limit (in bytes)
ui.viewers.text.limit = 20971520

```

**Comment by nunovieira220** [comment]
It is working and the default value was changed to 1mb.
