### ISSUE TITLE
When we select multiple categories the actions appear repeated on the list

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#839]
![screen shot 2017-03-19 at 15 08 53](https://cloud.githubusercontent.com/assets/3181302/24081989/0ba49c76-0cb6-11e7-8a50-c10b089d011f.png)

**Comment by nunovieira220** [comment]
@jmaferreira I cannot recreate this issue.

**Comment by hsilva-keep** [comment]
@nunovieira220 the way to reproduce it is:

1. Head to search, select search by file
2. Select a file
3. Hit the table actions menu
4. Select start new process
5. Select category conversion & disseminations

And you'll end up with duplicated plugin entries

**Comment by nunovieira220** [comment]
Solved on 1472ee751e1c9a68acaf80fc67225dd6599def2e
