### ISSUE TITLE
While a SIP is still being ingested, its parent node already displays information that sub AIPs exist

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#842]
Well.. sort of... 

Check this out:

![screen shot 2017-03-19 at 16 05 54](https://cloud.githubusercontent.com/assets/3181302/24082471/0f2e9e84-0cbe-11e7-9788-cb12c54014ea.png)

This happens while the SIPs are still in the ingest workflow.

**Comment by nunovieira220** [comment]
I cannot reproduce this issue. The steps I followed were:

1. Create an empty fond
2. Add a breakpoint before auto-accept executes
3. Ingest a SIP file with the created fond as parent node
4. When it stopped, the SIP file was not listed on sublevel list and, when resuming, it was.

The problem probably occured between indexing AIP and really completing the job. @jmaferreira what are the step to reproduce this issue?

**Comment by nunovieira220** [comment]
Solved on 4a3bb2af3d1a6d84a9459941ea8ddd665c8d9c8b
