### ISSUE TITLE
Add the ability to run tasks via cronjob in RODA docker container

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#845]

**Comment by hsilva-keep** [comment]
@jmaferreira I've changed the title of the issue as we should not impose what tasks are run via cronjob in RODA docker container.
In that same logic, in c2e0b5665020de22c282ddf6055a23a107e80ba8 I've added the ability to run tasks via cronjob by activating the cron service and, after that, one only needs to add the file containing the desired cronjobs (via docker copy or docker volume; how this can be done was added to README.md).
