### ISSUE TITLE
The agent version of siegfried plugin should include also the version of the PRONOM signature file

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#846]
That's important for accountability reasons. PRONOM is known to change the identified format of  a file over different versions of the signature file.

Evidences:
- http://users.ecs.soton.ac.uk/dt2/droid/
- Theres also some slides by David Tarrant that I can't seem to able to find... that shows this beautifully.

**Comment by nunovieira220** [comment]
Done on 288f8b466d0a8b8d1a3c2545b10ee8f46cf0b8c7
