### ISSUE TITLE
Improve the description of the container on GitHub

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#847]
One of the E-ARK reviewers wanted to try the RODA container and was puzzled on how to get it running. He followed the instructions on https://hub.docker.com/r/keeps/roda/ and couldn't get to run.

We should enhance the information on the container to have more info on the tool and on how to run it. Basically, copy some of the information available at https://github.com/keeps/roda/blob/master/README.md to the container description.

Here's a good example: https://hub.docker.com/_/mysql/

**Comment by hsilva-keep** [comment]
Done.
