### ISSUE TITLE
Develop CSS for being "printer friendly"

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#848]
ATM, when trying to print a page in RODA, not all the content is printed. 
This can be solved by developing CSS specific for printing.

**Comment by hsilva-keep** [comment]
Well, it turns out that this problem "only" occurs in Firefox (as in Google Chrome all the information is printed).

@nunovieira220 when you solve this issue just let me know as an internal task exists and must be closed when closing this one.

**Comment by nunovieira220** [comment]
A new stylesheet was added ( 05bbde5b28cd7d26a538efb99627cef0aced84cb ) but the problem still occurs on Firefox.

**Comment by hsilva-keep** [comment]
@nunovieira220 can you please investigate why the problem occurs in Firerox?

**Comment by luis100** [comment]
New features don't belong in beta testing. Moving to 2.1

**Comment by luis100** [comment]
This issue was fixed.
