### ISSUE TITLE
Revise Welcome page text in Portuguese

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#850]
It appears to have been automatically translated.

**Comment by hsilva-keep** [comment]
@jmaferreira are you talking about the [demo](http://demo.roda-community.org/?locale=pt_PT#welcome)? Because if you are, it is outdated (it has been changed to add the demo info/credentials & it wasn't updated after I made text review of the welcome page in RODA source code).

I'll update the demo.

**Comment by hsilva-keep** [comment]
Done updating the demo. @jmaferreira please take a look and, if it is good, please close the issue.

**Comment by jmaferreira** [comment]
Its ok.
