### ISSUE TITLE
Export CSV ignores chosen filters

### ISSUE THREAD

**Issue by luis100** [keeps/roda#862]
To reproduce, on job page:
* Ingest several SIPs, some of them corrupted
* Filter by "Reports last action"
* Export to CSV

![csv_export_ignores_filters](https://cloud.githubusercontent.com/assets/631728/25099517/83281f16-23a4-11e7-8a46-d9696a6941a7.png)

**Comment by nunovieira220** [comment]
Solved on 56df6d8509c43bad993aa88c55233144e989062f
