### ISSUE TITLE
Cannot run actions on files in assessment mode

### ISSUE THREAD

**Issue by luis100** [keeps/roda#864]
Although the buttons are there, when trying to run an action on files in assessment mode (non-active) they do not appear on the list of selected files and cannot be run on them.

![files_assessment_new_process](https://cloud.githubusercontent.com/assets/631728/25100405/e51abc1c-23a7-11e7-943b-1aeb15f952f8.png)

**Comment by nunovieira220** [comment]
Solved on 5a3d5c62f5a6af43ddb7c3b67a02a91c272d2875
