### ISSUE TITLE
Error renaming transferred resource file

### ISSUE THREAD

**Issue by luis100** [keeps/roda#865]
Had a file in transferred resources named "thesis.pdf", tried to rename it to "thesis2.pdf", got a resource not found error but also a toast message saying it was successful. Resource was **not** renamed.

<img width="1280" alt="captura de ecra 2017-04-17 as 23 47 20" src="https://cloud.githubusercontent.com/assets/631728/25107631/8104060e-23c8-11e7-9667-405d33cb8cca.png">
<img width="1280" alt="captura de ecra 2017-04-17 as 23 47 25" src="https://cloud.githubusercontent.com/assets/631728/25107636/877f14c4-23c8-11e7-9aa0-f3ad117febaf.png">

**Comment by luis100** [comment]
PS: The log does not show any errors

**Comment by nunovieira220** [comment]
Solved on 974fed513b848d7c8018828dc8b87c7cbedb4bc6
