### ISSUE TITLE
Ingest transfer allows to create folder named "a/b/c"

### ISSUE THREAD

**Issue by luis100** [keeps/roda#866]
On ingest transfer, clicking create folder, one can name the folder "a/b/c" and then the system will jump to a folder that does not exist. In fact, a folder "a" will be created with a sub-folder "b" and a sub-sub-folder "c". Only after a reindex these folders appear.

Disallow the use of "/" on the name of the folder.

**Comment by nunovieira220** [comment]
Solved on 6b43d6fdee2bcdae1819a1856f46ed271924f03b
