### ISSUE TITLE
Titles with XML entities

### ISSUE THREAD

**Issue by luis100** [keeps/roda#868]
Ingesting a file named "a&b.csv" will produce an AIP with a name "a&amp;b.csv"
![title_with_xml_ent](https://cloud.githubusercontent.com/assets/631728/25127507/fdb3fc26-242d-11e7-98bb-ec4ee8deb819.png)

**Comment by luis100** [comment]
To reproduce:
 1. Create a file named "a&b.csv"
 2. Upload it to transfer
 3. Ingest it using the SIP type "Uploaded file/folder (1.0)"

**Comment by nunovieira220** [comment]
Solved on 14ca159ea153b81731a79967d2c9e7822c673d10
