### ISSUE TITLE
Support the ability to edit static text in the admin/configuration UI or externally to the WAR file

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#87]
- Translation files 
- Core properties
- WUI properties
- Description level properties
- Descriptive metadata 
  - Validation schema
  - Index crosswalks
  - View crosswalks
  - New metadata template

-- STILL PENDING --

- Mail templates
- Report templates

**Comment by jmaferreira** [comment]
The methods that will support reading and writing of these files will be supported by @sleroux-keep

**Comment by jmaferreira** [comment]
The mail templates should be externalised and placed on the external config folder.

**Comment by nunovieira220** [comment]
The mail templates are copied to where they should be, on the _example-config/mail/templates_.

**Comment by luis100** [comment]
This is done.
