### ISSUE TITLE
Deleting a file with a "+" in the name will create a job report that cannot be accessed

### ISSUE THREAD

**Issue by luis100** [keeps/roda#870]
Steps to reproduce:
1. Create a file named "a+b.csv"
2. Ingest it using the SIP mode "Uploaded file/folder (1.0)"
3. Go to the created AIP, browse to the file, select it on the table and using ACTIONS delete it
4. Go to Administration > Internal Actions, to the delete job, and try to open the report
5. A wild NotFoundException should appear.

**Comment by luis100** [comment]
Note that #869 is related to this one and they all are probably due to a problem on URL encoding the "+" sign at [HistoryUtils.java:117](https://github.com/keeps/roda/blob/development/roda-ui/roda-wui/src/main/java/org/roda/wui/common/client/tools/HistoryUtils.java#L117)

**Comment by nunovieira220** [comment]
Solved on a5c9d206d9ef422162bd310bcc18b1be42116846
