### ISSUE TITLE
Create folder window on ingest transfer does not cope well with copy-paste

### ISSUE THREAD

**Issue by luis100** [keeps/roda#871]
Steps to reproduce:
1. Copy some text to clipboard
2. Go to Ingest > Transfer and click "New Folder"
3. Paste the text, the OK button is still disabled

The enable/disable should be tied to a onChangeEvent so at least when going out-of-focus it will enable the button. Another option is to always have the button enabled and show errors whenever the input is not valid (e.g. is empty or has illegal characters like at #866).

**Comment by nunovieira220** [comment]
Solved with the last changes to the dialog prompt
