### ISSUE TITLE
Dialogs.showPromptDialog() not setting button enable state correctly

### ISSUE THREAD

**Issue by luis100** [keeps/roda#873]
The event which is tied to the button enable state is the key press, which is evaluating against an outdated state of the inputted text. Should get the text from the event itself or choose another event where the `getText()` provides the updated text.

Steps to reproduce:
1. Go to Ingest > Transfer
2. Click "New folder"
3. Chose the input box and click the letter "a", the OK button is still disabled
4. Click "a" again, the button gets enabled, Click backspace and it is still enabled

**Comment by nunovieira220** [comment]
Solved on 6b43d6fdee2bcdae1819a1856f46ed271924f03b
