### ISSUE TITLE
Moving folder 'b' under folder 'a' opens folder 'a'

### ISSUE THREAD

**Issue by luis100** [keeps/roda#874]
Both on Ingest transfer and Browse, when moving folder 'b' under a folder 'a' it opens folder 'a' while the most natural would be to open or refresh folder 'b'.

Steps to reproduce:
1. Open Ingest transfer or Browse representation
2. Create two folders on root named 'a' and 'b'
3. Open or select folder 'b' and move it under 'a'
4. Folder 'a' is opened after move.

To note that in case a file is selected or multiple folders/files are selected for move, then the most natural would be the current behavior: to open 'a' folder.

**Comment by luis100** [comment]
Note that this has very low priority

**Comment by hsilva-keep** [comment]
In RODA version 3, actions & their repercussions seam right (using transferred resources as example):

1. In the root, if one creates folder 'a' & 'b', selecting 'b' & moving it to 'a', the user ends up in the same context, i.e. the root.
2. In the root, if one creates folder 'a' & 'b', opens 'b' & moving it to 'a', the user ends up in the 'a' folder page.
3. In the root, if one creates folder 'a', 'b' & 'c', selecting 'b' and 'c' & moving them to 'a', the user ends up in the 'a' folder page.

Its kind of subjective if behavior of number 2 is the correct, instead it could keep the user in 'b' folder page but a refresh would be required as the breadcrumb needs to be updated.

If no need for this occurred during one & half year, I'm closing the issue without further actions.
