### ISSUE TITLE
After transfer CRUD operation the lists do not show updated information

### ISSUE THREAD

**Issue by luis100** [keeps/roda#875]
It may need a forced commit on some of the methods.

Examples:
* Upload files
* Move files or folders
* Delete files or folders

**Comment by nunovieira220** [comment]
@luis100 it envolves using commits that may cause other type of issues. Should it be done?

**Comment by luis100** [comment]
Optional commit on REST method, table update on IngestTransfer resolve()

**Comment by nunovieira220** [comment]
Changed on 34234c14d2faf8ea54b42ec548e5a5452e824028. Can you review it @luis100

**Comment by luis100** [comment]
After a move information is not updated.

Steps to reproduce:
1. Create a folder 'test'
2. On the folder 'test', upload a file and create a folder 'test2'
3. Move the file to 'test2', 'test2' will be opened but will be empty, refreshing the browser shows the file.

This is probably due to a missing commit after move.

**Comment by nunovieira220** [comment]
As a first approach, a timer will be added to open the new folder's page after the plugin execution

**Comment by luis100** [comment]
Note that the Browse file move has the same problem.

**Comment by nunovieira220** [comment]
Solved on d4d66819efc91ad2e80a7cda263eccd577a25602
