### ISSUE TITLE
Review logged information

### ISSUE THREAD

**Issue by luis100** [keeps/roda#876]
Several logs have insufficient or inadequate logged information.

For example, the method createFolder logs only the parent file UUID and no information about the folder name.

**Comment by hsilva-keep** [comment]
Moreover, ATM, only login method is registering the failures. All the others, in case of exception, skip the action registration.

@luis100 @jmaferreira we should register action failures, right? I think so.

**Comment by jmaferreira** [comment]
Sure. Why not!?

**Comment by luis100** [comment]
That was changed some weeks ago by @nunovieira220, at #953

**Comment by luis100** [comment]
Note that logging every exception thrown would make the code much less readable and require many changes

**Comment by hsilva-keep** [comment]
@luis100 I never said we would log every exception. But we should register every failure, with the minimum amount of information. Basically, we will register the same amount of information but when an exception occurs instead of success state will issue an failure state.

**Comment by nunovieira220** [comment]
Solved on e485b7d16c25262dbb6fcdd594c1494aaa462358
