### ISSUE TITLE
JS injection into log entry parameters

### ISSUE THREAD

**Issue by luis100** [keeps/roda#877]
Steps to reproduce:
1. Create a file named `<a href='javascript:alert(document.cookie)'>TEST.html`
2. On any representation add the file
3. Go to Administration > Activity log and find the "Create file" log
4. There should be the link with the injected script

![js_injection](https://cloud.githubusercontent.com/assets/631728/25145223/78a41cc4-2468-11e7-9880-837838f4f3c6.png)

**Comment by luis100** [comment]
Should sanitize the parameters.

**Comment by luis100** [comment]
Note that sanitize the parameters means to use the function [SafeHtmlUtils.fromString()](http://www.gwtproject.org/javadoc/latest/com/google/gwt/safehtml/shared/SafeHtmlUtils.html#fromString-java.lang.String-) before adding the text to the GWT component.

**Comment by nunovieira220** [comment]
Solved on 51515bbe61c80b6cb0879faa2cb55653426baa12
