### ISSUE TITLE
JS injection into browse AIP by name of desc. metadata file

### ISSUE THREAD

**Issue by luis100** [keeps/roda#878]
Steps to reproduce:
1. Choose an AIP and add a new desc. metadata file
2. Choose type "Other" and name the file `<a href='javascript:alert(document.cookie)'>TEST.html`
3. Input as content `<a/>`
4. Save, should have some HTML injected into the toolbar
![browse_js_injection](https://cloud.githubusercontent.com/assets/631728/25147276/eecc5172-246e-11e7-8676-f2af3cfd8686.png)

**Comment by luis100** [comment]
Here it should be used [SafeHtmlBuilder](http://www.gwtproject.org/javadoc/latest/com/google/gwt/safehtml/shared/SafeHtmlBuilder.html) to build the toolbar HTML.

**Comment by nunovieira220** [comment]
Solved on 31f81f9c9350893664645b8ccf5333e6fc8ec801
