### ISSUE TITLE
Running VeraPDF plugin on ingest results in error

### ISSUE THREAD

**Issue by luis100** [keeps/roda#879]
When running the plugin with the appended file there is an error on the validation report:

```
/root/.roda/data/storage/aip/df75ffc1-847c-4c43-b2aa-beab51974cac/representations/0e9e9c98-bcac-498e-bc91-ff576f9c2ba7/data/thesis:test.pdfnamedescription00:00:00:056Exception: Couldn't parse stream caused by exception: Error in parsing xref stream
```

[thesis:test.pdf](https://github.com/keeps/roda/files/931126/thesis.test.pdf)

Steps to reproduce:
1. Startup RODA with the VeraPDF plugin loaded
2. Upload the above file to Ingest > Transfer
3. Ingest using SIP mode "Uploaded file/folder (1.0)" and enable "PDF/A format validation (VeraPDF)"
4. On the ingest report, follow the link to the VeraPDF report

**Comment by luis100** [comment]
Note that the same process with the same file but renamed to "thesis.pdf" results on the same error.

**Comment by nunovieira220** [comment]
@luis100 the exception is thrown by verapdf itself (it appears on the verapdf final report), not RODA.

**Comment by luis100** [comment]
Then please send this error to the VeraPDF project and close this issue.

**Comment by nunovieira220** [comment]
Created [here](https://github.com/veraPDF/veraPDF-library/issues/737)
