### ISSUE TITLE
The portuguese version of the pre-ingest page is outdated

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#880]
There are some buttons that shouldn't exist anymore. Align with the english version please.

![screen shot 2017-04-19 at 10 44 36](https://cloud.githubusercontent.com/assets/3181302/25173753/362588f8-24ed-11e7-9833-451632aa10ef.png)

**Comment by nunovieira220** [comment]
Solved on  eeef718202171df82330c80950a3a750785937d6
