### ISSUE TITLE
The 'Preservation actions' & 'Internal actions' textual description is wrong

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#881]
[Preservation actions](https://demo.roda-community.org/?locale=en#administration/process):
`The Ingest process contains services and functions to accept Submission Information Packages (SIP) from Producers, prepare Archival Information Packages (AIP) for storage, and ensure that Archival Information Packages and their supporting Descriptive Information become established within the repository. This page lists all the ingest jobs that are currently being executed, and all the jobs that have been run in the past. On the right side panel, it is possible to filter jobs based on their state, user that initiated the job, and start date. By clicking on an item from the table, it is possible to see the progress of the job as well as additional details.`

[Internal actions](https://demo.roda-community.org/?locale=en#administration/internal):
`The Ingest process contains services and functions to accept Submission Information Packages (SIP) from Producers, prepare Archival Information Packages (AIP) for storage, and ensure that Archival Information Packages and their supporting Descriptive Information become established within the repository. This page lists all the ingest jobs that are currently being executed, and all the jobs that have been run in the past. On the right side panel, it is possible to filter jobs based on their state, user that initiated the job, and start date. By clicking on an item from the table, it is possible to see the progress of the job as well as additional details.`

**Comment by jmaferreira** [comment]
Preservation actions:

[EN]
Preservation actions are tasks performed on the contents of the repository that aim to enhance the accessibility of archived files or to mitigate digital preservation risks.
Within RODA, preservation actions are handled by a job execution module. The job execution module allows the repository manager to run actions over a given set of data (AIPs, representations or files). Preservation actions include format conversions, checksum verifications, reporting (e.g. to automatically send SIP acceptance/rejection emails), virus checks, etc.

[PT]
Ações de preservação são tarefas que são aplicadas sobre os conteúdos do repositório e que visam aumentar a acessibilidade destes conteúdos ou mitigar riscos de preservação.


Internal actions:

[EN]
Internal actions are complex tasks performed by the repository as a background jobs that enhance the user experience by not blocking the user interface during long lasting operations. Examples of such operations are, moving AIPs, reindexing parts of the repository, or deleting a large number of files.


[PT]
Ações internas são tarefas complexas que são executas pelo repositório em segundo plano e que visam melhorar a experiência de utilização através do não bloqueio das interfaces sempre que se está a efetuar uma operação que poderá demorar vários segundos ou minutos. Exemplos deste tipo de operações são: mover uma AIP, reindexar partes do repositório ou eliminar um grande conjunto de ficheiros.

**Comment by nunovieira220** [comment]
Solved on 7bc062b1ba63df4a7f2b63adca577a0411eb32db
