### ISSUE TITLE
On rename file, the old file should be the value, not the placeholder

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#882]
This makes it easier to make small changes to the original name.

![screen shot 2017-04-19 at 11 14 51](https://cloud.githubusercontent.com/assets/3181302/25175116/859daee8-24f1-11e7-9c07-e1c415928816.png)

**Comment by nunovieira220** [comment]
Solved on 123f17ed0bbb9f6c4c5ba62069b9885cc18b900e
