### ISSUE TITLE
The order of the menu items could be improved

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#883]
The order should be:

Atualizar
Nova Pasta
Renomear
Mover
Eliminar
Carregar

![screen shot 2017-04-19 at 11 16 13](https://cloud.githubusercontent.com/assets/3181302/25175167/b2dacc1a-24f1-11e7-9632-e4d77246165d.png)

**Comment by hsilva-keep** [comment]
This no longer applies since RODA version 3 new UI/changes.
