### ISSUE TITLE
There are problems when we try to ingest a hierarchy of itens beneath a newly created AIP

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#884]
How to reproduce:

1. Create a hierarchy on RODA
2. Export hierarchy and load on RODA-in
3. Add a few items
4. Export all itens
5. Ingest on RODA setting the parent node (don't force)
6. See the result

**Comment by hsilva-keep** [comment]
Done since a0b93a1ba5712f0ede47afe0219ecba77e474901
