### ISSUE TITLE
Re-implement actions in all entities using the Actionable interface

### ISSUE THREAD

**Issue by luis100** [keeps/roda#885]
A new centralized model for actions upon entities was created following the interface `org.roda.wui.client.common.actions.Actionable` and implemented for the entities: AIP, Representation, File, Dissemination and DisseminationFile.

The same model should be implemented for the remaining entities, specifically:
- [x] TransferResources
- [x] Job and JobReport
- [x] Risk and RiskIncidence
- [x] Format/Representation Information
- [x] PreservationEvent and PreservationAgent
- [x] LogEntry and Notification
- [x] RODAMember (User and Group)

**Comment by chalkos** [comment]
LogEntry and Notifications do not have actions.

**Comment by chalkos** [comment]
Still missing actionable job and job report

**Comment by chalkos** [comment]
Done.
