### ISSUE TITLE
AIPCorruptionRiskAssessmentPlugin should detect missing files

### ISSUE THREAD

**Issue by luis100** [keeps/roda#891]
If there is a PREMIS file for a file that is not found an incidence should be created and it should be added in the report.

The idea is to iterate over the PREMIS files and when the respective file is not found, then the plugin should create a new incidence. It is necessary to remove PREMIS files when deleting files or representations (it is not being done yet)

**Comment by jmaferreira** [comment]
Also review the plugin description to state the new functionality.

**Comment by nunovieira220** [comment]
Solved on bd445150319cd13ff56e3d2abf1e2476f38746d5. can you review it @luis100 ?

**Comment by luis100** [comment]
Tried it and it didn't work, in fact it worked worst than before.

1. Ingested 2 files
2. Added a file (so PREMIS isn't created)
3. Removed one of the files firstly ingested
4. Using [bless](http://home.gna.org/bless/) edited the other file firstly ingested
5. Executed the plugin on all AIPs

The task ran without detecting any of the failures, the removed file or the corrupted file.

**Comment by luis100** [comment]
Note that test was run in a docker made from commmit bd445150319cd13ff56e3d2abf1e2476f38746d5

**Comment by nunovieira220** [comment]
There were no changes on the checksum comparison part and I cannot reproduce the problem. Did you use docker before too? @luis100

**Comment by nunovieira220** [comment]
Improvements were made on dec2443a55e36dbfe9c33f2f0d09205fae18c632. Can you test it again @luis100 ?

**Comment by luis100** [comment]
Now it worked. To note that it also complained about a file that didn't had PREMIS, which was expected because it was uploaded afterwards, not sure if this should be a failure, but ok...

![roda - 1da907e9-f62f-4031-8789-fa86e42bbad0-2542f405-5bdd-4bc2-a1eb-146146c80a77](https://cloud.githubusercontent.com/assets/631728/25825942/d18c96fc-343c-11e7-9a7f-8302b37c77da.jpg)
