### ISSUE TITLE
AIPCorruptionRiskAssessmentPlugin should not duplicate incidences

### ISSUE THREAD

**Issue by luis100** [keeps/roda#893]
When running several times AIPCorruptionRiskAssessmentPlugin on a corpora with the same incidences, it will duplicate the incidences. 

- [x] If a file is detected to be corrupted or missing, and an incidence related to this already exists, it should not be duplicated
- [x] If there is an incidence related to a file that is now fixed, then the incidence should be updated to be mitigated

Note that the same logic was already implemented in the plugins File not characterized risk assessment (1.0) and Format missing representation information risk assessment (1.1.1).

**Comment by nunovieira220** [comment]
Solved on 7884ac8482689cfc1c782cfa096997a7e5843121
