### ISSUE TITLE
AIP metadata editor is broken

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#895]
To reproduce:

1. Create a new AIP (look at the order of the fields)
2. Edit the created AIP  (look at the order of the fields)

Both should display the same order (order no 1).

PS: This bug was recently introduced. Previous version did not have it.

**Comment by hsilva-keep** [comment]
I've tested out this in docker images available & I've tracked down the last image that doesn't show this behaviour. It is beta3 produced from commit 205651c62931abbf3e5d7387084abbe8734a9de6.

**Comment by nunovieira220** [comment]
Solved on dd2098ad747d99b21267c4a2e3fa6023f2c722cf
