### ISSUE TITLE
Update translation "Negligível" > "Negligenciável"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#897]
Negligível está registado em dicionários brasileiros — cf. iDicionário Aulete e Dicionário Unesp do Português Contemporâneo —, que também acolhem negligenciável. O iDicionário Aulete descreve negligível como empréstimo do inglês e define-o como termo especializado da Física e Matemática («diz-se daquilo que pode ser desconsiderado (refere-se esp. a valores ou quantidades tão ínfimos que podem ser desprezados»), que por extensão semântica significa também «insignificante, desprezível».

Refira-se que negligível parece ter pouco uso, quer no português do Brasil quer no português europeu, a avaliar pelas raríssimas vezes em que aparece em corpora textuais: na Linguateca, apenas se registam duas ocorrências, uma num jornal brasileiro (Folha de São Paulo) e outra num jornal português (no Público); no Corpus do Português,  de Mark Davies e Michael Ferreira, apenas figura uma vez, num texto de origem brasileira. Em Portugal, os dicionários feitos em Portugal, mesmos os mais recentes ou atualizados (cf. versões em linha do Dicionário da Língua Portuguesa da Porto Editora e Dicionário Priberam da Língua Portuguesa) só incluem negligenciável. Pelo menos, em registos não especializados, não se vê necessidade na substituição de negligenciável por negligível, uma vez que este não traz qualquer matiz semântico relevante ou inovador e não tem tradição na língua portuguesa (ainda que, em última análise, este anglicismo tenha origem latina).

https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/negligivel/31943

**Comment by nunovieira220** [comment]
Solved on d4d66819efc91ad2e80a7cda263eccd577a25602
