### ISSUE TITLE
Background tasks and usability

### ISSUE THREAD

**Issue by luis100** [keeps/roda#900]
Some tasks, however simple, can take a lot of time to execute when the target objects are too many or too big. For example, moving (transferred resource files, AIPs, files) can be very fast when executed against a single file, but take a lot of time when executed against millions of files or a very big file moving between different storage systems.

To cope with tasks that take a lot of time we have **internal actions** and some tasks have already been implemented using internal actions, like e.g. the move of transferred resources. But, this internal tasks are asynchronous, the user requests the move and the function returns immediately before the result has been accomplished. This is all good for tasks that really take a lot of time, but **not for moving a small file between two folders on the same storage** (see #875).

One possible solution would be to only use **internal actions** when the move will take a lot of time but calling the method directly when the move will be fast. But it can be infeasible to know when an action will take a lot of time, so this approach is not adequate.

Another solution, and the one proposed by this issue, is to always use internal actions, but **wait a predefined amount of time before returning to the user**, giving a chance for the action to end. If the action **ends before the timeout it should return immediately** (so we need to be warned by the system that the task has already ended). When returning to the user it should be **stated if the action has already ended of if it is still running as a background task**, providing him with a **link to the internal action status page** if it is still running.

**Comment by luis100** [comment]
To note that this solution can be generic to any background task / internal action.

**Comment by hsilva-keep** [comment]
Since RODA version 3 almost all actions are done asynchronously via jobs. If any of the remaining actions, that are done synchronously, need to be done other way, new issue must be created.
