### ISSUE TITLE
Upload file to representation root problem

### ISSUE THREAD

**Issue by luis100** [keeps/roda#902]
Using the following steps a file will be uploaded to the wrong place.

Steps to reproduce:
1. Create a new AIP and add a new representation to it.
2. Create a folder named "test"
3. In the folder "test" upload a new file
4. Go back to the representation and upload another file here
5. The second uploaded file will be added to the folder "test" instead of being on the root of the representation.

**Comment by nunovieira220** [comment]
Solved on 123f17ed0bbb9f6c4c5ba62069b9885cc18b900e
