### ISSUE TITLE
PDF to PDF/A conversion (ghostscript) plugin problems

### ISSUE THREAD

**Issue by luis100** [keeps/roda#903]
Using as corpora my [thesis.pdf](https://github.com/keeps/roda/files/945111/thesis.pdf)

- [ ] Using the option "Apply veraPDF metadata fixer" makes the task fail without giving a concrete reason on the report. Also, it defines as a "partial success" when the action itself, which was to create a DIP, was not accomplished.
![job](https://cloud.githubusercontent.com/assets/631728/25246560/f620f6a2-25ff-11e7-9758-4f2b08572edf.png)
![job_report](https://cloud.githubusercontent.com/assets/631728/25246565/f8d18088-25ff-11e7-9752-e9411504c132.png)
- [ ] Not using the option "Apply veraPDF metadata fixer" creates a PDF file that is much bigger (a 4MB PDF became a 30MB PDF), and that does not pass the VeraPDF validator anyway.
![verapdf_report](https://cloud.githubusercontent.com/assets/631728/25246646/36d20222-2600-11e7-8667-09744e29c34e.png)

So I wonder what is the usefulness of having this plugin at all and if it shouldn't just be removed (unless the VeraPDF metadata fixing can be made functional and make the resulting PDF valid).

**Comment by jmaferreira** [comment]
Classify it as experimental.
Actually that is something we should do for all the plug-ins that haven’t been tested properly.

**Comment by luis100** [comment]
@hsilva-keep can you create another issue to classify this plugin as experimental and add it to the current spring and move this issue to the unplanned milestone?

**Comment by hsilva-keep** [comment]
No longer applies as experimental plugins have been removed.
