### ISSUE TITLE
Support autoprofile in VeraPDF plugin

### ISSUE THREAD

**Issue by luis100** [keeps/roda#905]
Right now the plugin makes it mandatory to choose a profile, or at least does not document the automatic profile selection on the plugin parameters.

This automatic profile selection should be the default for this plugin.

Check the [documentation about autoprofile](http://docs.verapdf.org/cli/validation/#auto-profile) for details.

**Comment by luis100** [comment]
Carl Wilson indicated that, to use the autoprofile:

> pass the NO_FLAVOUR enum rather than any flavour, the parser will then use the flag in the PDF's metadata

**Comment by hsilva-keep** [comment]
No longer applies as experimental plugins have been removed.
