### ISSUE TITLE
Review plugin categories

### ISSUE THREAD

**Issue by luis100** [keeps/roda#906]
Create new category validation and add the following plugins to it:
* Virus check
* Digital signature validation
* AIP metadata validation
* PDF/A validation (VeraPDF)
* Jpylyzer

Create new category "file format identification" and add:
* Siegfried
* Droid

Create new category "feature extraction" and add:
* ExifTool
* FITS
* JHove
* MediaInfo
* avprobe
* Apache Tika
* Jpylyzer

All validation, file format identification and feature extraction plugins should also be of category characterization.

**Comment by nunovieira220** [comment]
Solved on 94bf1a31b71d4f09686c71ecfc2c6bfa1bfba3c2
