### ISSUE TITLE
Dialogs.prompt() lack of feedback when input is invalid

### ISSUE THREAD

**Issue by luis100** [keeps/roda#908]
When the input is invalid the confirm button becomes disable but there is no feedback to the user of how to make the input valid.

This might require more changes that just outputting to the user that the input is invalid, as this still gives no clues of how to make it valid, and outputting a message like "Your input is invalid, please make sure you follow the regex pattern ^[^/]*$" is also very unusable for most users.

I suggest adding other ways to define the validity that would help giving proper user feedback messages:
* Number of minimum amount of characters
* Number of maximum amount of characters
* List of illegal characters (blacklist)
* List of permitted characters (whitelist)
* Regular expression (only to be used as last resort)

Each of the above would be a validation rule and the prompt dialog could receive a list of them.

**Comment by hmiguim** [comment]
Release in [tag 4.5.0](https://github.com/keeps/roda/releases/tag/v4.5.0).
