### ISSUE TITLE
Digital signature validator problems

### ISSUE THREAD

**Issue by luis100** [keeps/roda#911]
- [x] The plugin reports signature valid when it is **NOT** valid

[doc_situcaocontributiva_12026372822.pdf](https://github.com/keeps/roda/files/947894/doc_situcaocontributiva_12026372822.pdf)
Reports valid but the certificate is NOT valid

![invalid_signature](https://cloud.githubusercontent.com/assets/631728/25290144/880dcc1a-26c4-11e7-99fe-18de96a44d72.png)

- [x] [SampleSignedPDFDocument.pdf](https://github.com/keeps/roda/files/947895/SampleSignedPDFDocument.pdf)
Reports invalid  `Signature validation failed on aip/c91d2b4f-7f28-4fc1-93fe-f5ee8fa67101/representations/be615e8b-e43f-4143-9183-7e240d82cb30/data/SampleSignedPDFDocument.pdf.`
But only the timestamp has expired which, on the opinion of the Adobe Acrobat Reader constitutes a valid signature. Although we might not be of the same opinion, it would be very worthwhile describing on the report that the certificate is valid but the signature timestamp has expired.

![signature_kind_of_valid](https://cloud.githubusercontent.com/assets/631728/25290185/aff2be0c-26c4-11e7-8cc9-214522559f0e.png)

- [x] Digital signature report should have the same output as in the preservation event

Job report outcome details: none

Preservation event outcome detail:
```
Digital signatures were valid and/or they were stripped with success.
The DS verification ran on: decl.pdf (Passed). The following files DS information were extracted: decl.pdf. The digital signature (DS) operation stripped some files.
```

**Comment by nunovieira220** [comment]
Solved on 21906e6f0dab0fb8507f968e4cc3ed3644eee864
