### ISSUE TITLE
Internal actions facet Job types is superfluous

### ISSUE THREAD

**Issue by luis100** [keeps/roda#912]
On internal action all jobs are of type INTERNAL. Besides, the facet for this enumeration is not internationalized.

**Comment by luis100** [comment]
![roda - administration](https://cloud.githubusercontent.com/assets/631728/25344367/cdefa3b0-2909-11e7-921f-d2ded1d193f9.jpg)

**Comment by nunovieira220** [comment]
Solved on c4c6c30a369dff25aea798fd42053e1ca9cd5362
