### ISSUE TITLE
When (image) format conversion ignores/fails files resulting representation has missing files

### ISSUE THREAD

**Issue by luis100** [keeps/roda#918]
Converted an AIP with a representation with several images, some of them not supported by the imagemagick converter, but the resulting representation does not contain all the files. It should have copied the files it hasn't converted.

![roda - c3ef6d85-8cf2-4949-8cb0-5d699bccf7b5](https://cloud.githubusercontent.com/assets/631728/25358086/1f54d22e-2938-11e7-81ec-55ca71a70977.jpg)

![roda - c3ef6d85-8cf2-4949-8cb0-5d699bccf7b5-c1e4155e-c2b8-323d-8b60-ee72f94eab5f](https://cloud.githubusercontent.com/assets/631728/25358084/1d24cebe-2938-11e7-9824-d06ea96be398.jpg)

![roda - catalogue](https://cloud.githubusercontent.com/assets/631728/25358088/20ec64d0-2938-11e7-99b6-4b7a3d1a2ca8.jpg)

![roda - catalogue 1](https://cloud.githubusercontent.com/assets/631728/25358134/4fdbb174-2938-11e7-9655-af553597d8e7.jpg)

**Comment by luis100** [comment]
Corpora: [images.zip](https://github.com/keeps/roda/files/953137/images.zip)

**Comment by nunovieira220** [comment]
@luis100 I can not reproduce this issue, can you test it again?

**Comment by luis100** [comment]
Yes, wrong step two. Select the **AIP** and execute the image converter with the default options but deselecting the "create dissemination" option.

**Comment by luis100** [comment]
Note that executing the representation works well, but not executing the AIP, which should have the same logic.

The initial instruction, selecting all files, will create a different representation for each of the files which format the plugin supports, which is not optimal but understandable why it does it this way.

**Comment by nunovieira220** [comment]
@luis100 I can not reproduce with any of the input object types.

**Comment by luis100** [comment]
The problem continues. Select the AIP and run the plugin, it will only show two files on the resulting representation.

**Comment by nunovieira220** [comment]
Solved on 194c24627ae7f8a58d516c450a92366dfcbaa759
