### ISSUE TITLE
avconv missing error details

### ISSUE THREAD

**Issue by luis100** [keeps/roda#920]
Converting the file 
[jpeg2000.mov.zip](https://github.com/keeps/roda/files/953214/jpeg2000.mov.zip) (unzip first)

To the dissemination with all default options there is an error when using the avconv installed by default on the docker image.

![roda - 641c2d61-9865-4bd3-b9cf-9cbe9cfaa2c5-d42b7ebc-5d12-3f25-bafa-5adc7c1c1a44](https://cloud.githubusercontent.com/assets/631728/25359344/bd021d02-293c-11e7-83da-562be5bd0f11.jpg)

But it is missing the error details. Part of the problem are the program arguments used:

```
$ /usr/bin/avconv -t 20 -v quiet -y -i /root/.roda/data/storage/aip/098891ac-9183-4671-9209-b9f0758cfa37/representations/29f9cc5b-1c20-4f65-ab6c-db9584adaa25/data/jpeg2000.mov -c:v libx264 -crf 28 -c:a aac -b:a 128k -strict experimental /usr/local/tomcat/temp/converted6979216205472758360.mp4
```
The `-v quiet` silences all output, it should be changed to `-v warning` to: "Show all warnings and errors. Any message related to possibly incorrect or unexpected events will be shown."

```
# /usr/bin/avconv -t 20 -v warning -y -i /root/.roda/data/storage/aip/098891ac-9183-4671-9209-b9f0758cfa37/representations/29f9cc5b-1c20-4f65-ab6c-db9584adaa25/data/jpeg2000.mov -c:v libx264 -crf 28 -c:a aac -b:a 128k -strict experimental /usr/local/tomcat/temp/converted6979216205472758360.mp4
[jpeg2000 @ 0xc1a8a0] SOC marker not present
    Last message repeated 24 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xc095e0] Could not find codec parameters (Video: jpeg2000, 320x240, 3063 kb/s)
/root/.roda/data/storage/aip/098891ac-9183-4671-9209-b9f0758cfa37/representations/29f9cc5b-1c20-4f65-ab6c-db9584adaa25/data/jpeg2000.mov: could not find codec parameters
```

**Comment by nunovieira220** [comment]
Solved on a6770a5f80e1a528e837d6e43f63605adce89e53
