### ISSUE TITLE
Download a single preservation event/agent metadata

### ISSUE THREAD

**Issue by luis100** [keeps/roda#923]
Download the PREMIS file related to a single preservation event or agent. This is specially useful on repository level events, which can be many and we are only interested in one.
![roda - catalogue 3](https://cloud.githubusercontent.com/assets/631728/25410391/6d082b84-2a0e-11e7-8295-684d7892a4d1.jpg)

**Comment by nunovieira220** [comment]
Solved on e04f1e00bd26fb1df7c62ef3177a22ea060ec136
