### ISSUE TITLE
Advanced search field of controlled type should have a "None selected" option

### ISSUE THREAD

**Issue by luis100** [keeps/roda#925]
When adding an advanced search field of type controlled, the added widget does not provide with a "None selected" option, which enforces the restriction of that field to a value whenever it is visible. This is specially annoying when this is a fixed field.

Add a "None selected" option to the widget which should be selected by default.
![roda - search](https://cloud.githubusercontent.com/assets/631728/25441043/0f630d9c-2a99-11e7-8ea7-5b3471fd80d2.jpg)

**Comment by nunovieira220** [comment]
Solved on 3187b2fda4457844502d1cd2d87eaed558a5dc20
