### ISSUE TITLE
@title on the search comboboxes (hover with mouse) needs translation. Its locked on english.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#934]
![screen shot 2017-04-27 at 10 25 06](https://cloud.githubusercontent.com/assets/3181302/25476979/dbc6165a-2b33-11e7-939c-0216b0f4f5dd.png)

**Comment by hsilva-keep** [comment]
@jmaferreira we need more information about the problem & the possible solution.

**Comment by jmaferreira** [comment]
You're right. Sorry. Just changed the title of the issue to make it clear.

**Comment by jmaferreira** [comment]
Example:

![screen shot 2017-05-03 at 12 52 08](https://cloud.githubusercontent.com/assets/3181302/25659364/5b0e1ac8-2fff-11e7-807a-2482cd1085eb.png)

**Comment by nunovieira220** [comment]
Solved on 27b4aa18e18484600ba9716c2334894a002b88ce
