### ISSUE TITLE
METS generation problems

### ISSUE THREAD

**Issue by luis100** [keeps/roda#943]
Generated METS for the AIP: [digitally signed text .zip](https://github.com/keeps/roda/files/961291/digitally.signed.text.zip)

The mets file, which is included in the ZIP file above, escapes the slashes on the xlink:hrefs

```xml
<mdRef ID="metadata.xml" LOCTYPE="URL" MDTYPE="OTHER" OTHERMDTYPE="key-value" xlink:type="simple" xlink:href="metadata%2Fdescriptive%2Fmetadata.xml" MIMETYPE="application/xml" SIZE="115" CREATED="2017-04-27T10:35:22.580Z" CHECKSUM="640179558A7A4875957384D380D4CE2B72B8346F1D97228710A04FB1CDFFEDC9" CHECKSUMTYPE="SHA-256"/>
...
<mdRef ID="urn:roda:premis:event:552c0d44-1b33-4fb9-b9d1-90654ce53bc9" LOCTYPE="URL" MDTYPE="OTHER" xlink:type="simple" xlink:href="metadata%2Fpreservation%2Furn%3Aroda%3Apremis%3Aevent%3A552c0d44-1b33-4fb9-b9d1-90654ce53bc9.xml" MIMETYPE="application/xml" SIZE="1645" CREATED="2017-04-27T10:35:22.585Z" CHECKSUM="3AC11359D7A5A99CB746F71A50B8DA92FF6F12F8C62DE013B2E5148C81201D4C" CHECKSUMTYPE="SHA-256"/>
...
<file ID="uuid-2FF18C6E-4BB4-4215-9DB4-475C364D3D1C" MIMETYPE="application/xml" SIZE="3180" CREATED="2017-04-27T10:35:22.603Z" CHECKSUM="F1F5BB6003165CDD8F6C1FCC32F8FD1F965E1681010F3B9806D9460BCFFA8A3C" CHECKSUMTYPE="SHA-256"><FLocat LOCTYPE="URL" xlink:type="simple" xlink:href="schemas%2Fxlink.xsd"/>
```
Could not test it on eark web due to https://github.com/eark-project/earkweb/issues/48

**Comment by luis100** [comment]
This issue might be related to https://github.com/keeps/roda-in/issues/277

**Comment by rui-castro** [comment]
@luis100 I will look at this issue this week.

**Comment by luis100** [comment]
You should ask @sleroux-keep why, but my guess is that some characters actually need to be escaped, as XML special chars like `"'<>&`, but not all, like for example the slash. The encoding needs to be improved to only focus on the path partials and not the path as a whole.

**Comment by rui-castro** [comment]
@luis100 `mvn clean package` on master branch is failling with error `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project roda-plugin-conversion-pdftopdfa: There are test failures.`

I saw the commit (https://github.com/keeps/commons-ip/commit/fdeacc1fc1ae238af95cdb9ca2c28ba3ea5228a7) that @hsilva-keep mentioned and I was wondering if it makes sense to do URL encode on XML values. If we remove the URL encode everything would be ok, no?

**Comment by luis100** [comment]
@rui-castro are you compiling roda? if you are testing please use development branch, if there are errors please report as a different issue.

@rui-castro also if this issue is due to another issue on the underlying commons-ip library please report it. The generated METS should be valid and sound, having URL-encoded paths to files doesn't sound very good to me. It is, nevertheless, hard to assess the validity and soundness of the produced METS file without having a third party application to assess it independently, but as the eark-web issue reported above is not yet fixed, we have no other option but to assess it manually.

**Comment by luis100** [comment]
@rui-castro ping

**Comment by rui-castro** [comment]
@luis100 I'll check it later today.

**Comment by rui-castro** [comment]
@luis100 PR keeps/commons-ip/pull/26 fixes the issue

**Comment by luis100** [comment]
@hsilva-keep please check the PR

**Comment by luis100** [comment]
@hsilva-keep what is the status of this?

**Comment by jmaferreira** [comment]
We need a decision on this issue.

**Comment by hsilva-keep** [comment]
Well...The thing is...Besides having this one year old issue open, no other issues exists related to METS (and METS encoding). With this I'm saying that for the moment this is not an issue & therefore I'll close this issue until further evidences that the issue still exists (if that happens, we should open this one or create new one referencing this issue).
