### ISSUE TITLE
Add page of instructions about the integration between digitarq and RODA

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#945]
if specific add it only to DGLAB instance. If generic, put in base (PT only at this time).

- Foi disponibilizada uma nova versão do DigitArq no servidor de testes do DigitArq que possui um novo campo chamado "RODA AIP ID” na zona de Materiais relacionados. Neste campo poderão colocar o ID de um AIP do RODA que esteja partilhado para leitura com o grupo “FrontendApps”. Uma vez colocado lá um ID, se o registo for publicado, no FrontOffice do DigitArq poderão ver a integração com o RODA a funcionar. A integração não implicou alterações ao código do DigitArq, apenas a execução de um javascript, o que significa que em teoria será possível integrar o RODA com qualquer sistema Web que permita colocar num campo qualquer o AIP ID do RODA. O Javascript trata de tudo o resto.

**Comment by nunovieira220** [comment]
Solved adding on DGLAB instance.
