### ISSUE TITLE
Email link to acknowledge notification points to REST API

### ISSUE THREAD

**Issue by luis100** [keeps/roda#946]
The email link to acknowledge the notification points to the REST API, which responds like below.
This is ugly for the end user. Implement a new WUI servlet to acknowledge the notification and that will redirect to a page on RODA normal site describing to the user that the notification was successfully acknowledged (or show error message), and allow it to further use RODA WUI.

![localhost-8080-api-v1-notifications-7b7d1f66-ef5e-44eb-bfe2-d4571b916d6f-acknowledge-token c586e571-b842-4967-848f-603c8b71a81947686959-8e74-3d95-8e81-9c180af31982](https://cloud.githubusercontent.com/assets/631728/25487969/aa225ddc-2b5d-11e7-9a17-eabc1094715c.jpg)

**Comment by nunovieira220** [comment]
Solved on abb67fc33e7b423293142afab1ccfe0c5be046ed
