### ISSUE TITLE
Email notification design could be improved

### ISSUE THREAD

**Issue by luis100** [keeps/roda#947]
- [x] Subject needs a space between the hyphen and the SUCCESS/FAILURE state.
- [x] There could be more information about failures
- [x] Review design (fonts, colors, spaces).

![mailcatcher 3](https://cloud.githubusercontent.com/assets/631728/25488241/74bdb280-2b5e-11e7-8110-d838bd7291ce.jpg)

**Comment by jmaferreira** [comment]
Check if it is a configurable template. If so, we can change it on the implementation process.

**Comment by nunovieira220** [comment]
Solved on 6304a8283f6ab1f17ca32b6ebfdd2e6950849b9f
