### ISSUE TITLE
Label mismatch between recover password email and web form

### ISSUE THREAD

**Issue by luis100** [keeps/roda#948]
On the email it says "Pasword for verification" but on the web form it says "Password Recovery". 

![mailcatcher 5](https://cloud.githubusercontent.com/assets/631728/25489093/bf4ce724-2b60-11e7-80ff-0a675eb5b0d6.jpg)
![roda - change password](https://cloud.githubusercontent.com/assets/631728/25489099/c25f1ba8-2b60-11e7-9442-dc3ce0267aaf.jpg)

**Comment by nunovieira220** [comment]
Solved on 48cc5b579f4e4a791e9422c00e8c6d8d748e0ae6
