### ISSUE TITLE
Report lacks information when user is not authorized to ingest below an AIP

### ISSUE THREAD

**Issue by luis100** [keeps/roda#952]
It should state which user (name) and which AIP (id).

![roda - d1d2ca96-6f49-4094-8ff5-fd5846fcfd90-79f5ee66-1d72-488c-9a6b-b8773a233f97](https://cloud.githubusercontent.com/assets/631728/25495810/856f6dd6-2b76-11e7-9577-798046bfa707.jpg)

**Comment by nunovieira220** [comment]
Solved on c2226620c805666d45a331a26010ef4c4852cc4d
