### ISSUE TITLE
Risk incidence multiple edit form: mitigated on field date picker

### ISSUE THREAD

**Issue by luis100** [keeps/roda#955]
The "mitigated on" field is expecting a date, so the editor could be a date picker

![roda - planning 1](https://cloud.githubusercontent.com/assets/631728/25533868/00886aa0-2c2a-11e7-9f61-789507fa6c00.jpg)

**Comment by nunovieira220** [comment]
Solved on 4d2c9264e6414bfcb04daf05e91eadfbbab4a173
