### ISSUE TITLE
Delete single incidence toast message

### ISSUE THREAD

**Issue by luis100** [keeps/roda#956]
When selecting a single incidence from the list and clicking remove the message "Successfully removed **all** the items" appears. It should be "Successfully removed **selected"** the items"

![roda - planning 2](https://cloud.githubusercontent.com/assets/631728/25534053/98ef0114-2c2a-11e7-82e3-b253b28b3742.jpg)

**Comment by nunovieira220** [comment]
Solved on 27e2bc31d390280d371975f046766b3e3e4057d4
