### ISSUE TITLE
Format list: filtering by date without it being visible on the list is odd

### ISSUE THREAD

**Issue by luis100** [keeps/roda#957]
Or the date is important enough to be shown on the list and have a facet filter always visible, or it's not and the filter should be removed.

![roda - planning 3](https://cloud.githubusercontent.com/assets/631728/25534275/2e3ab790-2c2b-11e7-8de8-e011b86e5029.jpg)

**Comment by jmaferreira** [comment]
Remove date facet.

**Comment by nunovieira220** [comment]
Solved on 21eec33ab4d744fe788e5e45dfab69d3d0f9598e
