### ISSUE TITLE
Planning > Preservation events facets and filters

### ISSUE THREAD

**Issue by luis100** [keeps/roda#959]
Add preservation event 

- [ ] type facet, 
- [ ] outcome facet, and 
- [ ] date filter 

to the sidebar.

![roda - planning 4](https://cloud.githubusercontent.com/assets/631728/25535162/08aebb54-2c2e-11e7-9232-b248f7e05068.jpg)

**Comment by nunovieira220** [comment]
Solved on f0c008a8b1abc186f616c60f61acb046c32753a5
