### ISSUE TITLE
Add a parameter to the Default Ingest Plugin to specify the ParentID

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#96]
Two options:

1. Replace all the ParentIds in the SIPs of the batch
2. Fallback (if the SIPs do not include a ParentID)

**Comment by hsilva-keep** [comment]
Done since 3c5963a6716bbb1622f69bbe9e734e9061fb7bb2. 
It was implemented using a text field to set a parent id (which will be used in the SIPs that does not have one) and a checkbox to force the usage of the previously defined parent id in all SIPs (even if the SIPs have one defined)
