### ISSUE TITLE
NPE when sorting preservation events by detail

### ISSUE THREAD

**Issue by luis100** [keeps/roda#960]
![pres_event_npe](https://cloud.githubusercontent.com/assets/631728/25535329/8ef89946-2c2e-11e7-9322-46354ac4a4a6.png)

**Comment by hsilva-keep** [comment]
We've made several changes related with preservation events & plugins that produce preservations events, and failed to reproduce this issue. 
I'll close it for now & if latter on we can provide the steps to reproduce this issue, will open a new one.
