### ISSUE TITLE
Improve create user invalid password message(s)

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#962]
While creating a new user, several things might happen to the password introduced but the message is always the same, things like:
- The minimum length is not being meet
- The passwords (first & confirmation) do not match
- Etc.

Besides that, in PT_PT, the message is wrong. Where we have "Senha não é válido" we should have "Senha não é válida".

**Comment by nunovieira220** [comment]
Solved on 036940a1781b081772a388efbde38334efd55323
