### ISSUE TITLE
The preservation event created while deleting an AIP could have more information

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#966]
ATM, only the UUID is stored in the preservation event. Having things like the title, level or others could be useful to know more about the AIP deleted.

**Comment by nunovieira220** [comment]
I added the title information on a7e1eb66aa80a536a9ef2a8e7dbaa142954396ea, is it enough?

**Comment by jmaferreira** [comment]
Title, dates, level
All the stuff that appears on the lists

**Comment by nunovieira220** [comment]
Solved on 3ce2603206d98dec6eaede70440a2d4df3a68116
