### ISSUE TITLE
Calling API naked endpoint gives NPE

### ISSUE THREAD

**Issue by luis100** [keeps/roda#970]
http://localhost:8080/api

It should give some basic information.

![apache tomcat-8 0 33 - error report](https://cloud.githubusercontent.com/assets/631728/25635404/e841f25a-2f75-11e7-8d34-219bb449dd4a.jpg)

**Comment by hsilva-keep** [comment]
Perhaps we should redirect to swagger API...

**Comment by nunovieira220** [comment]
Solved on e1abe3fac5703502362c556e370db5ffa27b9266
