### ISSUE TITLE
RODA's main menu is not responsive

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#976]
It should switch to vertical menu on a small screen or else transform it self into an hamburger.

See if its an easy fix. If not, put in Unplanned.

**Comment by luis100** [comment]
It isn't an easy fix, currently the GWT Menu is used and it doesn't support being responsive. The mobile 'hamburger' version would need to be developed from scratch or a new library would need to be used to support responsive menus

**Comment by jmaferreira** [comment]
Ok… but a simple CSS fix can be done to make it more presentable right?!

**Comment by luis100** [comment]
It is an HTML table, code generated by gwt, not really easy to fix via CSS

**Comment by jmaferreira** [comment]
Ok. Move it to Unplanned.

**Comment by hsilva-keep** [comment]
If no need for this occurred during (almost) 2 years, I'm closing the issue without further actions.
