### ISSUE TITLE
Update CAS documentation

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#977]
- Filters configuration is outdated (now there'is an enable switch for internal & cas filter).
- Put any needed information to allow integration with another CAS enabled services.

**Comment by hsilva-keep** [comment]
Well, done.

**Comment by chalkos** [comment]
@hsilva-keep 
I just recalled that the docs are a bit incomplete.

I forgot to add that cross site scripting must be allowed, otherwise the connection from the **https** gwt page to the **http** gwt code server will be denied.

This is just development info, but I think it is important nonetheless.
