### ISSUE TITLE
Add a new section to the AIP UI

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#981]
The new section will be called "Representations" and it would have one button at the moment "New".

Representations
- New

![screen shot 2017-05-11 at 10 31 49](https://cloud.githubusercontent.com/assets/3181302/25942589/2e0db092-3635-11e7-8514-8c4f9bc74f96.png)

**Comment by nunovieira220** [comment]
Solved on 6304a8283f6ab1f17ca32b6ebfdd2e6950849b9f
