### ISSUE TITLE
When in CAS mode and "talking" with another CAS enabled service, RODA fails to do it properly 

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#982]
When RODA is in CAS mode and talks with a CAS enabled service (e.g. Database Visualization Toolkit), it fails to do it properly.
This happens because RODA should obtain, while doing authentication with CAS, the Proxy Granting Ticket, which would allow Database Visualization Toolkit to use authenticated services in the name of the authenticated user in RODA.

Some links:
- https://wiki.jasig.org/display/CAS/Proxy+CAS+Walkthrough
- https://apereo.github.io/cas/5.0.x/installation/Configuring-Proxy-Authentication.html (version 5.x where in RODA we are using version 4.x; special attention to #Returning PGT in Validation Response)

**Comment by chalkos** [comment]
Fixed by https://github.com/keeps/roda/commit/31a12f24b220446dca375b856ecebc399f4fa147
