### ISSUE TITLE
When editing basic information about a user, RODA complains about the password (even if I didn't changed that information)

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#984]
![captura de ecra de 2017-05-16 09 55 21](https://cloud.githubusercontent.com/assets/1315759/26097871/eaaffd54-3a1d-11e7-803f-3b6e5a84ff01.png)

**Comment by nunovieira220** [comment]
Solved on 597b70e39c62560cf6407e64b14967645f006174
