### ISSUE TITLE
Desc. metadata validation preservation event should state schema

### ISSUE THREAD

**Issue by luis100** [keeps/roda#985]
The preservation event created by the descriptive metadata validation task only states that the metadata was found to be valid and well-formed, but not against which schema (and schema version). Add this information to the event outcome.

![roda - catalogue 9](https://cloud.githubusercontent.com/assets/631728/26099421/8985213a-3a22-11e7-9c09-7ccdd39c4b44.jpg)

**Comment by nunovieira220** [comment]
Solved on c5ec9fd3b0c5f5a734193c6e1f49ca36bba60941
