### ISSUE TITLE
Some controllers are not registering properly some user information (e.g. ipAddress)

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#986]
Changes to be done:
- Replace UserUtility.getGuest(); by UserUtility.getGuest(request); and set ip address inside that method
- Add HttpServletRequest to all controller methods that don't receive, as parameter, a User (e.g. UserManagement.confirmUserEmail, and others in UserManagement)

**Comment by nunovieira220** [comment]
Solved on baa15be27321bb488a9dab81f9cca8b80fc26b39
