### ISSUE TITLE
Incoherence between i18n used in table and in facets

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#987]
Look at result/resultado values.
Changes: facets i18n should be equal to the ones from the tables (which are the correct ones)
![captura de ecra de 2017-05-18 12 46 54](https://cloud.githubusercontent.com/assets/1315759/26200849/2709fe20-3bc8-11e7-81bc-851e4ac71d91.png)
![captura de ecra de 2017-05-18 12 46 39](https://cloud.githubusercontent.com/assets/1315759/26200850/27352320-3bc8-11e7-8a70-99b5b516f166.png)

**Comment by nunovieira220** [comment]
Solved on  baa15be27321bb488a9dab81f9cca8b80fc26b39
