### ISSUE TITLE
Change button from "Confirm" to "Close"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#992]
There is no decision to be confirmed!

![screen shot 2017-05-23 at 17 28 37](https://cloud.githubusercontent.com/assets/3181302/26364769/571bcdc8-3fdd-11e7-87ba-ea8978f0d911.png)

A double click on the grey area should Copy the content.
See http://www.htmlgoodies.com/html5/other/working-with-clipboard-apis-in-html5-web-apps.html#fbid=eh9tM7GHJWF

**Comment by nunovieira220** [comment]
Solved on f95a6181f427b9838a90c98fb7898bdc6f05bc68
