### ISSUE TITLE
Moving too many transferred resources gives an error

### ISSUE THREAD

**Issue by luis100** [keeps/roda#993]
Moving around 76 transferred resources gives a Toast error "request URI too long" when showing select parent popup.

![roda - transfer](https://cloud.githubusercontent.com/assets/631728/26371458/b4b114a6-3ff2-11e7-9fcb-77bad4ec1102.jpg)

**Comment by luis100** [comment]
Note that this test was run using docker swarm and HTTP solr connection.

**Comment by hsilva-keep** [comment]
Well, it looks like the filter is to big (as it may contain info. about the objects being moved). 
The following code seams to be the reason: https://github.com/keeps/roda/blob/development/roda-ui/roda-wui/src/main/java/org/roda/wui/client/ingest/transfer/IngestTransfer.java#L662 right @nunovieira220 ?

**Comment by nunovieira220** [comment]
Yes, it is possible. It exists already a maximum limit (DIALOG_FILTER_LIMIT_NUMBER) of resources to avoid the excessive creation of filter parameters that exclude children folders, etc.. The limit is now 120 resources, should it be updated to a lower value? @luis100 @hsilva-keep

**Comment by luis100** [comment]
Not sure, the solution could come from the underlying solrj library to use POST instead of GET on the query request. I guess you'll have to analyse possible solutions before going with a simple limitation. If there are no other possible solutions, you'll have to calculate what are the maximum amount of resources by looking on the [maximum size for the URI](http://lucene.472066.n3.nabble.com/URI-is-too-long-td4254270.html) and the space each resource (UUID) filter takes on the query.

**Comment by nunovieira220** [comment]
There are other actions where adding exclusion filter parameters were simply removed. Should they be reviewed too? @luis100

**Comment by luis100** [comment]
Yes, please test them while using an HTTP Solr

**Comment by nunovieira220** [comment]
Solved on 516dcc1ff0fd526d00b49ef324b99d56d554cdde. Can you test it @luis100 ?

**Comment by luis100** [comment]
Solr problems no longer happens, but whenever I move there is always an error on every internal job report : `Could not move transferred resource PROCESSED due to inapropriate move operations`
