### ISSUE TITLE
Job report on failed reindex of logentry has a source that point to an invalid link

### ISSUE THREAD

**Issue by luis100** [keeps/roda#994]
Steps to reproduce:
1. Corrupt a log entry on the file system storage (i.e. make the JSON invalid)
2. Re-index log entries, one should fail
3. Open the job report that failed
4. Click the source log entry link

![roda - 9785511d-b51f-4bc5-a846-b9fe98364d8c-log 33959](https://cloud.githubusercontent.com/assets/631728/26377502/823aaee0-4008-11e7-80de-92ded117252b.jpg)

**Comment by hsilva-keep** [comment]
Well, the right way to proceed in this scenario is to add no source or outcome entity as the entity, most certainly, is not indexed neither we have its uuid to correctly construct the link. 
On the other side, we could at least improve the error description by adding the name/path log file where the error happened.

**Comment by luis100** [comment]
And also the line number, because on the log file there are many logs and some information is needed to know which line made the error.

**Comment by hsilva-keep** [comment]
The line & column number are already present in the exception provided by the JSON parser.

**Comment by luis100** [comment]
No there are not because the log file is a daily log file with one line per each log, each line is a JSON that is parsed independently, this JSON is always on a single line, so the exception will always say line one.

**Comment by hsilva-keep** [comment]
Yes, you're right!

**Comment by nunovieira220** [comment]
Solved on 5c7ad624084233b54858924af68c223ed8b2659c
