### ISSUE TITLE
Transferred resource move select parent list missing complete path

### ISSUE THREAD

**Issue by luis100** [keeps/roda#995]
On the example below it makes it very hard to distinguish the folders because they have the same name but different parent folders.
![roda - transfer 1](https://cloud.githubusercontent.com/assets/631728/26377720/60c657fe-4009-11e7-9f48-4d013a0e8bad.jpg)

**Comment by hsilva-keep** [comment]
Well, it looks like we have two options:
1. Extra column
2. Hover

right @luis100 @jmaferreira? Which one sounds better?

**Comment by luis100** [comment]
The file list has already an option (SearchFileList) that shows the path on the Name column in a light grey color, we could use the same here.

https://github.com/keeps/roda/blob/master/roda-ui/roda-wui/src/main/java/org/roda/wui/client/common/lists/SearchFileList.java#L85

**Comment by hsilva-keep** [comment]
Ok, it seams reasonable to use the same strategy.

**Comment by jmaferreira** [comment]
Extra column is more visible.

**Comment by luis100** [comment]
@jmaferreira  The problem with the extra column is that it looks ugly, because many items will have no parent path (those on root), and also because paths can have different lengths which makes everything less readable. Remember that the is a select windows with not much space.

**Comment by nunovieira220** [comment]
Solved on 20de7b014aef606a3338efa01d292e2cb63f01c3
